DROP TABLE IF EXISTS sales-dev6.t_alteration_history_sales_transaction_header CASCADE;
CREATE TABLE sales-dev6.t_alteration_history_sales_transaction_header(
 transaction_id varchar(57) NOT NULL,
 order_sub_number numeric(4) NOT NULL,
 sales_transaction_id varchar(30) NOT NULL,
 history_type numeric(1) NOT NULL,
 sales_transaction_error_id varchar(57),
 integrated_order_id varchar(27),
 sales_transaction_sub_number numeric(4),
 store_code varchar(10),
 data_creation_date_time timestamptz,
 data_creation_business_date varchar(8),
 cash_register_no numeric(3),
 receipt_no varchar(4),
 sales_linkage_type numeric(1),
 sales_transaction_type varchar(6),
 return_type numeric(1),
 system_brand_code varchar(4),
 system_business_code varchar(10),
 system_country_code varchar(3),
 channel_code varchar(10),
 order_status varchar(50),
 order_substatus varchar(50),
 order_status_update_date varchar(8),
 order_status_last_update_date_time timestamptz,
 order_cancelled_date_time timestamptz,
 booking_store_code varchar(10),
 booking_store_system_brand_code varchar(4),
 booking_store_system_business_code varchar(10),
 booking_store_system_country_code varchar(3),
 payment_status varchar(50),
 payment_store_code varchar(10),
 payment_store_system_brand_code varchar(4),
 payment_store_system_business_code varchar(10),
 payment_store_system_country_code varchar(3),
 transfer_out_status varchar(50),
 shipment_status varchar(50),
 shipment_store_code varchar(10),
 shipment_store_system_brand_code varchar(4),
 shipment_store_system_business_code varchar(10),
 shipment_store_system_country_code varchar(3),
 receiving_status varchar(50),
 receipt_store_code varchar(10),
 receipt_store_system_brand_code varchar(4),
 receipt_store_system_business_code varchar(10),
 receipt_store_system_country_code varchar(3),
 customer_id varchar(30),
 customer_type varchar(10),
 order_number_for_store_payment varchar(27),
 advance_received_store_code varchar(10),
 advance_received_store_system_brand_code varchar(4),
 advance_received_store_system_business_code varchar(10),
 advance_received_store_system_country_code varchar(3),
 operator_code varchar(18),
 original_transaction_id varchar(30),
 original_cash_register_no numeric(3),
 original_receipt_no varchar(4),
 deposit_currency_code varchar(3),
 deposit_value numeric(24,4),
 change_currency_code varchar(3),
 change_value numeric(24,4),
 receipt_no_for_credit_card_cancellation varchar(11),
 receipt_no_for_credit_card varchar(30),
 receipt_issued_flag boolean DEFAULT FALSE NOT NULL,
 e_receipt_target_flag boolean DEFAULT FALSE NOT NULL,
 processing_company_code varchar(20),
 employee_sale_flag boolean DEFAULT FALSE NOT NULL,
 consistency_sales_flag boolean DEFAULT FALSE NOT NULL,
 corporate_id varchar(20),
 sales_transaction_discount_flag boolean DEFAULT FALSE NOT NULL,
 sales_transaction_discount_type varchar(1),
 sales_transaction_discount_amount_rate_currency_code varchar(3),
 sales_transaction_discount_amount_rate numeric(24,4),
 token_code varchar(30),
 create_user_id varchar(30),
 create_datetime timestamptz NOT NULL,
 create_program_id varchar(30),
 update_user_id varchar(30),
 update_datetime timestamptz,
 update_program_id varchar(30),
  CONSTRAINT t_alteration_history_sales_transaction_header_pk
   PRIMARY KEY(transaction_id,order_sub_number,sales_transaction_id,history_type)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;
 CREATE INDEX t_alteration_history_sales_transaction_header_KEY1 ON sales-dev6.t_alteration_history_sales_transaction_header(sales_transaction_error_id);


commit;
