DROP TABLE IF EXISTS sales-dev6.t_error_evacuation_sales_transaction_detail CASCADE;
CREATE TABLE sales-dev6.t_error_evacuation_sales_transaction_detail(
 transaction_id varchar(57) NOT NULL,
 order_sub_number numeric(4) NOT NULL,
 sales_transaction_id varchar(30) NOT NULL,
 detail_sub_number numeric(4) NOT NULL,
 sales_transaction_error_id varchar(57),
 item_detail_sub_number numeric(4),
 sales_transaction_type varchar(6),
 system_brand_code varchar(4),
 l2_item_code varchar(20),
 display_l2_item_code varchar(25),
 l2_product_name varchar(250),
 l3_item_code varchar(25),
 l3_pos_product_name varchar(250),
 product_classification varchar(6),
 non_md_type varchar(6),
 non_md_code varchar(25),
 service_code varchar(50),
 epc_code varchar(24),
 g_department_code varchar(6),
 major_category_code varchar(4),
 quantity_code varchar(1),
 detail_quantity numeric(16,4),
 item_cost_currency_code varchar(3),
 item_cost_value numeric(24,4),
 initial_selling_price_currency_code varchar(3),
 initial_selling_price numeric(24,4),
 bclass_price_currency_code varchar(3),
 bclass_price numeric(24,4),
 new_price_currency_code varchar(3),
 new_price numeric(24,4),
 retail_unit_price_tax_excluded_currency_code varchar(3),
 retail_unit_price_tax_excluded numeric(24,4),
 retail_unit_price_tax_included_currency_code varchar(3),
 retail_unit_price_tax_included numeric(24,4),
 sales_amount_tax_excluded_currency_code varchar(3),
 sales_amount_tax_excluded numeric(24,4),
 sales_amount_tax_included_currency_code varchar(3),
 sales_amount_tax_included numeric(24,4),
 calculation_unavailable_type varchar(10),
 order_status_update_date varchar(8),
 order_status_last_update_date_time timestamptz,
 order_status varchar(50),
 order_substatus varchar(50),
 booking_store_code varchar(10),
 booking_store_system_brand_code varchar(4),
 booking_store_system_business_code varchar(10),
 booking_store_system_country_code varchar(3),
 shipment_store_code varchar(10),
 shipment_store_system_brand_code varchar(4),
 shipment_store_system_business_code varchar(10),
 shipment_store_system_country_code varchar(3),
 receipt_store_code varchar(10),
 receipt_store_system_brand_code varchar(4),
 receipt_store_system_business_code varchar(10),
 receipt_store_system_country_code varchar(3),
 contribution_sales_representative varchar(10),
 customer_id varchar(30),
 bundle_purchase_applicable_quantity numeric(16,4),
 bundle_purchase_applicable_price_currency_code varchar(3),
 bundle_purchase_applicable_price numeric(24,4),
 bundle_purchase_index numeric(3),
 limited_amount_promotion_count numeric(2),
 store_item_discount_type varchar(10),
 store_item_discount_currency_code varchar(3),
 store_item_discount_setting numeric(24,4),
 store_bundle_sale_flag boolean DEFAULT FALSE NOT NULL,
 store_bundle_sale_price_currency_code varchar(3),
 store_bundle_sale_price numeric(24,4),
 set_sales_detail_index numeric(3),
 taxation_type varchar(10),
 tax_system_type varchar(10),
 create_user_id varchar(30),
 create_datetime timestamptz NOT NULL,
 create_program_id varchar(30),
 update_user_id varchar(30),
 update_datetime timestamptz,
 update_program_id varchar(30),
  CONSTRAINT t_error_evacuation_sales_transaction_detail_pk
   PRIMARY KEY(transaction_id,order_sub_number,sales_transaction_id,detail_sub_number)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;
 CREATE INDEX t_error_evacuation_sales_transaction_detail_KEY1 ON sales-dev6.t_error_evacuation_sales_transaction_detail(sales_transaction_error_id);


commit;
