package com.fastretailing.dcp.sales.common.entity.optional;

import lombok.Data;

@Data
public class AlterationHistoryOrderInformationOptionalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alteration_history_order_information.transaction_id
     *
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alteration_history_order_information.integrated_order_id
     *
     */
    private String integratedOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alteration_history_order_information.history_type
     *
     */
    private Integer historyType;
}
