/**
 * @(#)BusinessCountryStateSettingMasterOptional.java
 *
 *                                                    Copyright (c) 2018 Fast Retailing Corporation.
 */

package com.fastretailing.dcp.sales.common.entity.optional;

import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class BusinessCountryStateSettingMasterOptional
        extends BusinessCountryStateSettingMasterOptionalKey {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.system_brand_code
     */
    private String systemBrandCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.system_business_code
     */
    private String systemBusinessCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.system_country_code
     */
    private String systemCountryCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.state_code
     */
    private String stateCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.variable_type
     */
    private String variableType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.display_order
     */
    private int displayOrder;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.create_user_id
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.create_datetime
     */
    private OffsetDateTime createDatetime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.create_program_id
     */
    private String createProgramId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.update_user_id
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.update_datetime
     */
    private OffsetDateTime updateDatetime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_business_country_state_setting.update_program_id
     */
    private String updateProgramId;
}
