package com.fastretailing.dcp.sales.common.entity.optional;

import lombok.Data;

@Data
public class ErrorEvacuationSalesTransactionTenderOptionalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_tender.transaction_id
     *
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_tender.order_sub_number
     *
     */
    private Integer orderSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_tender.sales_transaction_id
     *
     */
    private String salesTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_tender.tender_group
     *
     */
    private String tenderGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_tender.tender_id
     *
     */
    private String tenderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_tender.tender_sub_number
     *
     */
    private Integer tenderSubNumber;
}
