package com.fastretailing.dcp.sales.common.entity.optional;

import lombok.Data;

@Data
public class ErrorEvacuationSalesTransactionHeaderOptionalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_header.transaction_id
     *
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_header.order_sub_number
     *
     */
    private Integer orderSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_error_evacuation_sales_transaction_header.sales_transaction_id
     *
     */
    private String salesTransactionId;
}
