package com.fastretailing.dcp.sales.common.entity.optional;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ItemMasterOptional extends ItemMasterOptionalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.system_business_code
     *
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.item_code_type
     *
     */
    private String itemCodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.view_item_code
     *
     */
    private String viewItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.year_code
     *
     */
    private String yearCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.view_year_type
     *
     */
    private String viewYearType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.season_code
     *
     */
    private String seasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.detail_season_code
     *
     */
    private String detailSeasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.sales_country_code
     *
     */
    private String salesCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.color_code
     *
     */
    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.size_code
     *
     */
    private String sizeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.pattern_length_code
     *
     */
    private String patternLengthCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.major_category_code
     *
     */
    private String majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.class_code
     *
     */
    private String classCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.middle_category_code
     *
     */
    private String middleCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.small_category_value
     *
     */
    private Integer smallCategoryValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.item_parent
     *
     */
    private String itemParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.item_crand_parent
     *
     */
    private String itemCrandParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.item_level
     *
     */
    private Integer itemLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.transaction_level
     *
     */
    private Integer transactionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.pack_flag
     *
     */
    private boolean packFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.simple_item_pack_flag
     *
     */
    private boolean simpleItemPackFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.contains_inner_kind
     *
     */
    private String containsInnerKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.sellable_flag
     *
     */
    private boolean sellableFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.orderable_flag
     *
     */
    private boolean orderableFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.pack_status
     *
     */
    private String packStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.order_unit_type
     *
     */
    private String orderUnitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.asort_code
     *
     */
    private String asortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.fob
     *
     */
    private BigDecimal fob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.cost_price_sequence
     *
     */
    private Integer costPriceSequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.stock_buying_type_code
     *
     */
    private String stockBuyingTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.initial_selling_price
     *
     */
    private BigDecimal initialSellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.sales_zone_group
     *
     */
    private Integer salesZoneGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.standard_sales_unit
     *
     */
    private String standardSalesUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.item_name
     *
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.intern_item_name
     *
     */
    private String internItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.pos_item_name
     *
     */
    private String posItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.second_pos_item_name
     *
     */
    private String secondPosItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.external_item_name_1
     *
     */
    private String externalItemName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.external_item_name_2
     *
     */
    private String externalItemName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.external_item_name_3
     *
     */
    private String externalItemName3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.external_item_name_4
     *
     */
    private String externalItemName4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.second_item_name
     *
     */
    private String secondItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.picking_shipment_flag
     *
     */
    private boolean pickingShipmentFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.direct_delivery_unit_quantity
     *
     */
    private Integer directDeliveryUnitQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.regular_item_flag
     *
     */
    private boolean regularItemFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.color_size_management_flag
     *
     */
    private boolean colorSizeManagementFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.b_item_return_possible_flag
     *
     */
    private boolean bItemReturnPossibleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.status
     *
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.delivery_type_code
     *
     */
    private String deliveryTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.supplier_code
     *
     */
    private String supplierCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.stock_buying_cost
     *
     */
    private BigDecimal stockBuyingCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.packing_quantity
     *
     */
    private Integer packingQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.picking_unit_quantity
     *
     */
    private Integer pickingUnitQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.selling_price
     *
     */
    private BigDecimal sellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.selling_unit
     *
     */
    private String sellingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.taxation_flag
     *
     */
    private boolean taxationFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.batch_region
     *
     */
    private Integer batchRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item.update_program_id
     *
     */
    private String updateProgramId;
}
