package com.fastretailing.dcp.sales.common.entity.optional;

import lombok.Data;

@Data
public class SalesReportTransactionItemDetailOptionalKey {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.sales_transaction_id
     *
     */
    private String salesTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.detail_sub_number
     *
     */
    private Integer detailSubNumber;
}
