package com.fastretailing.dcp.sales.common.entity.optional;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

public class SalesReportTransactionTenderOptionalCondition {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public SalesReportTransactionTenderOptionalCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2,
                String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSalesTransactionIdIsNull() {
            addCriterion("sales_transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdIsNotNull() {
            addCriterion("sales_transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdEqualTo(String value) {
            addCriterion("sales_transaction_id =", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdNotEqualTo(String value) {
            addCriterion("sales_transaction_id <>", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdGreaterThan(String value) {
            addCriterion("sales_transaction_id >", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("sales_transaction_id >=", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdLessThan(String value) {
            addCriterion("sales_transaction_id <", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("sales_transaction_id <=", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdLike(String value) {
            addCriterion("sales_transaction_id like", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdNotLike(String value) {
            addCriterion("sales_transaction_id not like", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdIn(List<String> values) {
            addCriterion("sales_transaction_id in", values, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdNotIn(List<String> values) {
            addCriterion("sales_transaction_id not in", values, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdBetween(String value1, String value2) {
            addCriterion("sales_transaction_id between", value1, value2, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdNotBetween(String value1, String value2) {
            addCriterion("sales_transaction_id not between", value1, value2, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andTenderGroupIsNull() {
            addCriterion("tender_group is null");
            return (Criteria) this;
        }

        public Criteria andTenderGroupIsNotNull() {
            addCriterion("tender_group is not null");
            return (Criteria) this;
        }

        public Criteria andTenderGroupEqualTo(String value) {
            addCriterion("tender_group =", value, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupNotEqualTo(String value) {
            addCriterion("tender_group <>", value, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupGreaterThan(String value) {
            addCriterion("tender_group >", value, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupGreaterThanOrEqualTo(String value) {
            addCriterion("tender_group >=", value, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupLessThan(String value) {
            addCriterion("tender_group <", value, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupLessThanOrEqualTo(String value) {
            addCriterion("tender_group <=", value, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupLike(String value) {
            addCriterion("tender_group like", value, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupNotLike(String value) {
            addCriterion("tender_group not like", value, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupIn(List<String> values) {
            addCriterion("tender_group in", values, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupNotIn(List<String> values) {
            addCriterion("tender_group not in", values, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupBetween(String value1, String value2) {
            addCriterion("tender_group between", value1, value2, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderGroupNotBetween(String value1, String value2) {
            addCriterion("tender_group not between", value1, value2, "tenderGroup");
            return (Criteria) this;
        }

        public Criteria andTenderIdIsNull() {
            addCriterion("tender_id is null");
            return (Criteria) this;
        }

        public Criteria andTenderIdIsNotNull() {
            addCriterion("tender_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenderIdEqualTo(Integer value) {
            addCriterion("tender_id =", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotEqualTo(Integer value) {
            addCriterion("tender_id <>", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdGreaterThan(Integer value) {
            addCriterion("tender_id >", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tender_id >=", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdLessThan(Integer value) {
            addCriterion("tender_id <", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdLessThanOrEqualTo(Integer value) {
            addCriterion("tender_id <=", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdIn(List<Integer> values) {
            addCriterion("tender_id in", values, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotIn(List<Integer> values) {
            addCriterion("tender_id not in", values, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdBetween(Integer value1, Integer value2) {
            addCriterion("tender_id between", value1, value2, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tender_id not between", value1, value2, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberIsNull() {
            addCriterion("tender_sub_number is null");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberIsNotNull() {
            addCriterion("tender_sub_number is not null");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberEqualTo(Integer value) {
            addCriterion("tender_sub_number =", value, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberNotEqualTo(Integer value) {
            addCriterion("tender_sub_number <>", value, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberGreaterThan(Integer value) {
            addCriterion("tender_sub_number >", value, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("tender_sub_number >=", value, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberLessThan(Integer value) {
            addCriterion("tender_sub_number <", value, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberLessThanOrEqualTo(Integer value) {
            addCriterion("tender_sub_number <=", value, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberIn(List<Integer> values) {
            addCriterion("tender_sub_number in", values, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberNotIn(List<Integer> values) {
            addCriterion("tender_sub_number not in", values, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberBetween(Integer value1, Integer value2) {
            addCriterion("tender_sub_number between", value1, value2, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andTenderSubNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("tender_sub_number not between", value1, value2, "tenderSubNumber");
            return (Criteria) this;
        }

        public Criteria andPaymentSignIsNull() {
            addCriterion("payment_sign is null");
            return (Criteria) this;
        }

        public Criteria andPaymentSignIsNotNull() {
            addCriterion("payment_sign is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentSignEqualTo(String value) {
            addCriterion("payment_sign =", value, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignNotEqualTo(String value) {
            addCriterion("payment_sign <>", value, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignGreaterThan(String value) {
            addCriterion("payment_sign >", value, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignGreaterThanOrEqualTo(String value) {
            addCriterion("payment_sign >=", value, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignLessThan(String value) {
            addCriterion("payment_sign <", value, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignLessThanOrEqualTo(String value) {
            addCriterion("payment_sign <=", value, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignLike(String value) {
            addCriterion("payment_sign like", value, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignNotLike(String value) {
            addCriterion("payment_sign not like", value, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignIn(List<String> values) {
            addCriterion("payment_sign in", values, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignNotIn(List<String> values) {
            addCriterion("payment_sign not in", values, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignBetween(String value1, String value2) {
            addCriterion("payment_sign between", value1, value2, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andPaymentSignNotBetween(String value1, String value2) {
            addCriterion("payment_sign not between", value1, value2, "paymentSign");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeIsNull() {
            addCriterion("tax_included_payment_amount_currency_code is null");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeIsNotNull() {
            addCriterion("tax_included_payment_amount_currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeEqualTo(String value) {
            addCriterion("tax_included_payment_amount_currency_code =", value,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeNotEqualTo(String value) {
            addCriterion("tax_included_payment_amount_currency_code <>", value,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeGreaterThan(String value) {
            addCriterion("tax_included_payment_amount_currency_code >", value,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("tax_included_payment_amount_currency_code >=", value,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeLessThan(String value) {
            addCriterion("tax_included_payment_amount_currency_code <", value,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("tax_included_payment_amount_currency_code <=", value,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeLike(String value) {
            addCriterion("tax_included_payment_amount_currency_code like", value,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeNotLike(String value) {
            addCriterion("tax_included_payment_amount_currency_code not like", value,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeIn(List<String> values) {
            addCriterion("tax_included_payment_amount_currency_code in", values,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeNotIn(List<String> values) {
            addCriterion("tax_included_payment_amount_currency_code not in", values,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeBetween(String value1,
                String value2) {
            addCriterion("tax_included_payment_amount_currency_code between", value1, value2,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountCurrencyCodeNotBetween(String value1,
                String value2) {
            addCriterion("tax_included_payment_amount_currency_code not between", value1, value2,
                    "taxIncludedPaymentAmountCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueIsNull() {
            addCriterion("tax_included_payment_amount_value is null");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueIsNotNull() {
            addCriterion("tax_included_payment_amount_value is not null");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueEqualTo(BigDecimal value) {
            addCriterion("tax_included_payment_amount_value =", value,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueNotEqualTo(BigDecimal value) {
            addCriterion("tax_included_payment_amount_value <>", value,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueGreaterThan(BigDecimal value) {
            addCriterion("tax_included_payment_amount_value >", value,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_included_payment_amount_value >=", value,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueLessThan(BigDecimal value) {
            addCriterion("tax_included_payment_amount_value <", value,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_included_payment_amount_value <=", value,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueIn(List<BigDecimal> values) {
            addCriterion("tax_included_payment_amount_value in", values,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueNotIn(List<BigDecimal> values) {
            addCriterion("tax_included_payment_amount_value not in", values,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueBetween(BigDecimal value1,
                BigDecimal value2) {
            addCriterion("tax_included_payment_amount_value between", value1, value2,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andTaxIncludedPaymentAmountValueNotBetween(BigDecimal value1,
                BigDecimal value2) {
            addCriterion("tax_included_payment_amount_value not between", value1, value2,
                    "taxIncludedPaymentAmountValue");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIsNull() {
            addCriterion("create_program_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIsNotNull() {
            addCriterion("create_program_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdEqualTo(String value) {
            addCriterion("create_program_id =", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotEqualTo(String value) {
            addCriterion("create_program_id <>", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdGreaterThan(String value) {
            addCriterion("create_program_id >", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_program_id >=", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLessThan(String value) {
            addCriterion("create_program_id <", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLessThanOrEqualTo(String value) {
            addCriterion("create_program_id <=", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLike(String value) {
            addCriterion("create_program_id like", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotLike(String value) {
            addCriterion("create_program_id not like", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIn(List<String> values) {
            addCriterion("create_program_id in", values, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotIn(List<String> values) {
            addCriterion("create_program_id not in", values, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdBetween(String value1, String value2) {
            addCriterion("create_program_id between", value1, value2, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotBetween(String value1, String value2) {
            addCriterion("create_program_id not between", value1, value2, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIsNull() {
            addCriterion("update_program_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIsNotNull() {
            addCriterion("update_program_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdEqualTo(String value) {
            addCriterion("update_program_id =", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotEqualTo(String value) {
            addCriterion("update_program_id <>", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdGreaterThan(String value) {
            addCriterion("update_program_id >", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_program_id >=", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLessThan(String value) {
            addCriterion("update_program_id <", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLessThanOrEqualTo(String value) {
            addCriterion("update_program_id <=", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLike(String value) {
            addCriterion("update_program_id like", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotLike(String value) {
            addCriterion("update_program_id not like", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIn(List<String> values) {
            addCriterion("update_program_id in", values, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotIn(List<String> values) {
            addCriterion("update_program_id not in", values, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdBetween(String value1, String value2) {
            addCriterion("update_program_id between", value1, value2, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotBetween(String value1, String value2) {
            addCriterion("update_program_id not between", value1, value2, "updateProgramId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue,
                String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
