/**
 * @(#)SalesReportTransactionDiscountOptional.java
 *
 *                                                 Copyright (c) 2018 Fast Retailing Corporation.
 */
package com.fastretailing.dcp.sales.common.entity.optional;

import java.math.BigDecimal;
import lombok.Data;

@Data
public class SalesReportTransactionDiscountOptional {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_discount.sales_transaction_id
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String salesTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_discount.detail_sub_number
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private Integer detailSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_discount.item_discount_sub_number
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private Integer itemDiscountSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_discount.quantity_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String quantityCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_discount.discount_quantity
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private Integer discountQuantity;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_discount.discount_amount_tax_excluded
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal discountAmountTaxExcluded;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_discount.discount_amount_tax_included
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal discountAmountTaxIncluded;
}
