/**
 * @(#)SalesReportTransactionDetailOptional.java
 *
 *                                               Copyright (c) 2018 Fast Retailing Corporation.
 */

package com.fastretailing.dcp.sales.common.entity.optional;

import java.math.BigDecimal;
import lombok.Data;

@Data
public class SalesReportTransactionDetailOptional {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.sales_transaction_id
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String salesTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.detail_sub_number
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private Integer detailSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.item_detail_sub_number
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private Integer itemDetailSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.sales_transaction_type
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String salesTransactionType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.system_brand_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String systemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.system_business_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.system_country_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String systemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.l3_item_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String l3ItemCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.product_classification
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String productClassification;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.non_md_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String nonMdCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.g_department_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String gDepartmentCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.major_category_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.quantity_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String quantityCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.detail_quantity
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal detailQuantity;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.sales_amount_tax_excluded
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal salesAmountTaxExcluded;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.sales_amount_tax_included
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal salesAmountTaxIncluded;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_report_transaction_detail.calculation_unavailable_type
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String calculationUnavailableType;
}
