package com.fastretailing.dcp.sales.common.entity.optional;

import lombok.Data;

@Data
public class SalesErrorSalesTransactionDetailInformationOptionalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail_info.transaction_id
     *
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail_info.order_sub_number
     *
     */
    private Integer orderSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail_info.sales_transaction_id
     *
     */
    private String salesTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail_info.detail_sub_number
     *
     */
    private Integer detailSubNumber;
}
