/**
 * @(#)SalesErrorSalesTransactionTenderDetailOptional.java
 *
 *                                                         Copyright (c) 2018 Fast Retailing
 *                                                         Corporation.
 */

package com.fastretailing.dcp.sales.common.entity.optional;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;

/**
 * Sales error sales transaction tender detail optional.
 */
@Data
public class SalesErrorSalesTransactionTenderDetailOptional {
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_tender.transaction_id
    *
    */
   private String transactionId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_tender.order_sub_number
    *
    */
   private Integer orderSubNumber;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_tender.sales_transaction_id
    *
    */
   private String salesTransactionId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_tender.tender_group
    *
    */
   private String tenderGroup;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_tender.tender_id
    *
    */
   private String tenderId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_tender.tender_sub_number
    *
    */
   private Integer tenderSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.ims_tender_id
     *
     */
    private String imsTenderId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.ims_tender_group
     *
     */
    private String imsTenderGroup;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.tender_name
     *
     */
    private String tenderName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.payment_sign
     *
     */
    private String paymentSign;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.tax_included_payment_amount_currency_code
     *
     */
    private String taxIncludedPaymentAmountCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.tax_included_payment_amount_value
     *
     */
    private BigDecimal taxIncludedPaymentAmountValue;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_tender.update_program_id
     *
     */
    private String updateProgramId;
}
