/**
 * @(#)SalesErrorSalesTransactionTotalAmountDetailOptional.java
 *
 *                                                              Copyright (c) 2018 Fast Retailing
 *                                                              Corporation.
 */

package com.fastretailing.dcp.sales.common.entity.optional;

import java.math.BigDecimal;
import java.time.OffsetDateTime;import lombok.Data;
import lombok.ToString;

/**
 * Sales error sales transaction total amount detail optional.
 */
@Data
@ToString(callSuper = true)
public class SalesErrorSalesTransactionTotalAmountDetailOptional {
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_total_amount.transaction_id
    *
    */
   private String transactionId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_total_amount.order_sub_number
    *
    */
   private Integer orderSubNumber;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_total_amount.sales_transaction_id
    *
    */
   private String salesTransactionId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sales_error_sales_transaction_total_amount.total_type
    *
    */
   private String totalType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.total_amount_sub_number
     *
     */
    private Integer totalAmountSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.total_amount_tax_excluded_currency_code
     *
     */
    private String totalAmountTaxExcludedCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.total_amount_tax_excluded_value
     *
     */
    private BigDecimal totalAmountTaxExcludedValue;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.total_amount_tax_included_currency_code
     *
     */
    private String totalAmountTaxIncludedCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.total_amount_tax_included_value
     *
     */
    private BigDecimal totalAmountTaxIncludedValue;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.tax_rate
     *
     */
    private BigDecimal taxRate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.sales_transaction_information_1
     *
     */
    private String salesTransactionInformation1;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.sales_transaction_information_2
     *
     */
    private String salesTransactionInformation2;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.sales_transaction_information_3
     *
     */
    private String salesTransactionInformation3;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_transaction_total_amount.update_program_id
     *
     */
    private String updateProgramId;
}
