package com.fastretailing.dcp.sales.common.entity.optional;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SalesErrorSalesTransactionDetailOptional extends SalesErrorSalesTransactionDetailOptionalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.item_detail_sub_number
     *
     */
    private Integer itemDetailSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.sales_transaction_type
     *
     */
    private String salesTransactionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.system_brand_code
     *
     */
    private String systemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.l2_item_code
     *
     */
    private String l2ItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.display_l2_item_code
     *
     */
    private String displayL2ItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.l2_product_name
     *
     */
    private String l2ProductName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.l3_item_code
     *
     */
    private String l3ItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.l3_pos_product_name
     *
     */
    private String l3PosProductName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.product_classification
     *
     */
    private String productClassification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.non_md_type
     *
     */
    private String nonMdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.non_md_code
     *
     */
    private String nonMdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.service_code
     *
     */
    private String serviceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.epc_code
     *
     */
    private String epcCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.g_department_code
     *
     */
    private String gDepartmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.major_category_code
     *
     */
    private String majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.quantity_code
     *
     */
    private String quantityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.detail_quantity
     *
     */
    private BigDecimal detailQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.item_cost_currency_code
     *
     */
    private String itemCostCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.item_cost_value
     *
     */
    private BigDecimal itemCostValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.initial_selling_price_currency_code
     *
     */
    private String initialSellingPriceCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.initial_selling_price
     *
     */
    private BigDecimal initialSellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.bclass_price_currency_code
     *
     */
    private String bclassPriceCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.bclass_price
     *
     */
    private BigDecimal bclassPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.new_price_currency_code
     *
     */
    private String newPriceCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.new_price
     *
     */
    private BigDecimal newPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.retail_unit_price_tax_excluded_currency_code
     *
     */
    private String retailUnitPriceTaxExcludedCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.retail_unit_price_tax_excluded
     *
     */
    private BigDecimal retailUnitPriceTaxExcluded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.retail_unit_price_tax_included_currency_code
     *
     */
    private String retailUnitPriceTaxIncludedCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.retail_unit_price_tax_included
     *
     */
    private BigDecimal retailUnitPriceTaxIncluded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.sales_amount_tax_excluded_currency_code
     *
     */
    private String salesAmountTaxExcludedCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.sales_amount_tax_excluded
     *
     */
    private BigDecimal salesAmountTaxExcluded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.sales_amount_tax_included_currency_code
     *
     */
    private String salesAmountTaxIncludedCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.sales_amount_tax_included
     *
     */
    private BigDecimal salesAmountTaxIncluded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.calculation_unavailable_type
     *
     */
    private String calculationUnavailableType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.order_status_update_date
     *
     */
    private String orderStatusUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.order_status_last_update_date_time
     *
     */
    private OffsetDateTime orderStatusLastUpdateDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.order_status
     *
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.order_substatus
     *
     */
    private String orderSubstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.booking_store_code
     *
     */
    private String bookingStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.booking_store_system_brand_code
     *
     */
    private String bookingStoreSystemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.booking_store_system_business_code
     *
     */
    private String bookingStoreSystemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.booking_store_system_country_code
     *
     */
    private String bookingStoreSystemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.shipment_store_code
     *
     */
    private String shipmentStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.shipment_store_system_brand_code
     *
     */
    private String shipmentStoreSystemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.shipment_store_system_business_code
     *
     */
    private String shipmentStoreSystemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.shipment_store_system_country_code
     *
     */
    private String shipmentStoreSystemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.receipt_store_code
     *
     */
    private String receiptStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.receipt_store_system_brand_code
     *
     */
    private String receiptStoreSystemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.receipt_store_system_business_code
     *
     */
    private String receiptStoreSystemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.receipt_store_system_country_code
     *
     */
    private String receiptStoreSystemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.contribution_sales_representative
     *
     */
    private String contributionSalesRepresentative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.customer_id
     *
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.bundle_purchase_applicable_quantity
     *
     */
    private BigDecimal bundlePurchaseApplicableQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.bundle_purchase_applicable_price_currency_code
     *
     */
    private String bundlePurchaseApplicablePriceCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.bundle_purchase_applicable_price
     *
     */
    private BigDecimal bundlePurchaseApplicablePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.bundle_purchase_index
     *
     */
    private Integer bundlePurchaseIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.limited_amount_promotion_count
     *
     */
    private Integer limitedAmountPromotionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.store_item_discount_type
     *
     */
    private String storeItemDiscountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.store_item_discount_currency_code
     *
     */
    private String storeItemDiscountCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.store_item_discount_setting
     *
     */
    private BigDecimal storeItemDiscountSetting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.store_bundle_sale_flag
     *
     */
    private boolean storeBundleSaleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.store_bundle_sale_price_currency_code
     *
     */
    private String storeBundleSalePriceCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.store_bundle_sale_price
     *
     */
    private BigDecimal storeBundleSalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.set_sales_detail_index
     *
     */
    private Integer setSalesDetailIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.taxation_type
     *
     */
    private String taxationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.tax_system_type
     *
     */
    private String taxSystemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_detail.update_program_id
     *
     */
    private String updateProgramId;
}
