/**
 * @(#)SalesErrorSalesOrderDetailInformationOptional.java
 *
 *                                                        Copyright (c) 2018 Fast Retailing
 *                                                        Corporation.
 */

package com.fastretailing.dcp.sales.common.entity.optional;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Sales error sales order detail information optional.
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SalesErrorSalesOrderDetailInformationOptional
        extends SalesErrorSalesOrderInformationOptionalKey {

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.register_no
     *
     * @mbg.generated
     */
    private String registerNo;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.receipt_no
     *
     * @mbg.generated
     */
    private String receiptNo;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.order_barcode_number
     *
     * @mbg.generated
     */
    private String orderBarcodeNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.store_code
     *
     * @mbg.generated
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.system_brand_code
     *
     * @mbg.generated
     */
    private String systemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.system_business_code
     *
     * @mbg.generated
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.system_country_code
     *
     * @mbg.generated
     */
    private String systemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.channel_code
     *
     * @mbg.generated
     */
    private String channelCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.update_type
     *
     * @mbg.generated
     */
    private String updateType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.order_confirmation_business_date
     *
     * @mbg.generated
     */
    private String orderConfirmationBusinessDate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.order_confirmation_date_time
     *
     * @mbg.generated
     */
    private OffsetDateTime orderConfirmationDateTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.error_check_type
     *
     * @mbg.generated
     */
    private Integer errorCheckType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.data_alteration_sales_linkage_type
     *
     * @mbg.generated
     */
    private Integer dataAlterationSalesLinkageType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.data_alteration_backbone_linkage_type
     *
     * @mbg.generated
     */
    private Integer dataAlterationBackboneLinkageType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.data_alteration_editing_flag
     *
     * @mbg.generated
     */
    private boolean dataAlterationEditingFlag;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.data_alteration_user_id
     *
     * @mbg.generated
     */
    private String dataAlterationUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.create_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.create_program_id
     *
     * @mbg.generated
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.update_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_sales_error_sales_order_information.update_program_id
     *
     * @mbg.generated
     */
    private String updateProgramId;
}
