/**
 * @(#)StoreHourlyTwoDigitCategoryResultOptional.java
 *
 *                                                    Copyright (c) 2018 Fast Retailing Corporation.
 */
package com.fastretailing.dcp.sales.common.entity.optional;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;

@Data
public class StoreHourlyTwoDigitCategoryResultOptional {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.business_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private Integer businessCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.store_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.business_date
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String businessDate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.time_local
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String timeLocal;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.system_brand_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String systemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.system_business_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.tran_create_date
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String tranCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.eai_update_datetime
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private OffsetDateTime eaiUpdateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.eai_update_type
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String eaiUpdateType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.eai_send_status
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String eaiSendStatus;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.eai_send_datetime
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String eaiSendDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.time_utc
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String timeUtc;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.sales_hour
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String salesHour;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.sales_result_amount_of_money
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal salesResultAmountOfMoney;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.sales_quantity
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal salesQuantity;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.number_of_customers
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal numberOfCustomers;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.sales_discount_amount
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal salesDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.sales_return_amount
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal salesReturnAmount;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.non_item_sales_amount
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private BigDecimal nonItemSalesAmount;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.major_category_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.class_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String classCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.middle_category_code
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String middleCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.create_user_id
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.create_datetime
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.create_program_id
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.update_user_id
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.update_datetime
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_store_hourly_two_digit_category_result.update_program_id
     *
     * @mbg.generated Thu May 24 10:26:57 JST 2018
     */
    private String updateProgramId;
}
