package com.fastretailing.dcp.sales.common.entity.optional;

import lombok.Data;

@Data
public class TranslationTenderMasterOptionalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.store_code
     *
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.tender_id
     *
     */
    private String tenderId;
}
