package com.fastretailing.dcp.sales.common.entity.optional;

import java.time.OffsetDateTime;
import lombok.Data;

@Data
public class TranslationStoreCodeMasterOptional {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.store_code
     *
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.store_name
     *
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.view_store_code
     *
     */
    private String viewStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.integrate_db_store_code
     *
     */
    private String integrateDbStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.system_brand_code
     *
     */
    private String systemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.system_business_code
     *
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.business_name
     *
     */
    private String businessName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.block_code
     *
     */
    private String blockCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.block_name
     *
     */
    private String blockName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.area_code
     *
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.area_name
     *
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.system_country_code
     *
     */
    private String systemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.country_name
     *
     */
    private String countryName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.batch_region
     *
     */
    private Integer batchRegion;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.integrate_db_business_code
     *
     */
    private String integrateDbBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.store_device_rmvl_date
     *
     */
    private OffsetDateTime storeDeviceRmvlDate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.send_target_store_flag
     *
     */
    private boolean sendTargetStoreFlag;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * m_trans_store_code.update_program_id
     *
     */
    private String updateProgramId;
}
