package com.fastretailing.dcp.sales.common.entity.work;

import java.math.BigDecimal;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ItemWork extends ItemWorkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.eai_update_type
     *
     */
    private String eaiUpdateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.eai_send_status
     *
     */
    private String eaiSendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.eai_send_date
     *
     */
    private String eaiSendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.batch_region
     *
     */
    private Integer batchRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.view_item_code
     *
     */
    private String viewItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.year_code
     *
     */
    private String yearCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.view_year_type
     *
     */
    private String viewYearType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.season_code
     *
     */
    private String seasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.sales_country_code
     *
     */
    private String salesCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.color_code
     *
     */
    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.size_code
     *
     */
    private String sizeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.pattern_length_code
     *
     */
    private String patternLengthCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.major_category_code
     *
     */
    private Integer majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.class_code
     *
     */
    private Integer classCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.middle_category_code
     *
     */
    private Integer middleCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.item_parent
     *
     */
    private String itemParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.item_crand_parent
     *
     */
    private String itemCrandParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.item_level
     *
     */
    private Integer itemLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.transaction_level
     *
     */
    private Integer transactionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.pack_type
     *
     */
    private String packType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.simple_pack_kind
     *
     */
    private String simplePackKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.contains_inner_kind
     *
     */
    private String containsInnerKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.sellable_type
     *
     */
    private String sellableType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.orderable_type
     *
     */
    private String orderableType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.pack_status
     *
     */
    private String packStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.receive_unit
     *
     */
    private String receiveUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.asort_code
     *
     */
    private String asortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.cost_price_sequence
     *
     */
    private Integer costPriceSequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.initial_selling_price
     *
     */
    private BigDecimal initialSellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.retail_zone_group_id
     *
     */
    private Integer retailZoneGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.intern_item_name
     *
     */
    private String internItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.pos_item_name
     *
     */
    private String posItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.second_pos_item_name
     *
     */
    private String secondPosItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.external_item_name_1
     *
     */
    private String externalItemName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.external_item_name_2
     *
     */
    private String externalItemName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.external_item_name_3
     *
     */
    private String externalItemName3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.external_item_name_4
     *
     */
    private String externalItemName4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.second_item_name
     *
     */
    private String secondItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.picking_shipment_type
     *
     */
    private String pickingShipmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.regular_item_type
     *
     */
    private String regularItemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.color_size_management_type
     *
     */
    private String colorSizeManagementType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.b_item_return_possible_type
     *
     */
    private String bItemReturnPossibleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.status
     *
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.delivery_type_code
     *
     */
    private String deliveryTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.stock_buying_cost
     *
     */
    private BigDecimal stockBuyingCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_item.uda_value
     *
     */
    private Integer udaValue;
}
