package com.fastretailing.dcp.sales.common.entity.work;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class NonItemWork extends NonItemWorkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.apply_end_date
     *
     */
    private OffsetDateTime applyEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.non_item_type
     *
     */
    private String nonItemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.pos_item_name
     *
     */
    private String posItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.unit_retail
     *
     */
    private BigDecimal unitRetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.g_dept_code
     *
     */
    private String gDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.major_category_code
     *
     */
    private Integer majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.tax_rate
     *
     */
    private String taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.tax_type
     *
     */
    private String taxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.tax_kind
     *
     */
    private String taxKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.discount_flag
     *
     */
    private boolean discountFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_non_item.update_program_id
     *
     */
    private String updateProgramId;
}
