package com.fastretailing.dcp.sales.common.entity.work;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SkulistParentWork extends SkulistParentWorkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.eai_update_type
     *
     */
    private String eaiUpdateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.eai_send_status
     *
     */
    private String eaiSendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.eai_send_date
     *
     */
    private String eaiSendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.item_list_name
     *
     */
    private String itemListName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.create_date
     *
     */
    private OffsetDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.static_ind
     *
     */
    private String staticInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.last_rebuild_date
     *
     */
    private OffsetDateTime lastRebuildDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.user_security_ind
     *
     */
    private String userSecurityInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.tax_prod_goup_ind
     *
     */
    private String taxProdGoupInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.comment_desc
     *
     */
    private String commentDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.parent_skulist_code
     *
     */
    private Integer parentSkulistCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.color_code
     *
     */
    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.size_code
     *
     */
    private String sizeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.pattern_length_code
     *
     */
    private String patternLengthCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.major_category_code
     *
     */
    private Integer majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.class_code
     *
     */
    private Integer classCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.middle_category_code
     *
     */
    private Integer middleCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.initial_selling_price
     *
     */
    private BigDecimal initialSellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.regular_item_type
     *
     */
    private String regularItemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.core_attribute_type
     *
     */
    private String coreAttributeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.out_of_stock_judge_quantity
     *
     */
    private Integer outOfStockJudgeQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.line_up_type_code
     *
     */
    private String lineUpTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.input_aggregation_type
     *
     */
    private String inputAggregationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.skulist_status
     *
     */
    private String skulistStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.view_item_code
     *
     */
    private String viewItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.item_list_hierarchy_code
     *
     */
    private String itemListHierarchyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.year_code
     *
     */
    private String yearCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.view_year_type
     *
     */
    private String viewYearType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.season_code
     *
     */
    private String seasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.detail_season_code
     *
     */
    private String detailSeasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.skulist_pattern_code
     *
     */
    private String skulistPatternCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.set_object_auto_update_type
     *
     */
    private String setObjectAutoUpdateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.batch_region
     *
     */
    private Integer batchRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_parent.uda_value
     *
     */
    private Integer udaValue;
}
