package com.fastretailing.dcp.sales.common.entity.work;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

public class SkulistChildWorkCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_skulist_child
     *
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_skulist_child
     *
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_skulist_child
     *
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public SkulistChildWorkCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_skulist_child
     *
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLotNumberIsNull() {
            addCriterion("lot_number is null");
            return (Criteria) this;
        }

        public Criteria andLotNumberIsNotNull() {
            addCriterion("lot_number is not null");
            return (Criteria) this;
        }

        public Criteria andLotNumberEqualTo(String value) {
            addCriterion("lot_number =", value, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberNotEqualTo(String value) {
            addCriterion("lot_number <>", value, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberGreaterThan(String value) {
            addCriterion("lot_number >", value, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberGreaterThanOrEqualTo(String value) {
            addCriterion("lot_number >=", value, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberLessThan(String value) {
            addCriterion("lot_number <", value, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberLessThanOrEqualTo(String value) {
            addCriterion("lot_number <=", value, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberLike(String value) {
            addCriterion("lot_number like", value, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberNotLike(String value) {
            addCriterion("lot_number not like", value, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberIn(List<String> values) {
            addCriterion("lot_number in", values, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberNotIn(List<String> values) {
            addCriterion("lot_number not in", values, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberBetween(String value1, String value2) {
            addCriterion("lot_number between", value1, value2, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andLotNumberNotBetween(String value1, String value2) {
            addCriterion("lot_number not between", value1, value2, "lotNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIsNull() {
            addCriterion("business_code is null");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIsNotNull() {
            addCriterion("business_code is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeEqualTo(Long value) {
            addCriterion("business_code =", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotEqualTo(Long value) {
            addCriterion("business_code <>", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeGreaterThan(Long value) {
            addCriterion("business_code >", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("business_code >=", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLessThan(Long value) {
            addCriterion("business_code <", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLessThanOrEqualTo(Long value) {
            addCriterion("business_code <=", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIn(List<Long> values) {
            addCriterion("business_code in", values, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotIn(List<Long> values) {
            addCriterion("business_code not in", values, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeBetween(Long value1, Long value2) {
            addCriterion("business_code between", value1, value2, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotBetween(Long value1, Long value2) {
            addCriterion("business_code not between", value1, value2, "businessCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIsNull() {
            addCriterion("country_code is null");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIsNotNull() {
            addCriterion("country_code is not null");
            return (Criteria) this;
        }

        public Criteria andCountryCodeEqualTo(String value) {
            addCriterion("country_code =", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotEqualTo(String value) {
            addCriterion("country_code <>", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeGreaterThan(String value) {
            addCriterion("country_code >", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("country_code >=", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLessThan(String value) {
            addCriterion("country_code <", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLessThanOrEqualTo(String value) {
            addCriterion("country_code <=", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLike(String value) {
            addCriterion("country_code like", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotLike(String value) {
            addCriterion("country_code not like", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIn(List<String> values) {
            addCriterion("country_code in", values, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotIn(List<String> values) {
            addCriterion("country_code not in", values, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeBetween(String value1, String value2) {
            addCriterion("country_code between", value1, value2, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotBetween(String value1, String value2) {
            addCriterion("country_code not between", value1, value2, "countryCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeIsNull() {
            addCriterion("skulist_code is null");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeIsNotNull() {
            addCriterion("skulist_code is not null");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeEqualTo(Integer value) {
            addCriterion("skulist_code =", value, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeNotEqualTo(Integer value) {
            addCriterion("skulist_code <>", value, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeGreaterThan(Integer value) {
            addCriterion("skulist_code >", value, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("skulist_code >=", value, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeLessThan(Integer value) {
            addCriterion("skulist_code <", value, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeLessThanOrEqualTo(Integer value) {
            addCriterion("skulist_code <=", value, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeIn(List<Integer> values) {
            addCriterion("skulist_code in", values, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeNotIn(List<Integer> values) {
            addCriterion("skulist_code not in", values, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeBetween(Integer value1, Integer value2) {
            addCriterion("skulist_code between", value1, value2, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andSkulistCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("skulist_code not between", value1, value2, "skulistCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeIsNull() {
            addCriterion("item_code is null");
            return (Criteria) this;
        }

        public Criteria andItemCodeIsNotNull() {
            addCriterion("item_code is not null");
            return (Criteria) this;
        }

        public Criteria andItemCodeEqualTo(String value) {
            addCriterion("item_code =", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotEqualTo(String value) {
            addCriterion("item_code <>", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeGreaterThan(String value) {
            addCriterion("item_code >", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("item_code >=", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLessThan(String value) {
            addCriterion("item_code <", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLessThanOrEqualTo(String value) {
            addCriterion("item_code <=", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLike(String value) {
            addCriterion("item_code like", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotLike(String value) {
            addCriterion("item_code not like", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeIn(List<String> values) {
            addCriterion("item_code in", values, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotIn(List<String> values) {
            addCriterion("item_code not in", values, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeBetween(String value1, String value2) {
            addCriterion("item_code between", value1, value2, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotBetween(String value1, String value2) {
            addCriterion("item_code not between", value1, value2, "itemCode");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateIsNull() {
            addCriterion("eai_update_date is null");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateIsNotNull() {
            addCriterion("eai_update_date is not null");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateEqualTo(String value) {
            addCriterion("eai_update_date =", value, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateNotEqualTo(String value) {
            addCriterion("eai_update_date <>", value, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateGreaterThan(String value) {
            addCriterion("eai_update_date >", value, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("eai_update_date >=", value, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateLessThan(String value) {
            addCriterion("eai_update_date <", value, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("eai_update_date <=", value, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateLike(String value) {
            addCriterion("eai_update_date like", value, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateNotLike(String value) {
            addCriterion("eai_update_date not like", value, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateIn(List<String> values) {
            addCriterion("eai_update_date in", values, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateNotIn(List<String> values) {
            addCriterion("eai_update_date not in", values, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateBetween(String value1, String value2) {
            addCriterion("eai_update_date between", value1, value2, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateDateNotBetween(String value1, String value2) {
            addCriterion("eai_update_date not between", value1, value2, "eaiUpdateDate");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeIsNull() {
            addCriterion("eai_update_type is null");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeIsNotNull() {
            addCriterion("eai_update_type is not null");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeEqualTo(String value) {
            addCriterion("eai_update_type =", value, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeNotEqualTo(String value) {
            addCriterion("eai_update_type <>", value, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeGreaterThan(String value) {
            addCriterion("eai_update_type >", value, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("eai_update_type >=", value, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeLessThan(String value) {
            addCriterion("eai_update_type <", value, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeLessThanOrEqualTo(String value) {
            addCriterion("eai_update_type <=", value, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeLike(String value) {
            addCriterion("eai_update_type like", value, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeNotLike(String value) {
            addCriterion("eai_update_type not like", value, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeIn(List<String> values) {
            addCriterion("eai_update_type in", values, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeNotIn(List<String> values) {
            addCriterion("eai_update_type not in", values, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeBetween(String value1, String value2) {
            addCriterion("eai_update_type between", value1, value2, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiUpdateTypeNotBetween(String value1, String value2) {
            addCriterion("eai_update_type not between", value1, value2, "eaiUpdateType");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusIsNull() {
            addCriterion("eai_send_status is null");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusIsNotNull() {
            addCriterion("eai_send_status is not null");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusEqualTo(String value) {
            addCriterion("eai_send_status =", value, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusNotEqualTo(String value) {
            addCriterion("eai_send_status <>", value, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusGreaterThan(String value) {
            addCriterion("eai_send_status >", value, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusGreaterThanOrEqualTo(String value) {
            addCriterion("eai_send_status >=", value, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusLessThan(String value) {
            addCriterion("eai_send_status <", value, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusLessThanOrEqualTo(String value) {
            addCriterion("eai_send_status <=", value, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusLike(String value) {
            addCriterion("eai_send_status like", value, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusNotLike(String value) {
            addCriterion("eai_send_status not like", value, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusIn(List<String> values) {
            addCriterion("eai_send_status in", values, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusNotIn(List<String> values) {
            addCriterion("eai_send_status not in", values, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusBetween(String value1, String value2) {
            addCriterion("eai_send_status between", value1, value2, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendStatusNotBetween(String value1, String value2) {
            addCriterion("eai_send_status not between", value1, value2, "eaiSendStatus");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateIsNull() {
            addCriterion("eai_send_date is null");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateIsNotNull() {
            addCriterion("eai_send_date is not null");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateEqualTo(String value) {
            addCriterion("eai_send_date =", value, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateNotEqualTo(String value) {
            addCriterion("eai_send_date <>", value, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateGreaterThan(String value) {
            addCriterion("eai_send_date >", value, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateGreaterThanOrEqualTo(String value) {
            addCriterion("eai_send_date >=", value, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateLessThan(String value) {
            addCriterion("eai_send_date <", value, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateLessThanOrEqualTo(String value) {
            addCriterion("eai_send_date <=", value, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateLike(String value) {
            addCriterion("eai_send_date like", value, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateNotLike(String value) {
            addCriterion("eai_send_date not like", value, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateIn(List<String> values) {
            addCriterion("eai_send_date in", values, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateNotIn(List<String> values) {
            addCriterion("eai_send_date not in", values, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateBetween(String value1, String value2) {
            addCriterion("eai_send_date between", value1, value2, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andEaiSendDateNotBetween(String value1, String value2) {
            addCriterion("eai_send_date not between", value1, value2, "eaiSendDate");
            return (Criteria) this;
        }

        public Criteria andItemLevelIsNull() {
            addCriterion("item_level is null");
            return (Criteria) this;
        }

        public Criteria andItemLevelIsNotNull() {
            addCriterion("item_level is not null");
            return (Criteria) this;
        }

        public Criteria andItemLevelEqualTo(Integer value) {
            addCriterion("item_level =", value, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelNotEqualTo(Integer value) {
            addCriterion("item_level <>", value, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelGreaterThan(Integer value) {
            addCriterion("item_level >", value, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_level >=", value, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelLessThan(Integer value) {
            addCriterion("item_level <", value, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelLessThanOrEqualTo(Integer value) {
            addCriterion("item_level <=", value, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelIn(List<Integer> values) {
            addCriterion("item_level in", values, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelNotIn(List<Integer> values) {
            addCriterion("item_level not in", values, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelBetween(Integer value1, Integer value2) {
            addCriterion("item_level between", value1, value2, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andItemLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("item_level not between", value1, value2, "itemLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelIsNull() {
            addCriterion("inventory_management_level is null");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelIsNotNull() {
            addCriterion("inventory_management_level is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelEqualTo(Integer value) {
            addCriterion("inventory_management_level =", value, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelNotEqualTo(Integer value) {
            addCriterion("inventory_management_level <>", value, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelGreaterThan(Integer value) {
            addCriterion("inventory_management_level >", value, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("inventory_management_level >=", value, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelLessThan(Integer value) {
            addCriterion("inventory_management_level <", value, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelLessThanOrEqualTo(Integer value) {
            addCriterion("inventory_management_level <=", value, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelIn(List<Integer> values) {
            addCriterion("inventory_management_level in", values, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelNotIn(List<Integer> values) {
            addCriterion("inventory_management_level not in", values, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelBetween(Integer value1, Integer value2) {
            addCriterion("inventory_management_level between", value1, value2, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andInventoryManagementLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("inventory_management_level not between", value1, value2, "inventoryManagementLevel");
            return (Criteria) this;
        }

        public Criteria andPackIndIsNull() {
            addCriterion("pack_ind is null");
            return (Criteria) this;
        }

        public Criteria andPackIndIsNotNull() {
            addCriterion("pack_ind is not null");
            return (Criteria) this;
        }

        public Criteria andPackIndEqualTo(String value) {
            addCriterion("pack_ind =", value, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndNotEqualTo(String value) {
            addCriterion("pack_ind <>", value, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndGreaterThan(String value) {
            addCriterion("pack_ind >", value, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndGreaterThanOrEqualTo(String value) {
            addCriterion("pack_ind >=", value, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndLessThan(String value) {
            addCriterion("pack_ind <", value, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndLessThanOrEqualTo(String value) {
            addCriterion("pack_ind <=", value, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndLike(String value) {
            addCriterion("pack_ind like", value, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndNotLike(String value) {
            addCriterion("pack_ind not like", value, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndIn(List<String> values) {
            addCriterion("pack_ind in", values, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndNotIn(List<String> values) {
            addCriterion("pack_ind not in", values, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndBetween(String value1, String value2) {
            addCriterion("pack_ind between", value1, value2, "packInd");
            return (Criteria) this;
        }

        public Criteria andPackIndNotBetween(String value1, String value2) {
            addCriterion("pack_ind not between", value1, value2, "packInd");
            return (Criteria) this;
        }

        public Criteria andInsertIdIsNull() {
            addCriterion("insert_id is null");
            return (Criteria) this;
        }

        public Criteria andInsertIdIsNotNull() {
            addCriterion("insert_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsertIdEqualTo(String value) {
            addCriterion("insert_id =", value, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdNotEqualTo(String value) {
            addCriterion("insert_id <>", value, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdGreaterThan(String value) {
            addCriterion("insert_id >", value, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdGreaterThanOrEqualTo(String value) {
            addCriterion("insert_id >=", value, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdLessThan(String value) {
            addCriterion("insert_id <", value, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdLessThanOrEqualTo(String value) {
            addCriterion("insert_id <=", value, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdLike(String value) {
            addCriterion("insert_id like", value, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdNotLike(String value) {
            addCriterion("insert_id not like", value, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdIn(List<String> values) {
            addCriterion("insert_id in", values, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdNotIn(List<String> values) {
            addCriterion("insert_id not in", values, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdBetween(String value1, String value2) {
            addCriterion("insert_id between", value1, value2, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertIdNotBetween(String value1, String value2) {
            addCriterion("insert_id not between", value1, value2, "insertId");
            return (Criteria) this;
        }

        public Criteria andInsertDateIsNull() {
            addCriterion("insert_date is null");
            return (Criteria) this;
        }

        public Criteria andInsertDateIsNotNull() {
            addCriterion("insert_date is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDateEqualTo(OffsetDateTime value) {
            addCriterion("insert_date =", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotEqualTo(OffsetDateTime value) {
            addCriterion("insert_date <>", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateGreaterThan(OffsetDateTime value) {
            addCriterion("insert_date >", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("insert_date >=", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateLessThan(OffsetDateTime value) {
            addCriterion("insert_date <", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("insert_date <=", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateIn(List<OffsetDateTime> values) {
            addCriterion("insert_date in", values, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotIn(List<OffsetDateTime> values) {
            addCriterion("insert_date not in", values, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("insert_date between", value1, value2, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("insert_date not between", value1, value2, "insertDate");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeIsNull() {
            addCriterion("last_update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeIsNotNull() {
            addCriterion("last_update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("last_update_datetime =", value, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("last_update_datetime <>", value, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("last_update_datetime >", value, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("last_update_datetime >=", value, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("last_update_datetime <", value, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("last_update_datetime <=", value, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("last_update_datetime in", values, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("last_update_datetime not in", values, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("last_update_datetime between", value1, value2, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("last_update_datetime not between", value1, value2, "lastUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdIsNull() {
            addCriterion("last_update_id is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdIsNotNull() {
            addCriterion("last_update_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdEqualTo(String value) {
            addCriterion("last_update_id =", value, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdNotEqualTo(String value) {
            addCriterion("last_update_id <>", value, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdGreaterThan(String value) {
            addCriterion("last_update_id >", value, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("last_update_id >=", value, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdLessThan(String value) {
            addCriterion("last_update_id <", value, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("last_update_id <=", value, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdLike(String value) {
            addCriterion("last_update_id like", value, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdNotLike(String value) {
            addCriterion("last_update_id not like", value, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdIn(List<String> values) {
            addCriterion("last_update_id in", values, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdNotIn(List<String> values) {
            addCriterion("last_update_id not in", values, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdBetween(String value1, String value2) {
            addCriterion("last_update_id between", value1, value2, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIdNotBetween(String value1, String value2) {
            addCriterion("last_update_id not between", value1, value2, "lastUpdateId");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeIsNull() {
            addCriterion("main_item_type is null");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeIsNotNull() {
            addCriterion("main_item_type is not null");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeEqualTo(String value) {
            addCriterion("main_item_type =", value, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeNotEqualTo(String value) {
            addCriterion("main_item_type <>", value, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeGreaterThan(String value) {
            addCriterion("main_item_type >", value, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("main_item_type >=", value, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeLessThan(String value) {
            addCriterion("main_item_type <", value, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeLessThanOrEqualTo(String value) {
            addCriterion("main_item_type <=", value, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeLike(String value) {
            addCriterion("main_item_type like", value, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeNotLike(String value) {
            addCriterion("main_item_type not like", value, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeIn(List<String> values) {
            addCriterion("main_item_type in", values, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeNotIn(List<String> values) {
            addCriterion("main_item_type not in", values, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeBetween(String value1, String value2) {
            addCriterion("main_item_type between", value1, value2, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andMainItemTypeNotBetween(String value1, String value2) {
            addCriterion("main_item_type not between", value1, value2, "mainItemType");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeIsNull() {
            addCriterion("inner_pack_size is null");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeIsNotNull() {
            addCriterion("inner_pack_size is not null");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeEqualTo(BigDecimal value) {
            addCriterion("inner_pack_size =", value, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeNotEqualTo(BigDecimal value) {
            addCriterion("inner_pack_size <>", value, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeGreaterThan(BigDecimal value) {
            addCriterion("inner_pack_size >", value, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("inner_pack_size >=", value, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeLessThan(BigDecimal value) {
            addCriterion("inner_pack_size <", value, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("inner_pack_size <=", value, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeIn(List<BigDecimal> values) {
            addCriterion("inner_pack_size in", values, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeNotIn(List<BigDecimal> values) {
            addCriterion("inner_pack_size not in", values, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inner_pack_size between", value1, value2, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andInnerPackSizeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inner_pack_size not between", value1, value2, "innerPackSize");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeIsNull() {
            addCriterion("logical_delete_type is null");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeIsNotNull() {
            addCriterion("logical_delete_type is not null");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeEqualTo(String value) {
            addCriterion("logical_delete_type =", value, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeNotEqualTo(String value) {
            addCriterion("logical_delete_type <>", value, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeGreaterThan(String value) {
            addCriterion("logical_delete_type >", value, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeGreaterThanOrEqualTo(String value) {
            addCriterion("logical_delete_type >=", value, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeLessThan(String value) {
            addCriterion("logical_delete_type <", value, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeLessThanOrEqualTo(String value) {
            addCriterion("logical_delete_type <=", value, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeLike(String value) {
            addCriterion("logical_delete_type like", value, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeNotLike(String value) {
            addCriterion("logical_delete_type not like", value, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeIn(List<String> values) {
            addCriterion("logical_delete_type in", values, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeNotIn(List<String> values) {
            addCriterion("logical_delete_type not in", values, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeBetween(String value1, String value2) {
            addCriterion("logical_delete_type between", value1, value2, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andLogicalDeleteTypeNotBetween(String value1, String value2) {
            addCriterion("logical_delete_type not between", value1, value2, "logicalDeleteType");
            return (Criteria) this;
        }

        public Criteria andBatchRegionIsNull() {
            addCriterion("batch_region is null");
            return (Criteria) this;
        }

        public Criteria andBatchRegionIsNotNull() {
            addCriterion("batch_region is not null");
            return (Criteria) this;
        }

        public Criteria andBatchRegionEqualTo(Integer value) {
            addCriterion("batch_region =", value, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionNotEqualTo(Integer value) {
            addCriterion("batch_region <>", value, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionGreaterThan(Integer value) {
            addCriterion("batch_region >", value, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionGreaterThanOrEqualTo(Integer value) {
            addCriterion("batch_region >=", value, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionLessThan(Integer value) {
            addCriterion("batch_region <", value, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionLessThanOrEqualTo(Integer value) {
            addCriterion("batch_region <=", value, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionIn(List<Integer> values) {
            addCriterion("batch_region in", values, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionNotIn(List<Integer> values) {
            addCriterion("batch_region not in", values, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionBetween(Integer value1, Integer value2) {
            addCriterion("batch_region between", value1, value2, "batchRegion");
            return (Criteria) this;
        }

        public Criteria andBatchRegionNotBetween(Integer value1, Integer value2) {
            addCriterion("batch_region not between", value1, value2, "batchRegion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_skulist_child
     *
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_skulist_child
     *
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
