package com.fastretailing.dcp.sales.common.entity.work;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SkulistChildWork extends SkulistChildWorkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.eai_update_type
     *
     */
    private String eaiUpdateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.eai_send_status
     *
     */
    private String eaiSendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.eai_send_date
     *
     */
    private String eaiSendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.item_level
     *
     */
    private Integer itemLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.inventory_management_level
     *
     */
    private Integer inventoryManagementLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.pack_ind
     *
     */
    private String packInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.insert_id
     *
     */
    private String insertId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.insert_date
     *
     */
    private OffsetDateTime insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.last_update_datetime
     *
     */
    private OffsetDateTime lastUpdateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.last_update_id
     *
     */
    private String lastUpdateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.main_item_type
     *
     */
    private String mainItemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.inner_pack_size
     *
     */
    private BigDecimal innerPackSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.logical_delete_type
     *
     */
    private String logicalDeleteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_skulist_child.batch_region
     *
     */
    private Integer batchRegion;
}
