package com.fastretailing.dcp.sales.common.entity.work;

import lombok.Data;

@Data
public class StoreWorkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.lot_number
     *
     */
    private String lotNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_code
     *
     */
    private Long storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.eai_update_date
     *
     */
    private String eaiUpdateDate;
}
