package com.fastretailing.dcp.sales.common.entity.work;

import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class StoreWork extends StoreWorkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.eai_update_type
     *
     */
    private String eaiUpdateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.eai_send_status
     *
     */
    private String eaiSendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.eai_send_date
     *
     */
    private String eaiSendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_name
     *
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_name_kana
     *
     */
    private String storeNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.address1
     *
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.address2
     *
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_city
     *
     */
    private String storeCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.county
     *
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.state_code
     *
     */
    private String stateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.country_code
     *
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.postal_code
     *
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.fax_number
     *
     */
    private String faxNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.phone_number
     *
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_type
     *
     */
    private String storeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_open_date
     *
     */
    private OffsetDateTime storeOpenDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_close_date
     *
     */
    private OffsetDateTime storeCloseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.renewal_open_date
     *
     */
    private OffsetDateTime renewalOpenDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.vat_region_code
     *
     */
    private Integer vatRegionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.channel_id
     *
     */
    private Integer channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.area_code
     *
     */
    private Integer areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.order_start_days
     *
     */
    private Integer orderStartDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.order_end_days
     *
     */
    private Integer orderEndDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.currency_code
     *
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.language_code
     *
     */
    private Integer languageCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.shipment_logistics_district_code
     *
     */
    private String shipmentLogisticsDistrictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_scale_pattern_code
     *
     */
    private String storeScalePatternCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.existing_store_type_code
     *
     */
    private String existingStoreTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.inventory_object_type_code
     *
     */
    private String inventoryObjectTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.register_catinterlock_typecode
     *
     */
    private String registerCatinterlockTypecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.ss_store_manager_store_type_code
     *
     */
    private String ssStoreManagerStoreTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.renewal_previous_close_date
     *
     */
    private OffsetDateTime renewalPreviousCloseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.open_term_number
     *
     */
    private Integer openTermNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_inspection_start_date
     *
     */
    private OffsetDateTime storeInspectionStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.store_inspection_end_date
     *
     */
    private OffsetDateTime storeInspectionEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.close_type_code
     *
     */
    private String closeTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.direct_management_fc_store_type_code
     *
     */
    private String directManagementFcStoreTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.consignment_store_type_code
     *
     */
    private String consignmentStoreTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.system_machine_removal_date
     *
     */
    private OffsetDateTime systemMachineRemovalDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.sale_channel_type_code
     *
     */
    private String saleChannelTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.tsf_out_control_exclusion_type
     *
     */
    private String tsfOutControlExclusionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.batch_region
     *
     */
    private Integer batchRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_store.business_code
     *
     */
    private Long businessCode;
}
