package com.fastretailing.dcp.sales.common.entity.work;

import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TenderWork extends TenderWorkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.eai_update_type
     *
     */
    private String eaiUpdateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.eai_send_status
     *
     */
    private String eaiSendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.eai_send_datetime
     *
     */
    private String eaiSendDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.tender_name
     *
     */
    private String tenderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.receipt_tender_name
     *
     */
    private String receiptTenderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.tender_group
     *
     */
    private String tenderGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.valid_date
     *
     */
    private OffsetDateTime validDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.currency_code
     *
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.kid
     *
     */
    private String kid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.change_flag
     *
     */
    private String changeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.current_deposit_flag
     *
     */
    private String currentDepositFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.credit_company_code
     *
     */
    private String creditCompanyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.batch_region
     *
     */
    private Integer batchRegion;
}
