package com.fastretailing.dcp.sales.common.entity.work;

import lombok.Data;

@Data
public class TenderWorkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.lot_number
     *
     */
    private String lotNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.store_code
     *
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.tender_id
     *
     */
    private Integer tenderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tender.eai_update_datetime
     *
     */
    private String eaiUpdateDatetime;
}
