package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.AlterationExclusionControl;
import com.fastretailing.dcp.sales.common.entity.AlterationExclusionControlCondition;
import com.fastretailing.dcp.sales.common.entity.AlterationExclusionControlKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationExclusionControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    long countByCondition(AlterationExclusionControlCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int deleteByCondition(AlterationExclusionControlCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int deleteByPrimaryKey(AlterationExclusionControlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int insert(AlterationExclusionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int insertSelective(AlterationExclusionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    List<AlterationExclusionControl> selectByCondition(AlterationExclusionControlCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    AlterationExclusionControl selectByPrimaryKey(AlterationExclusionControlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int updateByConditionSelective(@Param("record") AlterationExclusionControl record, @Param("example") AlterationExclusionControlCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int updateByCondition(@Param("record") AlterationExclusionControl record, @Param("example") AlterationExclusionControlCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int updateByPrimaryKeySelective(AlterationExclusionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int updateByPrimaryKey(AlterationExclusionControl record);
}
