package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.ColorSizeMaster;
import com.fastretailing.dcp.sales.common.entity.ColorSizeMasterCondition;
import com.fastretailing.dcp.sales.common.entity.ColorSizeMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ColorSizeMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    long countByCondition(ColorSizeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    int deleteByCondition(ColorSizeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    int deleteByPrimaryKey(ColorSizeMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    int insert(ColorSizeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    int insertSelective(ColorSizeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    List<ColorSizeMaster> selectByCondition(ColorSizeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    ColorSizeMaster selectByPrimaryKey(ColorSizeMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    int updateByConditionSelective(@Param("record") ColorSizeMaster record, @Param("example") ColorSizeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    int updateByCondition(@Param("record") ColorSizeMaster record, @Param("example") ColorSizeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    int updateByPrimaryKeySelective(ColorSizeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_color_size
     *
     */
    int updateByPrimaryKey(ColorSizeMaster record);
}
