package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.CommonCodeMaster;
import com.fastretailing.dcp.sales.common.entity.CommonCodeMasterCondition;
import com.fastretailing.dcp.sales.common.entity.CommonCodeMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CommonCodeMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    long countByCondition(CommonCodeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    int deleteByCondition(CommonCodeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    int deleteByPrimaryKey(CommonCodeMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    int insert(CommonCodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    int insertSelective(CommonCodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    List<CommonCodeMaster> selectByCondition(CommonCodeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    CommonCodeMaster selectByPrimaryKey(CommonCodeMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    int updateByConditionSelective(@Param("record") CommonCodeMaster record, @Param("example") CommonCodeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    int updateByCondition(@Param("record") CommonCodeMaster record, @Param("example") CommonCodeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    int updateByPrimaryKeySelective(CommonCodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_common_code_master
     *
     */
    int updateByPrimaryKey(CommonCodeMaster record);
}
