package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.GClassMaster;
import com.fastretailing.dcp.sales.common.entity.GClassMasterCondition;
import com.fastretailing.dcp.sales.common.entity.GClassMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface GClassMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    long countByCondition(GClassMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    int deleteByCondition(GClassMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    int deleteByPrimaryKey(GClassMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    int insert(GClassMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    int insertSelective(GClassMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    List<GClassMaster> selectByCondition(GClassMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    GClassMaster selectByPrimaryKey(GClassMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    int updateByConditionSelective(@Param("record") GClassMaster record, @Param("example") GClassMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    int updateByCondition(@Param("record") GClassMaster record, @Param("example") GClassMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    int updateByPrimaryKeySelective(GClassMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class
     *
     */
    int updateByPrimaryKey(GClassMaster record);
}
