package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.GClassLinkMaster;
import com.fastretailing.dcp.sales.common.entity.GClassLinkMasterCondition;
import com.fastretailing.dcp.sales.common.entity.GClassLinkMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface GClassLinkMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    long countByCondition(GClassLinkMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    int deleteByCondition(GClassLinkMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    int deleteByPrimaryKey(GClassLinkMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    int insert(GClassLinkMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    int insertSelective(GClassLinkMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    List<GClassLinkMaster> selectByCondition(GClassLinkMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    GClassLinkMaster selectByPrimaryKey(GClassLinkMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    int updateByConditionSelective(@Param("record") GClassLinkMaster record, @Param("example") GClassLinkMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    int updateByCondition(@Param("record") GClassLinkMaster record, @Param("example") GClassLinkMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    int updateByPrimaryKeySelective(GClassLinkMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    int updateByPrimaryKey(GClassLinkMaster record);
}
