package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.ItemListHeaderMaster;
import com.fastretailing.dcp.sales.common.entity.ItemListHeaderMasterCondition;
import com.fastretailing.dcp.sales.common.entity.ItemListHeaderMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemListHeaderMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    long countByCondition(ItemListHeaderMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    int deleteByCondition(ItemListHeaderMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    int deleteByPrimaryKey(ItemListHeaderMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    int insert(ItemListHeaderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    int insertSelective(ItemListHeaderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    List<ItemListHeaderMaster> selectByCondition(ItemListHeaderMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    ItemListHeaderMaster selectByPrimaryKey(ItemListHeaderMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    int updateByConditionSelective(@Param("record") ItemListHeaderMaster record, @Param("example") ItemListHeaderMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    int updateByCondition(@Param("record") ItemListHeaderMaster record, @Param("example") ItemListHeaderMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    int updateByPrimaryKeySelective(ItemListHeaderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_head
     *
     */
    int updateByPrimaryKey(ItemListHeaderMaster record);
}
