package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.ItemLevel1Master;
import com.fastretailing.dcp.sales.common.entity.ItemLevel1MasterCondition;
import com.fastretailing.dcp.sales.common.entity.ItemLevel1MasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemLevel1MasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    long countByCondition(ItemLevel1MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    int deleteByCondition(ItemLevel1MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    int deleteByPrimaryKey(ItemLevel1MasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    int insert(ItemLevel1Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    int insertSelective(ItemLevel1Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    List<ItemLevel1Master> selectByCondition(ItemLevel1MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    ItemLevel1Master selectByPrimaryKey(ItemLevel1MasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    int updateByConditionSelective(@Param("record") ItemLevel1Master record, @Param("example") ItemLevel1MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    int updateByCondition(@Param("record") ItemLevel1Master record, @Param("example") ItemLevel1MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    int updateByPrimaryKeySelective(ItemLevel1Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_1
     *
     */
    int updateByPrimaryKey(ItemLevel1Master record);
}
