package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.ItemListDetailMaster;
import com.fastretailing.dcp.sales.common.entity.ItemListDetailMasterCondition;
import com.fastretailing.dcp.sales.common.entity.ItemListDetailMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemListDetailMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    long countByCondition(ItemListDetailMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    int deleteByCondition(ItemListDetailMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    int deleteByPrimaryKey(ItemListDetailMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    int insert(ItemListDetailMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    int insertSelective(ItemListDetailMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    List<ItemListDetailMaster> selectByCondition(ItemListDetailMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    ItemListDetailMaster selectByPrimaryKey(ItemListDetailMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    int updateByConditionSelective(@Param("record") ItemListDetailMaster record, @Param("example") ItemListDetailMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    int updateByCondition(@Param("record") ItemListDetailMaster record, @Param("example") ItemListDetailMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    int updateByPrimaryKeySelective(ItemListDetailMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_list_detail
     *
     */
    int updateByPrimaryKey(ItemListDetailMaster record);
}
