package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.ItemPackMaster;
import com.fastretailing.dcp.sales.common.entity.ItemPackMasterCondition;
import com.fastretailing.dcp.sales.common.entity.ItemPackMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemPackMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    long countByCondition(ItemPackMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    int deleteByCondition(ItemPackMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    int deleteByPrimaryKey(ItemPackMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    int insert(ItemPackMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    int insertSelective(ItemPackMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    List<ItemPackMaster> selectByCondition(ItemPackMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    ItemPackMaster selectByPrimaryKey(ItemPackMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    int updateByConditionSelective(@Param("record") ItemPackMaster record, @Param("example") ItemPackMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    int updateByCondition(@Param("record") ItemPackMaster record, @Param("example") ItemPackMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    int updateByPrimaryKeySelective(ItemPackMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_pack
     *
     */
    int updateByPrimaryKey(ItemPackMaster record);
}
