package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.ItemLevel2Master;
import com.fastretailing.dcp.sales.common.entity.ItemLevel2MasterCondition;
import com.fastretailing.dcp.sales.common.entity.ItemLevel2MasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemLevel2MasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    long countByCondition(ItemLevel2MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    int deleteByCondition(ItemLevel2MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    int deleteByPrimaryKey(ItemLevel2MasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    int insert(ItemLevel2Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    int insertSelective(ItemLevel2Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    List<ItemLevel2Master> selectByCondition(ItemLevel2MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    ItemLevel2Master selectByPrimaryKey(ItemLevel2MasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    int updateByConditionSelective(@Param("record") ItemLevel2Master record, @Param("example") ItemLevel2MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    int updateByCondition(@Param("record") ItemLevel2Master record, @Param("example") ItemLevel2MasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    int updateByPrimaryKeySelective(ItemLevel2Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item_level_2
     *
     */
    int updateByPrimaryKey(ItemLevel2Master record);
}
