package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.LotNumberManagement;
import com.fastretailing.dcp.sales.common.entity.LotNumberManagementCondition;
import com.fastretailing.dcp.sales.common.entity.LotNumberManagementKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LotNumberManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    long countByCondition(LotNumberManagementCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    int deleteByCondition(LotNumberManagementCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    int deleteByPrimaryKey(LotNumberManagementKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    int insert(LotNumberManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    int insertSelective(LotNumberManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    List<LotNumberManagement> selectByCondition(LotNumberManagementCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    LotNumberManagement selectByPrimaryKey(LotNumberManagementKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    int updateByConditionSelective(@Param("record") LotNumberManagement record, @Param("example") LotNumberManagementCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    int updateByCondition(@Param("record") LotNumberManagement record, @Param("example") LotNumberManagementCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    int updateByPrimaryKeySelective(LotNumberManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lot_number_mgm
     *
     */
    int updateByPrimaryKey(LotNumberManagement record);
}
