package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.NonItemIfMaster;
import com.fastretailing.dcp.sales.common.entity.NonItemIfMasterCondition;
import com.fastretailing.dcp.sales.common.entity.NonItemIfMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface NonItemIfMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    long countByCondition(NonItemIfMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    int deleteByCondition(NonItemIfMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    int deleteByPrimaryKey(NonItemIfMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    int insert(NonItemIfMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    int insertSelective(NonItemIfMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    List<NonItemIfMaster> selectByCondition(NonItemIfMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    NonItemIfMaster selectByPrimaryKey(NonItemIfMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    int updateByConditionSelective(@Param("record") NonItemIfMaster record, @Param("example") NonItemIfMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    int updateByCondition(@Param("record") NonItemIfMaster record, @Param("example") NonItemIfMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    int updateByPrimaryKeySelective(NonItemIfMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item_if
     *
     */
    int updateByPrimaryKey(NonItemIfMaster record);
}
