package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.NonItemMaster;
import com.fastretailing.dcp.sales.common.entity.NonItemMasterCondition;
import com.fastretailing.dcp.sales.common.entity.NonItemMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface NonItemMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    long countByCondition(NonItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    int deleteByCondition(NonItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    int deleteByPrimaryKey(NonItemMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    int insert(NonItemMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    int insertSelective(NonItemMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    List<NonItemMaster> selectByCondition(NonItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    NonItemMaster selectByPrimaryKey(NonItemMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    int updateByConditionSelective(@Param("record") NonItemMaster record, @Param("example") NonItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    int updateByCondition(@Param("record") NonItemMaster record, @Param("example") NonItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    int updateByPrimaryKeySelective(NonItemMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    int updateByPrimaryKey(NonItemMaster record);
}
