package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.PayOffSummaryMappingMaster;
import com.fastretailing.dcp.sales.common.entity.PayOffSummaryMappingMasterCondition;
import com.fastretailing.dcp.sales.common.entity.PayOffSummaryMappingMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PayOffSummaryMappingMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    long countByCondition(PayOffSummaryMappingMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    int deleteByCondition(PayOffSummaryMappingMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    int deleteByPrimaryKey(PayOffSummaryMappingMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    int insert(PayOffSummaryMappingMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    int insertSelective(PayOffSummaryMappingMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    List<PayOffSummaryMappingMaster> selectByCondition(PayOffSummaryMappingMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    PayOffSummaryMappingMaster selectByPrimaryKey(PayOffSummaryMappingMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    int updateByConditionSelective(@Param("record") PayOffSummaryMappingMaster record, @Param("example") PayOffSummaryMappingMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    int updateByCondition(@Param("record") PayOffSummaryMappingMaster record, @Param("example") PayOffSummaryMappingMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    int updateByPrimaryKeySelective(PayOffSummaryMappingMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_pay_off_summary_mapping
     *
     */
    int updateByPrimaryKey(PayOffSummaryMappingMaster record);
}
