package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.PurgeItemMaster;
import com.fastretailing.dcp.sales.common.entity.PurgeItemMasterCondition;
import com.fastretailing.dcp.sales.common.entity.PurgeItemMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PurgeItemMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    long countByCondition(PurgeItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    int deleteByCondition(PurgeItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    int deleteByPrimaryKey(PurgeItemMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    int insert(PurgeItemMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    int insertSelective(PurgeItemMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    List<PurgeItemMaster> selectByCondition(PurgeItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    PurgeItemMaster selectByPrimaryKey(PurgeItemMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    int updateByConditionSelective(@Param("record") PurgeItemMaster record, @Param("example") PurgeItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    int updateByCondition(@Param("record") PurgeItemMaster record, @Param("example") PurgeItemMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    int updateByPrimaryKeySelective(PurgeItemMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_purge_item
     *
     */
    int updateByPrimaryKey(PurgeItemMaster record);
}
