package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.StoreHourlySkuResult;
import com.fastretailing.dcp.sales.common.entity.StoreHourlySkuResultCondition;
import com.fastretailing.dcp.sales.common.entity.StoreHourlySkuResultKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StoreHourlySkuResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    long countByCondition(StoreHourlySkuResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    int deleteByCondition(StoreHourlySkuResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    int deleteByPrimaryKey(StoreHourlySkuResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    int insert(StoreHourlySkuResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    int insertSelective(StoreHourlySkuResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    List<StoreHourlySkuResult> selectByCondition(StoreHourlySkuResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    StoreHourlySkuResult selectByPrimaryKey(StoreHourlySkuResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    int updateByConditionSelective(@Param("record") StoreHourlySkuResult record, @Param("example") StoreHourlySkuResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    int updateByCondition(@Param("record") StoreHourlySkuResult record, @Param("example") StoreHourlySkuResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    int updateByPrimaryKeySelective(StoreHourlySkuResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_sku_result
     *
     */
    int updateByPrimaryKey(StoreHourlySkuResult record);
}
