package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.StoreGroupMapMaster;
import com.fastretailing.dcp.sales.common.entity.StoreGroupMapMasterCondition;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StoreGroupMapMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    long countByCondition(StoreGroupMapMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    int deleteByCondition(StoreGroupMapMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    int deleteByPrimaryKey(String storeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    int insert(StoreGroupMapMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    int insertSelective(StoreGroupMapMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    List<StoreGroupMapMaster> selectByCondition(StoreGroupMapMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    StoreGroupMapMaster selectByPrimaryKey(String storeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    int updateByConditionSelective(@Param("record") StoreGroupMapMaster record, @Param("example") StoreGroupMapMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    int updateByCondition(@Param("record") StoreGroupMapMaster record, @Param("example") StoreGroupMapMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    int updateByPrimaryKeySelective(StoreGroupMapMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_group_map
     *
     */
    int updateByPrimaryKey(StoreGroupMapMaster record);
}
