package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.StoreHourlyGatherResult;
import com.fastretailing.dcp.sales.common.entity.StoreHourlyGatherResultCondition;
import com.fastretailing.dcp.sales.common.entity.StoreHourlyGatherResultKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StoreHourlyGatherResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    long countByCondition(StoreHourlyGatherResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    int deleteByCondition(StoreHourlyGatherResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    int deleteByPrimaryKey(StoreHourlyGatherResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    int insert(StoreHourlyGatherResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    int insertSelective(StoreHourlyGatherResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    List<StoreHourlyGatherResult> selectByCondition(StoreHourlyGatherResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    StoreHourlyGatherResult selectByPrimaryKey(StoreHourlyGatherResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    int updateByConditionSelective(@Param("record") StoreHourlyGatherResult record, @Param("example") StoreHourlyGatherResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    int updateByCondition(@Param("record") StoreHourlyGatherResult record, @Param("example") StoreHourlyGatherResultCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    int updateByPrimaryKeySelective(StoreHourlyGatherResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_hourly_gather_result
     *
     */
    int updateByPrimaryKey(StoreHourlyGatherResult record);
}
