package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTenderInformation;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTenderInformationCondition;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTenderInformationKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionInquirySalesTransactionTenderInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    long countByCondition(TransactionInquirySalesTransactionTenderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    int deleteByCondition(TransactionInquirySalesTransactionTenderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    int deleteByPrimaryKey(TransactionInquirySalesTransactionTenderInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    int insert(TransactionInquirySalesTransactionTenderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    int insertSelective(TransactionInquirySalesTransactionTenderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    List<TransactionInquirySalesTransactionTenderInformation> selectByCondition(TransactionInquirySalesTransactionTenderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    TransactionInquirySalesTransactionTenderInformation selectByPrimaryKey(TransactionInquirySalesTransactionTenderInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    int updateByConditionSelective(@Param("record") TransactionInquirySalesTransactionTenderInformation record, @Param("example") TransactionInquirySalesTransactionTenderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    int updateByCondition(@Param("record") TransactionInquirySalesTransactionTenderInformation record, @Param("example") TransactionInquirySalesTransactionTenderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    int updateByPrimaryKeySelective(TransactionInquirySalesTransactionTenderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tender_info
     *
     */
    int updateByPrimaryKey(TransactionInquirySalesTransactionTenderInformation record);
}
