package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDetail;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDetailCondition;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionInquirySalesTransactionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    long countByCondition(TransactionInquirySalesTransactionDetailCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    int deleteByCondition(TransactionInquirySalesTransactionDetailCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    int deleteByPrimaryKey(TransactionInquirySalesTransactionDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    int insert(TransactionInquirySalesTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    int insertSelective(TransactionInquirySalesTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    List<TransactionInquirySalesTransactionDetail> selectByCondition(TransactionInquirySalesTransactionDetailCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    TransactionInquirySalesTransactionDetail selectByPrimaryKey(TransactionInquirySalesTransactionDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    int updateByConditionSelective(@Param("record") TransactionInquirySalesTransactionDetail record, @Param("example") TransactionInquirySalesTransactionDetailCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    int updateByCondition(@Param("record") TransactionInquirySalesTransactionDetail record, @Param("example") TransactionInquirySalesTransactionDetailCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    int updateByPrimaryKeySelective(TransactionInquirySalesTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail
     *
     */
    int updateByPrimaryKey(TransactionInquirySalesTransactionDetail record);
}
