package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.TransactionInquiryOrderInformation;
import com.fastretailing.dcp.sales.common.entity.TransactionInquiryOrderInformationCondition;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionInquiryOrderInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    long countByCondition(TransactionInquiryOrderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    int deleteByCondition(TransactionInquiryOrderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    int deleteByPrimaryKey(String integratedOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    int insert(TransactionInquiryOrderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    int insertSelective(TransactionInquiryOrderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    List<TransactionInquiryOrderInformation> selectByCondition(TransactionInquiryOrderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    TransactionInquiryOrderInformation selectByPrimaryKey(String integratedOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    int updateByConditionSelective(@Param("record") TransactionInquiryOrderInformation record, @Param("example") TransactionInquiryOrderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    int updateByCondition(@Param("record") TransactionInquiryOrderInformation record, @Param("example") TransactionInquiryOrderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    int updateByPrimaryKeySelective(TransactionInquiryOrderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_order_information
     *
     */
    int updateByPrimaryKey(TransactionInquiryOrderInformation record);
}
