package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTax;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTaxCondition;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTaxKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionInquirySalesTransactionTaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    long countByCondition(TransactionInquirySalesTransactionTaxCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    int deleteByCondition(TransactionInquirySalesTransactionTaxCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    int deleteByPrimaryKey(TransactionInquirySalesTransactionTaxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    int insert(TransactionInquirySalesTransactionTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    int insertSelective(TransactionInquirySalesTransactionTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    List<TransactionInquirySalesTransactionTax> selectByCondition(TransactionInquirySalesTransactionTaxCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    TransactionInquirySalesTransactionTax selectByPrimaryKey(TransactionInquirySalesTransactionTaxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    int updateByConditionSelective(@Param("record") TransactionInquirySalesTransactionTax record, @Param("example") TransactionInquirySalesTransactionTaxCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    int updateByCondition(@Param("record") TransactionInquirySalesTransactionTax record, @Param("example") TransactionInquirySalesTransactionTaxCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    int updateByPrimaryKeySelective(TransactionInquirySalesTransactionTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_tax
     *
     */
    int updateByPrimaryKey(TransactionInquirySalesTransactionTax record);
}
