package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTotalAmount;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTotalAmountCondition;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionTotalAmountKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionInquirySalesTransactionTotalAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    long countByCondition(TransactionInquirySalesTransactionTotalAmountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    int deleteByCondition(TransactionInquirySalesTransactionTotalAmountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    int deleteByPrimaryKey(TransactionInquirySalesTransactionTotalAmountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    int insert(TransactionInquirySalesTransactionTotalAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    int insertSelective(TransactionInquirySalesTransactionTotalAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    List<TransactionInquirySalesTransactionTotalAmount> selectByCondition(TransactionInquirySalesTransactionTotalAmountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    TransactionInquirySalesTransactionTotalAmount selectByPrimaryKey(TransactionInquirySalesTransactionTotalAmountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    int updateByConditionSelective(@Param("record") TransactionInquirySalesTransactionTotalAmount record, @Param("example") TransactionInquirySalesTransactionTotalAmountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    int updateByCondition(@Param("record") TransactionInquirySalesTransactionTotalAmount record, @Param("example") TransactionInquirySalesTransactionTotalAmountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    int updateByPrimaryKeySelective(TransactionInquirySalesTransactionTotalAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    int updateByPrimaryKey(TransactionInquirySalesTransactionTotalAmount record);
}
