package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionHeader;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionHeaderCondition;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionHeaderKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionInquirySalesTransactionHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    long countByCondition(TransactionInquirySalesTransactionHeaderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    int deleteByCondition(TransactionInquirySalesTransactionHeaderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    int deleteByPrimaryKey(TransactionInquirySalesTransactionHeaderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    int insert(TransactionInquirySalesTransactionHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    int insertSelective(TransactionInquirySalesTransactionHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    List<TransactionInquirySalesTransactionHeader> selectByCondition(TransactionInquirySalesTransactionHeaderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    TransactionInquirySalesTransactionHeader selectByPrimaryKey(TransactionInquirySalesTransactionHeaderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    int updateByConditionSelective(@Param("record") TransactionInquirySalesTransactionHeader record, @Param("example") TransactionInquirySalesTransactionHeaderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    int updateByCondition(@Param("record") TransactionInquirySalesTransactionHeader record, @Param("example") TransactionInquirySalesTransactionHeaderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    int updateByPrimaryKeySelective(TransactionInquirySalesTransactionHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_header
     *
     */
    int updateByPrimaryKey(TransactionInquirySalesTransactionHeader record);
}
