package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDiscount;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDiscountCondition;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDiscountKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionInquirySalesTransactionDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    long countByCondition(TransactionInquirySalesTransactionDiscountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    int deleteByCondition(TransactionInquirySalesTransactionDiscountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    int deleteByPrimaryKey(TransactionInquirySalesTransactionDiscountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    int insert(TransactionInquirySalesTransactionDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    int insertSelective(TransactionInquirySalesTransactionDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    List<TransactionInquirySalesTransactionDiscount> selectByCondition(TransactionInquirySalesTransactionDiscountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    TransactionInquirySalesTransactionDiscount selectByPrimaryKey(TransactionInquirySalesTransactionDiscountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    int updateByConditionSelective(@Param("record") TransactionInquirySalesTransactionDiscount record, @Param("example") TransactionInquirySalesTransactionDiscountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    int updateByCondition(@Param("record") TransactionInquirySalesTransactionDiscount record, @Param("example") TransactionInquirySalesTransactionDiscountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    int updateByPrimaryKeySelective(TransactionInquirySalesTransactionDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_discount
     *
     */
    int updateByPrimaryKey(TransactionInquirySalesTransactionDiscount record);
}
