package com.fastretailing.dcp.sales.common.repository;

import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDetailInformation;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDetailInformationCondition;
import com.fastretailing.dcp.sales.common.entity.TransactionInquirySalesTransactionDetailInformationKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionInquirySalesTransactionDetailInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    long countByCondition(TransactionInquirySalesTransactionDetailInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    int deleteByCondition(TransactionInquirySalesTransactionDetailInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    int deleteByPrimaryKey(TransactionInquirySalesTransactionDetailInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    int insert(TransactionInquirySalesTransactionDetailInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    int insertSelective(TransactionInquirySalesTransactionDetailInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    List<TransactionInquirySalesTransactionDetailInformation> selectByCondition(TransactionInquirySalesTransactionDetailInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    TransactionInquirySalesTransactionDetailInformation selectByPrimaryKey(TransactionInquirySalesTransactionDetailInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    int updateByConditionSelective(@Param("record") TransactionInquirySalesTransactionDetailInformation record, @Param("example") TransactionInquirySalesTransactionDetailInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    int updateByCondition(@Param("record") TransactionInquirySalesTransactionDetailInformation record, @Param("example") TransactionInquirySalesTransactionDetailInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    int updateByPrimaryKeySelective(TransactionInquirySalesTransactionDetailInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_detail_info
     *
     */
    int updateByPrimaryKey(TransactionInquirySalesTransactionDetailInformation record);
}
