package com.fastretailing.dcp.sales.common.entity;

import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CommonCodeMaster extends CommonCodeMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.display_order
     *
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.name_1
     *
     */
    private String name1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.name_2
     *
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.name_3
     *
     */
    private String name3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.name_4
     *
     */
    private String name4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.name_5
     *
     */
    private String name5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_common_code_master.update_program_id
     *
     */
    private String updateProgramId;
}
