package com.fastretailing.dcp.sales.common.entity;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

public class GClassLinkMasterCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_g_class_link
     *
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_g_class_link
     *
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_g_class_link
     *
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public GClassLinkMasterCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_g_class_link
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_g_class_link
     *
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSystemCountryCodeIsNull() {
            addCriterion("system_country_code is null");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeIsNotNull() {
            addCriterion("system_country_code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeEqualTo(String value) {
            addCriterion("system_country_code =", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeNotEqualTo(String value) {
            addCriterion("system_country_code <>", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeGreaterThan(String value) {
            addCriterion("system_country_code >", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_country_code >=", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeLessThan(String value) {
            addCriterion("system_country_code <", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeLessThanOrEqualTo(String value) {
            addCriterion("system_country_code <=", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeLike(String value) {
            addCriterion("system_country_code like", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeNotLike(String value) {
            addCriterion("system_country_code not like", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeIn(List<String> values) {
            addCriterion("system_country_code in", values, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeNotIn(List<String> values) {
            addCriterion("system_country_code not in", values, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeBetween(String value1, String value2) {
            addCriterion("system_country_code between", value1, value2, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeNotBetween(String value1, String value2) {
            addCriterion("system_country_code not between", value1, value2, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeIsNull() {
            addCriterion("system_brand_code is null");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeIsNotNull() {
            addCriterion("system_brand_code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeEqualTo(String value) {
            addCriterion("system_brand_code =", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeNotEqualTo(String value) {
            addCriterion("system_brand_code <>", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeGreaterThan(String value) {
            addCriterion("system_brand_code >", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_brand_code >=", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeLessThan(String value) {
            addCriterion("system_brand_code <", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeLessThanOrEqualTo(String value) {
            addCriterion("system_brand_code <=", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeLike(String value) {
            addCriterion("system_brand_code like", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeNotLike(String value) {
            addCriterion("system_brand_code not like", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeIn(List<String> values) {
            addCriterion("system_brand_code in", values, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeNotIn(List<String> values) {
            addCriterion("system_brand_code not in", values, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeBetween(String value1, String value2) {
            addCriterion("system_brand_code between", value1, value2, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeNotBetween(String value1, String value2) {
            addCriterion("system_brand_code not between", value1, value2, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeIsNull() {
            addCriterion("major_category_code is null");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeIsNotNull() {
            addCriterion("major_category_code is not null");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeEqualTo(String value) {
            addCriterion("major_category_code =", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeNotEqualTo(String value) {
            addCriterion("major_category_code <>", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeGreaterThan(String value) {
            addCriterion("major_category_code >", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("major_category_code >=", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeLessThan(String value) {
            addCriterion("major_category_code <", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeLessThanOrEqualTo(String value) {
            addCriterion("major_category_code <=", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeLike(String value) {
            addCriterion("major_category_code like", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeNotLike(String value) {
            addCriterion("major_category_code not like", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeIn(List<String> values) {
            addCriterion("major_category_code in", values, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeNotIn(List<String> values) {
            addCriterion("major_category_code not in", values, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeBetween(String value1, String value2) {
            addCriterion("major_category_code between", value1, value2, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeNotBetween(String value1, String value2) {
            addCriterion("major_category_code not between", value1, value2, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeIsNull() {
            addCriterion("class_code is null");
            return (Criteria) this;
        }

        public Criteria andClassCodeIsNotNull() {
            addCriterion("class_code is not null");
            return (Criteria) this;
        }

        public Criteria andClassCodeEqualTo(String value) {
            addCriterion("class_code =", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeNotEqualTo(String value) {
            addCriterion("class_code <>", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeGreaterThan(String value) {
            addCriterion("class_code >", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeGreaterThanOrEqualTo(String value) {
            addCriterion("class_code >=", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeLessThan(String value) {
            addCriterion("class_code <", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeLessThanOrEqualTo(String value) {
            addCriterion("class_code <=", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeLike(String value) {
            addCriterion("class_code like", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeNotLike(String value) {
            addCriterion("class_code not like", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeIn(List<String> values) {
            addCriterion("class_code in", values, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeNotIn(List<String> values) {
            addCriterion("class_code not in", values, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeBetween(String value1, String value2) {
            addCriterion("class_code between", value1, value2, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeNotBetween(String value1, String value2) {
            addCriterion("class_code not between", value1, value2, "classCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeIsNull() {
            addCriterion("middle_category_code is null");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeIsNotNull() {
            addCriterion("middle_category_code is not null");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeEqualTo(String value) {
            addCriterion("middle_category_code =", value, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeNotEqualTo(String value) {
            addCriterion("middle_category_code <>", value, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeGreaterThan(String value) {
            addCriterion("middle_category_code >", value, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("middle_category_code >=", value, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeLessThan(String value) {
            addCriterion("middle_category_code <", value, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeLessThanOrEqualTo(String value) {
            addCriterion("middle_category_code <=", value, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeLike(String value) {
            addCriterion("middle_category_code like", value, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeNotLike(String value) {
            addCriterion("middle_category_code not like", value, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeIn(List<String> values) {
            addCriterion("middle_category_code in", values, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeNotIn(List<String> values) {
            addCriterion("middle_category_code not in", values, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeBetween(String value1, String value2) {
            addCriterion("middle_category_code between", value1, value2, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryCodeNotBetween(String value1, String value2) {
            addCriterion("middle_category_code not between", value1, value2, "middleCategoryCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeIsNull() {
            addCriterion("system_business_code is null");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeIsNotNull() {
            addCriterion("system_business_code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeEqualTo(String value) {
            addCriterion("system_business_code =", value, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeNotEqualTo(String value) {
            addCriterion("system_business_code <>", value, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeGreaterThan(String value) {
            addCriterion("system_business_code >", value, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_business_code >=", value, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeLessThan(String value) {
            addCriterion("system_business_code <", value, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeLessThanOrEqualTo(String value) {
            addCriterion("system_business_code <=", value, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeLike(String value) {
            addCriterion("system_business_code like", value, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeNotLike(String value) {
            addCriterion("system_business_code not like", value, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeIn(List<String> values) {
            addCriterion("system_business_code in", values, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeNotIn(List<String> values) {
            addCriterion("system_business_code not in", values, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeBetween(String value1, String value2) {
            addCriterion("system_business_code between", value1, value2, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andSystemBusinessCodeNotBetween(String value1, String value2) {
            addCriterion("system_business_code not between", value1, value2, "systemBusinessCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeIsNull() {
            addCriterion("g_department_code is null");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeIsNotNull() {
            addCriterion("g_department_code is not null");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeEqualTo(String value) {
            addCriterion("g_department_code =", value, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeNotEqualTo(String value) {
            addCriterion("g_department_code <>", value, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeGreaterThan(String value) {
            addCriterion("g_department_code >", value, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("g_department_code >=", value, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeLessThan(String value) {
            addCriterion("g_department_code <", value, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeLessThanOrEqualTo(String value) {
            addCriterion("g_department_code <=", value, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeLike(String value) {
            addCriterion("g_department_code like", value, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeNotLike(String value) {
            addCriterion("g_department_code not like", value, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeIn(List<String> values) {
            addCriterion("g_department_code in", values, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeNotIn(List<String> values) {
            addCriterion("g_department_code not in", values, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeBetween(String value1, String value2) {
            addCriterion("g_department_code between", value1, value2, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andGDepartmentCodeNotBetween(String value1, String value2) {
            addCriterion("g_department_code not between", value1, value2, "gDepartmentCode");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIsNull() {
            addCriterion("create_program_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIsNotNull() {
            addCriterion("create_program_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdEqualTo(String value) {
            addCriterion("create_program_id =", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotEqualTo(String value) {
            addCriterion("create_program_id <>", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdGreaterThan(String value) {
            addCriterion("create_program_id >", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_program_id >=", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLessThan(String value) {
            addCriterion("create_program_id <", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLessThanOrEqualTo(String value) {
            addCriterion("create_program_id <=", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLike(String value) {
            addCriterion("create_program_id like", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotLike(String value) {
            addCriterion("create_program_id not like", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIn(List<String> values) {
            addCriterion("create_program_id in", values, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotIn(List<String> values) {
            addCriterion("create_program_id not in", values, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdBetween(String value1, String value2) {
            addCriterion("create_program_id between", value1, value2, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotBetween(String value1, String value2) {
            addCriterion("create_program_id not between", value1, value2, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIsNull() {
            addCriterion("update_program_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIsNotNull() {
            addCriterion("update_program_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdEqualTo(String value) {
            addCriterion("update_program_id =", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotEqualTo(String value) {
            addCriterion("update_program_id <>", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdGreaterThan(String value) {
            addCriterion("update_program_id >", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_program_id >=", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLessThan(String value) {
            addCriterion("update_program_id <", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLessThanOrEqualTo(String value) {
            addCriterion("update_program_id <=", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLike(String value) {
            addCriterion("update_program_id like", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotLike(String value) {
            addCriterion("update_program_id not like", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIn(List<String> values) {
            addCriterion("update_program_id in", values, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotIn(List<String> values) {
            addCriterion("update_program_id not in", values, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdBetween(String value1, String value2) {
            addCriterion("update_program_id between", value1, value2, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotBetween(String value1, String value2) {
            addCriterion("update_program_id not between", value1, value2, "updateProgramId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_g_class_link
     *
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_g_class_link
     *
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
