package com.fastretailing.dcp.sales.common.entity;

import lombok.Data;

@Data
public class ItemListDetailMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.system_brand_code
     *
     */
    private String systemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.system_country_code
     *
     */
    private String systemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.skulist_code
     *
     */
    private String skulistCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.item_code
     *
     */
    private String itemCode;
}
