package com.fastretailing.dcp.sales.common.entity;

import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ItemListDetailMaster extends ItemListDetailMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.system_business_code
     *
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.item_level
     *
     */
    private Integer itemLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.inventory_management_level
     *
     */
    private Integer inventoryManagementLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.pack_ind
     *
     */
    private String packInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.main_item_flag
     *
     */
    private boolean mainItemFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_detail.update_program_id
     *
     */
    private String updateProgramId;
}
