package com.fastretailing.dcp.sales.common.entity;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ItemListHeaderMaster extends ItemListHeaderMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.system_business_code
     *
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.item_list_name
     *
     */
    private String itemListName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.parent_skulist_code
     *
     */
    private String parentSkulistCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.color_code
     *
     */
    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.size_code
     *
     */
    private String sizeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.pattern_length_code
     *
     */
    private String patternLengthCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.major_category_code
     *
     */
    private String majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.class_code
     *
     */
    private String classCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.middle_category_code
     *
     */
    private String middleCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.small_category_value
     *
     */
    private Integer smallCategoryValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.initial_selling_price
     *
     */
    private BigDecimal initialSellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.regular_item_flag
     *
     */
    private boolean regularItemFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.core_attribute_flag
     *
     */
    private boolean coreAttributeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.out_of_stock_judge_quantity
     *
     */
    private Integer outOfStockJudgeQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.line_up_type_code
     *
     */
    private String lineUpTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.input_aggregation_type
     *
     */
    private String inputAggregationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.skulist_status
     *
     */
    private String skulistStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.view_item_code
     *
     */
    private String viewItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.item_list_hierarchy_code
     *
     */
    private String itemListHierarchyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.year_code
     *
     */
    private String yearCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.view_year_type
     *
     */
    private String viewYearType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.season_code
     *
     */
    private String seasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.detail_season_code
     *
     */
    private String detailSeasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.skulist_pattern_code
     *
     */
    private String skulistPatternCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.set_object_auto_update_flag
     *
     */
    private boolean setObjectAutoUpdateFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_list_head.update_program_id
     *
     */
    private String updateProgramId;
}
