package com.fastretailing.dcp.sales.common.entity;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ItemPackMaster extends ItemPackMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.system_business_code
     *
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.item_code_type
     *
     */
    private String itemCodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.view_item_code
     *
     */
    private String viewItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.year_code
     *
     */
    private String yearCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.view_year_type
     *
     */
    private String viewYearType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.season_code
     *
     */
    private String seasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.detail_season_code
     *
     */
    private String detailSeasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.sales_country_code
     *
     */
    private String salesCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.color_code
     *
     */
    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.size_code
     *
     */
    private String sizeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.pattern_length_code
     *
     */
    private String patternLengthCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.major_category_code
     *
     */
    private String majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.class_code
     *
     */
    private String classCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.middle_category_code
     *
     */
    private String middleCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.small_category_value
     *
     */
    private Integer smallCategoryValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.item_parent
     *
     */
    private String itemParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.item_crand_parent
     *
     */
    private String itemCrandParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.item_level
     *
     */
    private Integer itemLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.transaction_level
     *
     */
    private Integer transactionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.pack_flag
     *
     */
    private boolean packFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.simple_item_pack_flag
     *
     */
    private boolean simpleItemPackFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.contains_inner_kind
     *
     */
    private String containsInnerKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.sellable_flag
     *
     */
    private boolean sellableFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.orderable_flag
     *
     */
    private boolean orderableFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.pack_status
     *
     */
    private String packStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.order_unit_type
     *
     */
    private String orderUnitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.asort_code
     *
     */
    private String asortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.fob
     *
     */
    private BigDecimal fob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.cost_price_sequence
     *
     */
    private Integer costPriceSequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.stock_buying_type_code
     *
     */
    private String stockBuyingTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.initial_selling_price
     *
     */
    private BigDecimal initialSellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.sales_zone_group
     *
     */
    private Integer salesZoneGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.standard_sales_unit
     *
     */
    private String standardSalesUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.item_name
     *
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.intern_item_name
     *
     */
    private String internItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.pos_item_name
     *
     */
    private String posItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.second_pos_item_name
     *
     */
    private String secondPosItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.external_item_name_1
     *
     */
    private String externalItemName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.external_item_name_2
     *
     */
    private String externalItemName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.external_item_name_3
     *
     */
    private String externalItemName3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.external_item_name_4
     *
     */
    private String externalItemName4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.second_item_name
     *
     */
    private String secondItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.picking_shipment_flag
     *
     */
    private boolean pickingShipmentFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.direct_delivery_unit_quantity
     *
     */
    private Integer directDeliveryUnitQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.regular_item_flag
     *
     */
    private boolean regularItemFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.color_size_management_flag
     *
     */
    private boolean colorSizeManagementFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.b_item_return_possible_flag
     *
     */
    private boolean bItemReturnPossibleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.status
     *
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.delivery_type_code
     *
     */
    private String deliveryTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.supplier_code
     *
     */
    private String supplierCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.stock_buying_cost
     *
     */
    private BigDecimal stockBuyingCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.packing_quantity
     *
     */
    private Integer packingQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.picking_unit_quantity
     *
     */
    private Integer pickingUnitQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.selling_price
     *
     */
    private BigDecimal sellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.selling_unit
     *
     */
    private String sellingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.taxation_flag
     *
     */
    private boolean taxationFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.batch_region
     *
     */
    private Integer batchRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_item_pack.update_program_id
     *
     */
    private String updateProgramId;
}
