package com.fastretailing.dcp.sales.common.entity;

import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class LotNumberManagement extends LotNumberManagementKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.store_group_code
     *
     */
    private String storeGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.batch_region
     *
     */
    private Integer batchRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.check_flag
     *
     */
    private boolean checkFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lot_number_mgm.update_program_id
     *
     */
    private String updateProgramId;
}
