package com.fastretailing.dcp.sales.common.entity;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

public class NonItemMasterCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_non_item
     *
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_non_item
     *
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_non_item
     *
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public NonItemMasterCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_non_item
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_non_item
     *
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSystemCountryCodeIsNull() {
            addCriterion("system_country_code is null");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeIsNotNull() {
            addCriterion("system_country_code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeEqualTo(String value) {
            addCriterion("system_country_code =", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeNotEqualTo(String value) {
            addCriterion("system_country_code <>", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeGreaterThan(String value) {
            addCriterion("system_country_code >", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_country_code >=", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeLessThan(String value) {
            addCriterion("system_country_code <", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeLessThanOrEqualTo(String value) {
            addCriterion("system_country_code <=", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeLike(String value) {
            addCriterion("system_country_code like", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeNotLike(String value) {
            addCriterion("system_country_code not like", value, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeIn(List<String> values) {
            addCriterion("system_country_code in", values, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeNotIn(List<String> values) {
            addCriterion("system_country_code not in", values, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeBetween(String value1, String value2) {
            addCriterion("system_country_code between", value1, value2, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemCountryCodeNotBetween(String value1, String value2) {
            addCriterion("system_country_code not between", value1, value2, "systemCountryCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeIsNull() {
            addCriterion("system_brand_code is null");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeIsNotNull() {
            addCriterion("system_brand_code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeEqualTo(String value) {
            addCriterion("system_brand_code =", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeNotEqualTo(String value) {
            addCriterion("system_brand_code <>", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeGreaterThan(String value) {
            addCriterion("system_brand_code >", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_brand_code >=", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeLessThan(String value) {
            addCriterion("system_brand_code <", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeLessThanOrEqualTo(String value) {
            addCriterion("system_brand_code <=", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeLike(String value) {
            addCriterion("system_brand_code like", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeNotLike(String value) {
            addCriterion("system_brand_code not like", value, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeIn(List<String> values) {
            addCriterion("system_brand_code in", values, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeNotIn(List<String> values) {
            addCriterion("system_brand_code not in", values, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeBetween(String value1, String value2) {
            addCriterion("system_brand_code between", value1, value2, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andSystemBrandCodeNotBetween(String value1, String value2) {
            addCriterion("system_brand_code not between", value1, value2, "systemBrandCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeIsNull() {
            addCriterion("non_item_code is null");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeIsNotNull() {
            addCriterion("non_item_code is not null");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeEqualTo(String value) {
            addCriterion("non_item_code =", value, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeNotEqualTo(String value) {
            addCriterion("non_item_code <>", value, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeGreaterThan(String value) {
            addCriterion("non_item_code >", value, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("non_item_code >=", value, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeLessThan(String value) {
            addCriterion("non_item_code <", value, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeLessThanOrEqualTo(String value) {
            addCriterion("non_item_code <=", value, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeLike(String value) {
            addCriterion("non_item_code like", value, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeNotLike(String value) {
            addCriterion("non_item_code not like", value, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeIn(List<String> values) {
            addCriterion("non_item_code in", values, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeNotIn(List<String> values) {
            addCriterion("non_item_code not in", values, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeBetween(String value1, String value2) {
            addCriterion("non_item_code between", value1, value2, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andNonItemCodeNotBetween(String value1, String value2) {
            addCriterion("non_item_code not between", value1, value2, "nonItemCode");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateIsNull() {
            addCriterion("apply_start_date is null");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateIsNotNull() {
            addCriterion("apply_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateEqualTo(OffsetDateTime value) {
            addCriterion("apply_start_date =", value, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateNotEqualTo(OffsetDateTime value) {
            addCriterion("apply_start_date <>", value, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateGreaterThan(OffsetDateTime value) {
            addCriterion("apply_start_date >", value, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("apply_start_date >=", value, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateLessThan(OffsetDateTime value) {
            addCriterion("apply_start_date <", value, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("apply_start_date <=", value, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateIn(List<OffsetDateTime> values) {
            addCriterion("apply_start_date in", values, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateNotIn(List<OffsetDateTime> values) {
            addCriterion("apply_start_date not in", values, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("apply_start_date between", value1, value2, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyStartDateNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("apply_start_date not between", value1, value2, "applyStartDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateIsNull() {
            addCriterion("apply_end_date is null");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateIsNotNull() {
            addCriterion("apply_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateEqualTo(OffsetDateTime value) {
            addCriterion("apply_end_date =", value, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateNotEqualTo(OffsetDateTime value) {
            addCriterion("apply_end_date <>", value, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateGreaterThan(OffsetDateTime value) {
            addCriterion("apply_end_date >", value, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("apply_end_date >=", value, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateLessThan(OffsetDateTime value) {
            addCriterion("apply_end_date <", value, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("apply_end_date <=", value, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateIn(List<OffsetDateTime> values) {
            addCriterion("apply_end_date in", values, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateNotIn(List<OffsetDateTime> values) {
            addCriterion("apply_end_date not in", values, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("apply_end_date between", value1, value2, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andApplyEndDateNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("apply_end_date not between", value1, value2, "applyEndDate");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeIsNull() {
            addCriterion("non_item_type is null");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeIsNotNull() {
            addCriterion("non_item_type is not null");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeEqualTo(String value) {
            addCriterion("non_item_type =", value, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeNotEqualTo(String value) {
            addCriterion("non_item_type <>", value, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeGreaterThan(String value) {
            addCriterion("non_item_type >", value, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("non_item_type >=", value, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeLessThan(String value) {
            addCriterion("non_item_type <", value, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeLessThanOrEqualTo(String value) {
            addCriterion("non_item_type <=", value, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeLike(String value) {
            addCriterion("non_item_type like", value, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeNotLike(String value) {
            addCriterion("non_item_type not like", value, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeIn(List<String> values) {
            addCriterion("non_item_type in", values, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeNotIn(List<String> values) {
            addCriterion("non_item_type not in", values, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeBetween(String value1, String value2) {
            addCriterion("non_item_type between", value1, value2, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andNonItemTypeNotBetween(String value1, String value2) {
            addCriterion("non_item_type not between", value1, value2, "nonItemType");
            return (Criteria) this;
        }

        public Criteria andPosItemNameIsNull() {
            addCriterion("pos_item_name is null");
            return (Criteria) this;
        }

        public Criteria andPosItemNameIsNotNull() {
            addCriterion("pos_item_name is not null");
            return (Criteria) this;
        }

        public Criteria andPosItemNameEqualTo(String value) {
            addCriterion("pos_item_name =", value, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameNotEqualTo(String value) {
            addCriterion("pos_item_name <>", value, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameGreaterThan(String value) {
            addCriterion("pos_item_name >", value, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("pos_item_name >=", value, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameLessThan(String value) {
            addCriterion("pos_item_name <", value, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameLessThanOrEqualTo(String value) {
            addCriterion("pos_item_name <=", value, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameLike(String value) {
            addCriterion("pos_item_name like", value, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameNotLike(String value) {
            addCriterion("pos_item_name not like", value, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameIn(List<String> values) {
            addCriterion("pos_item_name in", values, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameNotIn(List<String> values) {
            addCriterion("pos_item_name not in", values, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameBetween(String value1, String value2) {
            addCriterion("pos_item_name between", value1, value2, "posItemName");
            return (Criteria) this;
        }

        public Criteria andPosItemNameNotBetween(String value1, String value2) {
            addCriterion("pos_item_name not between", value1, value2, "posItemName");
            return (Criteria) this;
        }

        public Criteria andUnitRetailIsNull() {
            addCriterion("unit_retail is null");
            return (Criteria) this;
        }

        public Criteria andUnitRetailIsNotNull() {
            addCriterion("unit_retail is not null");
            return (Criteria) this;
        }

        public Criteria andUnitRetailEqualTo(BigDecimal value) {
            addCriterion("unit_retail =", value, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailNotEqualTo(BigDecimal value) {
            addCriterion("unit_retail <>", value, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailGreaterThan(BigDecimal value) {
            addCriterion("unit_retail >", value, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("unit_retail >=", value, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailLessThan(BigDecimal value) {
            addCriterion("unit_retail <", value, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailLessThanOrEqualTo(BigDecimal value) {
            addCriterion("unit_retail <=", value, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailIn(List<BigDecimal> values) {
            addCriterion("unit_retail in", values, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailNotIn(List<BigDecimal> values) {
            addCriterion("unit_retail not in", values, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("unit_retail between", value1, value2, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andUnitRetailNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("unit_retail not between", value1, value2, "unitRetail");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeIsNull() {
            addCriterion("g_dept_code is null");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeIsNotNull() {
            addCriterion("g_dept_code is not null");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeEqualTo(String value) {
            addCriterion("g_dept_code =", value, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeNotEqualTo(String value) {
            addCriterion("g_dept_code <>", value, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeGreaterThan(String value) {
            addCriterion("g_dept_code >", value, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeGreaterThanOrEqualTo(String value) {
            addCriterion("g_dept_code >=", value, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeLessThan(String value) {
            addCriterion("g_dept_code <", value, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeLessThanOrEqualTo(String value) {
            addCriterion("g_dept_code <=", value, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeLike(String value) {
            addCriterion("g_dept_code like", value, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeNotLike(String value) {
            addCriterion("g_dept_code not like", value, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeIn(List<String> values) {
            addCriterion("g_dept_code in", values, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeNotIn(List<String> values) {
            addCriterion("g_dept_code not in", values, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeBetween(String value1, String value2) {
            addCriterion("g_dept_code between", value1, value2, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andGDeptCodeNotBetween(String value1, String value2) {
            addCriterion("g_dept_code not between", value1, value2, "gDeptCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeIsNull() {
            addCriterion("major_category_code is null");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeIsNotNull() {
            addCriterion("major_category_code is not null");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeEqualTo(Integer value) {
            addCriterion("major_category_code =", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeNotEqualTo(Integer value) {
            addCriterion("major_category_code <>", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeGreaterThan(Integer value) {
            addCriterion("major_category_code >", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("major_category_code >=", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeLessThan(Integer value) {
            addCriterion("major_category_code <", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeLessThanOrEqualTo(Integer value) {
            addCriterion("major_category_code <=", value, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeIn(List<Integer> values) {
            addCriterion("major_category_code in", values, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeNotIn(List<Integer> values) {
            addCriterion("major_category_code not in", values, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeBetween(Integer value1, Integer value2) {
            addCriterion("major_category_code between", value1, value2, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andMajorCategoryCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("major_category_code not between", value1, value2, "majorCategoryCode");
            return (Criteria) this;
        }

        public Criteria andTaxRateIsNull() {
            addCriterion("tax_rate is null");
            return (Criteria) this;
        }

        public Criteria andTaxRateIsNotNull() {
            addCriterion("tax_rate is not null");
            return (Criteria) this;
        }

        public Criteria andTaxRateEqualTo(String value) {
            addCriterion("tax_rate =", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateNotEqualTo(String value) {
            addCriterion("tax_rate <>", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateGreaterThan(String value) {
            addCriterion("tax_rate >", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateGreaterThanOrEqualTo(String value) {
            addCriterion("tax_rate >=", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateLessThan(String value) {
            addCriterion("tax_rate <", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateLessThanOrEqualTo(String value) {
            addCriterion("tax_rate <=", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateLike(String value) {
            addCriterion("tax_rate like", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateNotLike(String value) {
            addCriterion("tax_rate not like", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateIn(List<String> values) {
            addCriterion("tax_rate in", values, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateNotIn(List<String> values) {
            addCriterion("tax_rate not in", values, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateBetween(String value1, String value2) {
            addCriterion("tax_rate between", value1, value2, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateNotBetween(String value1, String value2) {
            addCriterion("tax_rate not between", value1, value2, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxTypeIsNull() {
            addCriterion("tax_type is null");
            return (Criteria) this;
        }

        public Criteria andTaxTypeIsNotNull() {
            addCriterion("tax_type is not null");
            return (Criteria) this;
        }

        public Criteria andTaxTypeEqualTo(String value) {
            addCriterion("tax_type =", value, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeNotEqualTo(String value) {
            addCriterion("tax_type <>", value, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeGreaterThan(String value) {
            addCriterion("tax_type >", value, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeGreaterThanOrEqualTo(String value) {
            addCriterion("tax_type >=", value, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeLessThan(String value) {
            addCriterion("tax_type <", value, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeLessThanOrEqualTo(String value) {
            addCriterion("tax_type <=", value, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeLike(String value) {
            addCriterion("tax_type like", value, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeNotLike(String value) {
            addCriterion("tax_type not like", value, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeIn(List<String> values) {
            addCriterion("tax_type in", values, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeNotIn(List<String> values) {
            addCriterion("tax_type not in", values, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeBetween(String value1, String value2) {
            addCriterion("tax_type between", value1, value2, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxTypeNotBetween(String value1, String value2) {
            addCriterion("tax_type not between", value1, value2, "taxType");
            return (Criteria) this;
        }

        public Criteria andTaxKindIsNull() {
            addCriterion("tax_kind is null");
            return (Criteria) this;
        }

        public Criteria andTaxKindIsNotNull() {
            addCriterion("tax_kind is not null");
            return (Criteria) this;
        }

        public Criteria andTaxKindEqualTo(String value) {
            addCriterion("tax_kind =", value, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindNotEqualTo(String value) {
            addCriterion("tax_kind <>", value, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindGreaterThan(String value) {
            addCriterion("tax_kind >", value, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindGreaterThanOrEqualTo(String value) {
            addCriterion("tax_kind >=", value, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindLessThan(String value) {
            addCriterion("tax_kind <", value, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindLessThanOrEqualTo(String value) {
            addCriterion("tax_kind <=", value, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindLike(String value) {
            addCriterion("tax_kind like", value, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindNotLike(String value) {
            addCriterion("tax_kind not like", value, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindIn(List<String> values) {
            addCriterion("tax_kind in", values, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindNotIn(List<String> values) {
            addCriterion("tax_kind not in", values, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindBetween(String value1, String value2) {
            addCriterion("tax_kind between", value1, value2, "taxKind");
            return (Criteria) this;
        }

        public Criteria andTaxKindNotBetween(String value1, String value2) {
            addCriterion("tax_kind not between", value1, value2, "taxKind");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagIsNull() {
            addCriterion("discount_flag is null");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagIsNotNull() {
            addCriterion("discount_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagEqualTo(boolean value) {
            addCriterion("discount_flag =", value, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagNotEqualTo(boolean value) {
            addCriterion("discount_flag <>", value, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagGreaterThan(boolean value) {
            addCriterion("discount_flag >", value, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagGreaterThanOrEqualTo(boolean value) {
            addCriterion("discount_flag >=", value, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagLessThan(boolean value) {
            addCriterion("discount_flag <", value, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagLessThanOrEqualTo(boolean value) {
            addCriterion("discount_flag <=", value, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagIn(List<Boolean> values) {
            addCriterion("discount_flag in", values, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagNotIn(List<Boolean> values) {
            addCriterion("discount_flag not in", values, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagBetween(boolean value1, boolean value2) {
            addCriterion("discount_flag between", value1, value2, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andDiscountFlagNotBetween(boolean value1, boolean value2) {
            addCriterion("discount_flag not between", value1, value2, "discountFlag");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIsNull() {
            addCriterion("create_program_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIsNotNull() {
            addCriterion("create_program_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdEqualTo(String value) {
            addCriterion("create_program_id =", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotEqualTo(String value) {
            addCriterion("create_program_id <>", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdGreaterThan(String value) {
            addCriterion("create_program_id >", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_program_id >=", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLessThan(String value) {
            addCriterion("create_program_id <", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLessThanOrEqualTo(String value) {
            addCriterion("create_program_id <=", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLike(String value) {
            addCriterion("create_program_id like", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotLike(String value) {
            addCriterion("create_program_id not like", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIn(List<String> values) {
            addCriterion("create_program_id in", values, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotIn(List<String> values) {
            addCriterion("create_program_id not in", values, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdBetween(String value1, String value2) {
            addCriterion("create_program_id between", value1, value2, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotBetween(String value1, String value2) {
            addCriterion("create_program_id not between", value1, value2, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIsNull() {
            addCriterion("update_program_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIsNotNull() {
            addCriterion("update_program_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdEqualTo(String value) {
            addCriterion("update_program_id =", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotEqualTo(String value) {
            addCriterion("update_program_id <>", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdGreaterThan(String value) {
            addCriterion("update_program_id >", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_program_id >=", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLessThan(String value) {
            addCriterion("update_program_id <", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLessThanOrEqualTo(String value) {
            addCriterion("update_program_id <=", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLike(String value) {
            addCriterion("update_program_id like", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotLike(String value) {
            addCriterion("update_program_id not like", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIn(List<String> values) {
            addCriterion("update_program_id in", values, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotIn(List<String> values) {
            addCriterion("update_program_id not in", values, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdBetween(String value1, String value2) {
            addCriterion("update_program_id between", value1, value2, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotBetween(String value1, String value2) {
            addCriterion("update_program_id not between", value1, value2, "updateProgramId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_non_item
     *
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_non_item
     *
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
