package com.fastretailing.dcp.sales.common.entity;

import lombok.Data;

@Data
public class NonItemIfMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.lot_num
     *
     */
    private String lotNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.system_country_code
     *
     */
    private String systemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.system_brand_code
     *
     */
    private String systemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.non_item_code
     *
     */
    private String nonItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.apply_start_date
     *
     */
    private String applyStartDate;
}
