package com.fastretailing.dcp.sales.common.entity;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class NonItemIfMaster extends NonItemIfMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.apply_end_date
     *
     */
    private String applyEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.non_item_type
     *
     */
    private String nonItemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.pos_item_name
     *
     */
    private String posItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.unit_retail
     *
     */
    private BigDecimal unitRetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.g_dept_code
     *
     */
    private String gDeptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.major_category_code
     *
     */
    private Integer majorCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.tax_rate
     *
     */
    private String taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.tax_type
     *
     */
    private String taxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.tax_kind
     *
     */
    private String taxKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.discount_flag
     *
     */
    private boolean discountFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_non_item_if.update_program_id
     *
     */
    private String updateProgramId;
}
