package com.fastretailing.dcp.sales.common.entity;

import lombok.Data;

@Data
public class PayOffSummaryMappingMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_pay_off_summary_mapping.mapping_pattern
     *
     */
    private Integer mappingPattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_pay_off_summary_mapping.payoff_type_code
     *
     */
    private String payoffTypeCode;
}
