package com.fastretailing.dcp.sales.common.entity;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TransactionInquirySalesTransactionDiscount extends TransactionInquirySalesTransactionDiscountKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.item_discount_sub_number
     *
     */
    private Integer itemDiscountSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.quantity_code
     *
     */
    private String quantityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.discount_quantity
     *
     */
    private Integer discountQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.discount_amount_tax_excluded_currency_code
     *
     */
    private String discountAmountTaxExcludedCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.discount_amount_tax_excluded
     *
     */
    private BigDecimal discountAmountTaxExcluded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.discount_amount_tax_included_currency_code
     *
     */
    private String discountAmountTaxIncludedCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.discount_amount_tax_included
     *
     */
    private BigDecimal discountAmountTaxIncluded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_discount.update_program_id
     *
     */
    private String updateProgramId;
}
