package com.fastretailing.dcp.sales.common.entity;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

public class TransactionInquirySalesTransactionTotalAmountCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public TransactionInquirySalesTransactionTotalAmountCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderSubNumberIsNull() {
            addCriterion("order_sub_number is null");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberIsNotNull() {
            addCriterion("order_sub_number is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberEqualTo(Integer value) {
            addCriterion("order_sub_number =", value, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberNotEqualTo(Integer value) {
            addCriterion("order_sub_number <>", value, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberGreaterThan(Integer value) {
            addCriterion("order_sub_number >", value, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_sub_number >=", value, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberLessThan(Integer value) {
            addCriterion("order_sub_number <", value, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberLessThanOrEqualTo(Integer value) {
            addCriterion("order_sub_number <=", value, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberIn(List<Integer> values) {
            addCriterion("order_sub_number in", values, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberNotIn(List<Integer> values) {
            addCriterion("order_sub_number not in", values, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberBetween(Integer value1, Integer value2) {
            addCriterion("order_sub_number between", value1, value2, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andOrderSubNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("order_sub_number not between", value1, value2, "orderSubNumber");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdIsNull() {
            addCriterion("sales_transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdIsNotNull() {
            addCriterion("sales_transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdEqualTo(String value) {
            addCriterion("sales_transaction_id =", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdNotEqualTo(String value) {
            addCriterion("sales_transaction_id <>", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdGreaterThan(String value) {
            addCriterion("sales_transaction_id >", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("sales_transaction_id >=", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdLessThan(String value) {
            addCriterion("sales_transaction_id <", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("sales_transaction_id <=", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdLike(String value) {
            addCriterion("sales_transaction_id like", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdNotLike(String value) {
            addCriterion("sales_transaction_id not like", value, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdIn(List<String> values) {
            addCriterion("sales_transaction_id in", values, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdNotIn(List<String> values) {
            addCriterion("sales_transaction_id not in", values, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdBetween(String value1, String value2) {
            addCriterion("sales_transaction_id between", value1, value2, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionIdNotBetween(String value1, String value2) {
            addCriterion("sales_transaction_id not between", value1, value2, "salesTransactionId");
            return (Criteria) this;
        }

        public Criteria andTotalTypeIsNull() {
            addCriterion("total_type is null");
            return (Criteria) this;
        }

        public Criteria andTotalTypeIsNotNull() {
            addCriterion("total_type is not null");
            return (Criteria) this;
        }

        public Criteria andTotalTypeEqualTo(String value) {
            addCriterion("total_type =", value, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeNotEqualTo(String value) {
            addCriterion("total_type <>", value, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeGreaterThan(String value) {
            addCriterion("total_type >", value, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeGreaterThanOrEqualTo(String value) {
            addCriterion("total_type >=", value, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeLessThan(String value) {
            addCriterion("total_type <", value, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeLessThanOrEqualTo(String value) {
            addCriterion("total_type <=", value, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeLike(String value) {
            addCriterion("total_type like", value, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeNotLike(String value) {
            addCriterion("total_type not like", value, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeIn(List<String> values) {
            addCriterion("total_type in", values, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeNotIn(List<String> values) {
            addCriterion("total_type not in", values, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeBetween(String value1, String value2) {
            addCriterion("total_type between", value1, value2, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalTypeNotBetween(String value1, String value2) {
            addCriterion("total_type not between", value1, value2, "totalType");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberIsNull() {
            addCriterion("total_amount_sub_number is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberIsNotNull() {
            addCriterion("total_amount_sub_number is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberEqualTo(Integer value) {
            addCriterion("total_amount_sub_number =", value, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberNotEqualTo(Integer value) {
            addCriterion("total_amount_sub_number <>", value, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberGreaterThan(Integer value) {
            addCriterion("total_amount_sub_number >", value, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_amount_sub_number >=", value, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberLessThan(Integer value) {
            addCriterion("total_amount_sub_number <", value, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberLessThanOrEqualTo(Integer value) {
            addCriterion("total_amount_sub_number <=", value, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberIn(List<Integer> values) {
            addCriterion("total_amount_sub_number in", values, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberNotIn(List<Integer> values) {
            addCriterion("total_amount_sub_number not in", values, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberBetween(Integer value1, Integer value2) {
            addCriterion("total_amount_sub_number between", value1, value2, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountSubNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("total_amount_sub_number not between", value1, value2, "totalAmountSubNumber");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeIsNull() {
            addCriterion("total_amount_tax_excluded_currency_code is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeIsNotNull() {
            addCriterion("total_amount_tax_excluded_currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeEqualTo(String value) {
            addCriterion("total_amount_tax_excluded_currency_code =", value, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeNotEqualTo(String value) {
            addCriterion("total_amount_tax_excluded_currency_code <>", value, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeGreaterThan(String value) {
            addCriterion("total_amount_tax_excluded_currency_code >", value, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("total_amount_tax_excluded_currency_code >=", value, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeLessThan(String value) {
            addCriterion("total_amount_tax_excluded_currency_code <", value, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("total_amount_tax_excluded_currency_code <=", value, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeLike(String value) {
            addCriterion("total_amount_tax_excluded_currency_code like", value, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeNotLike(String value) {
            addCriterion("total_amount_tax_excluded_currency_code not like", value, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeIn(List<String> values) {
            addCriterion("total_amount_tax_excluded_currency_code in", values, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeNotIn(List<String> values) {
            addCriterion("total_amount_tax_excluded_currency_code not in", values, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeBetween(String value1, String value2) {
            addCriterion("total_amount_tax_excluded_currency_code between", value1, value2, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("total_amount_tax_excluded_currency_code not between", value1, value2, "totalAmountTaxExcludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueIsNull() {
            addCriterion("total_amount_tax_excluded_value is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueIsNotNull() {
            addCriterion("total_amount_tax_excluded_value is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueEqualTo(BigDecimal value) {
            addCriterion("total_amount_tax_excluded_value =", value, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueNotEqualTo(BigDecimal value) {
            addCriterion("total_amount_tax_excluded_value <>", value, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueGreaterThan(BigDecimal value) {
            addCriterion("total_amount_tax_excluded_value >", value, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_amount_tax_excluded_value >=", value, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueLessThan(BigDecimal value) {
            addCriterion("total_amount_tax_excluded_value <", value, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_amount_tax_excluded_value <=", value, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueIn(List<BigDecimal> values) {
            addCriterion("total_amount_tax_excluded_value in", values, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueNotIn(List<BigDecimal> values) {
            addCriterion("total_amount_tax_excluded_value not in", values, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_amount_tax_excluded_value between", value1, value2, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxExcludedValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_amount_tax_excluded_value not between", value1, value2, "totalAmountTaxExcludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeIsNull() {
            addCriterion("total_amount_tax_included_currency_code is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeIsNotNull() {
            addCriterion("total_amount_tax_included_currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeEqualTo(String value) {
            addCriterion("total_amount_tax_included_currency_code =", value, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeNotEqualTo(String value) {
            addCriterion("total_amount_tax_included_currency_code <>", value, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeGreaterThan(String value) {
            addCriterion("total_amount_tax_included_currency_code >", value, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("total_amount_tax_included_currency_code >=", value, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeLessThan(String value) {
            addCriterion("total_amount_tax_included_currency_code <", value, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("total_amount_tax_included_currency_code <=", value, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeLike(String value) {
            addCriterion("total_amount_tax_included_currency_code like", value, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeNotLike(String value) {
            addCriterion("total_amount_tax_included_currency_code not like", value, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeIn(List<String> values) {
            addCriterion("total_amount_tax_included_currency_code in", values, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeNotIn(List<String> values) {
            addCriterion("total_amount_tax_included_currency_code not in", values, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeBetween(String value1, String value2) {
            addCriterion("total_amount_tax_included_currency_code between", value1, value2, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("total_amount_tax_included_currency_code not between", value1, value2, "totalAmountTaxIncludedCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueIsNull() {
            addCriterion("total_amount_tax_included_value is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueIsNotNull() {
            addCriterion("total_amount_tax_included_value is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueEqualTo(BigDecimal value) {
            addCriterion("total_amount_tax_included_value =", value, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueNotEqualTo(BigDecimal value) {
            addCriterion("total_amount_tax_included_value <>", value, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueGreaterThan(BigDecimal value) {
            addCriterion("total_amount_tax_included_value >", value, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_amount_tax_included_value >=", value, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueLessThan(BigDecimal value) {
            addCriterion("total_amount_tax_included_value <", value, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_amount_tax_included_value <=", value, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueIn(List<BigDecimal> values) {
            addCriterion("total_amount_tax_included_value in", values, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueNotIn(List<BigDecimal> values) {
            addCriterion("total_amount_tax_included_value not in", values, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_amount_tax_included_value between", value1, value2, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTotalAmountTaxIncludedValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_amount_tax_included_value not between", value1, value2, "totalAmountTaxIncludedValue");
            return (Criteria) this;
        }

        public Criteria andTaxRateIsNull() {
            addCriterion("tax_rate is null");
            return (Criteria) this;
        }

        public Criteria andTaxRateIsNotNull() {
            addCriterion("tax_rate is not null");
            return (Criteria) this;
        }

        public Criteria andTaxRateEqualTo(BigDecimal value) {
            addCriterion("tax_rate =", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateNotEqualTo(BigDecimal value) {
            addCriterion("tax_rate <>", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateGreaterThan(BigDecimal value) {
            addCriterion("tax_rate >", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_rate >=", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateLessThan(BigDecimal value) {
            addCriterion("tax_rate <", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_rate <=", value, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateIn(List<BigDecimal> values) {
            addCriterion("tax_rate in", values, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateNotIn(List<BigDecimal> values) {
            addCriterion("tax_rate not in", values, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax_rate between", value1, value2, "taxRate");
            return (Criteria) this;
        }

        public Criteria andTaxRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax_rate not between", value1, value2, "taxRate");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1IsNull() {
            addCriterion("sales_transaction_information_1 is null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1IsNotNull() {
            addCriterion("sales_transaction_information_1 is not null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1EqualTo(String value) {
            addCriterion("sales_transaction_information_1 =", value, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1NotEqualTo(String value) {
            addCriterion("sales_transaction_information_1 <>", value, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1GreaterThan(String value) {
            addCriterion("sales_transaction_information_1 >", value, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1GreaterThanOrEqualTo(String value) {
            addCriterion("sales_transaction_information_1 >=", value, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1LessThan(String value) {
            addCriterion("sales_transaction_information_1 <", value, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1LessThanOrEqualTo(String value) {
            addCriterion("sales_transaction_information_1 <=", value, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1Like(String value) {
            addCriterion("sales_transaction_information_1 like", value, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1NotLike(String value) {
            addCriterion("sales_transaction_information_1 not like", value, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1In(List<String> values) {
            addCriterion("sales_transaction_information_1 in", values, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1NotIn(List<String> values) {
            addCriterion("sales_transaction_information_1 not in", values, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1Between(String value1, String value2) {
            addCriterion("sales_transaction_information_1 between", value1, value2, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation1NotBetween(String value1, String value2) {
            addCriterion("sales_transaction_information_1 not between", value1, value2, "salesTransactionInformation1");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2IsNull() {
            addCriterion("sales_transaction_information_2 is null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2IsNotNull() {
            addCriterion("sales_transaction_information_2 is not null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2EqualTo(String value) {
            addCriterion("sales_transaction_information_2 =", value, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2NotEqualTo(String value) {
            addCriterion("sales_transaction_information_2 <>", value, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2GreaterThan(String value) {
            addCriterion("sales_transaction_information_2 >", value, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2GreaterThanOrEqualTo(String value) {
            addCriterion("sales_transaction_information_2 >=", value, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2LessThan(String value) {
            addCriterion("sales_transaction_information_2 <", value, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2LessThanOrEqualTo(String value) {
            addCriterion("sales_transaction_information_2 <=", value, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2Like(String value) {
            addCriterion("sales_transaction_information_2 like", value, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2NotLike(String value) {
            addCriterion("sales_transaction_information_2 not like", value, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2In(List<String> values) {
            addCriterion("sales_transaction_information_2 in", values, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2NotIn(List<String> values) {
            addCriterion("sales_transaction_information_2 not in", values, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2Between(String value1, String value2) {
            addCriterion("sales_transaction_information_2 between", value1, value2, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation2NotBetween(String value1, String value2) {
            addCriterion("sales_transaction_information_2 not between", value1, value2, "salesTransactionInformation2");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3IsNull() {
            addCriterion("sales_transaction_information_3 is null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3IsNotNull() {
            addCriterion("sales_transaction_information_3 is not null");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3EqualTo(String value) {
            addCriterion("sales_transaction_information_3 =", value, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3NotEqualTo(String value) {
            addCriterion("sales_transaction_information_3 <>", value, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3GreaterThan(String value) {
            addCriterion("sales_transaction_information_3 >", value, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3GreaterThanOrEqualTo(String value) {
            addCriterion("sales_transaction_information_3 >=", value, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3LessThan(String value) {
            addCriterion("sales_transaction_information_3 <", value, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3LessThanOrEqualTo(String value) {
            addCriterion("sales_transaction_information_3 <=", value, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3Like(String value) {
            addCriterion("sales_transaction_information_3 like", value, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3NotLike(String value) {
            addCriterion("sales_transaction_information_3 not like", value, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3In(List<String> values) {
            addCriterion("sales_transaction_information_3 in", values, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3NotIn(List<String> values) {
            addCriterion("sales_transaction_information_3 not in", values, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3Between(String value1, String value2) {
            addCriterion("sales_transaction_information_3 between", value1, value2, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andSalesTransactionInformation3NotBetween(String value1, String value2) {
            addCriterion("sales_transaction_information_3 not between", value1, value2, "salesTransactionInformation3");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIsNull() {
            addCriterion("create_program_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIsNotNull() {
            addCriterion("create_program_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdEqualTo(String value) {
            addCriterion("create_program_id =", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotEqualTo(String value) {
            addCriterion("create_program_id <>", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdGreaterThan(String value) {
            addCriterion("create_program_id >", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_program_id >=", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLessThan(String value) {
            addCriterion("create_program_id <", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLessThanOrEqualTo(String value) {
            addCriterion("create_program_id <=", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdLike(String value) {
            addCriterion("create_program_id like", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotLike(String value) {
            addCriterion("create_program_id not like", value, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdIn(List<String> values) {
            addCriterion("create_program_id in", values, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotIn(List<String> values) {
            addCriterion("create_program_id not in", values, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdBetween(String value1, String value2) {
            addCriterion("create_program_id between", value1, value2, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateProgramIdNotBetween(String value1, String value2) {
            addCriterion("create_program_id not between", value1, value2, "createProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(OffsetDateTime value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(OffsetDateTime value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(OffsetDateTime value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<OffsetDateTime> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<OffsetDateTime> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(OffsetDateTime value1, OffsetDateTime value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIsNull() {
            addCriterion("update_program_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIsNotNull() {
            addCriterion("update_program_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdEqualTo(String value) {
            addCriterion("update_program_id =", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotEqualTo(String value) {
            addCriterion("update_program_id <>", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdGreaterThan(String value) {
            addCriterion("update_program_id >", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_program_id >=", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLessThan(String value) {
            addCriterion("update_program_id <", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLessThanOrEqualTo(String value) {
            addCriterion("update_program_id <=", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdLike(String value) {
            addCriterion("update_program_id like", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotLike(String value) {
            addCriterion("update_program_id not like", value, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdIn(List<String> values) {
            addCriterion("update_program_id in", values, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotIn(List<String> values) {
            addCriterion("update_program_id not in", values, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdBetween(String value1, String value2) {
            addCriterion("update_program_id between", value1, value2, "updateProgramId");
            return (Criteria) this;
        }

        public Criteria andUpdateProgramIdNotBetween(String value1, String value2) {
            addCriterion("update_program_id not between", value1, value2, "updateProgramId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_transaction_inquiry_sales_transaction_total_amount
     *
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
