package com.fastretailing.dcp.sales.common.entity;

import java.time.OffsetDateTime;
import lombok.Data;
import lombok.ToString;

@Data
@ToString(callSuper = true)
public class TranslationTenderMaster {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column m_trans_tender.store_code
    *
    * @mbg.generated
    */
   private String storeCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column m_trans_tender.tender_id
    *
    * @mbg.generated
    */
   private String tenderId;
   
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.tender_group
     *
     */
    private String tenderGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.valid_date
     *
     */
    private OffsetDateTime validDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.ims_tender_id
     *
     */
    private Integer imsTenderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.ims_tender_group
     *
     */
    private String imsTenderGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.update_program_id
     *
     */
    private String updateProgramId;
}
