package com.fastretailing.dcp.sales.common.entity;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TransactionInquirySalesTransactionTenderInformation extends TransactionInquirySalesTransactionTenderInformationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.discount_value_currency_code
     *
     */
    private String discountValueCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.discount_value
     *
     */
    private BigDecimal discountValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.discount_rate
     *
     */
    private BigDecimal discountRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.discount_code_id_corporate_id
     *
     */
    private String discountCodeIdCorporateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.coupon_type
     *
     */
    private String couponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.coupon_discount_amount_setting_currency_code
     *
     */
    private String couponDiscountAmountSettingCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.coupon_discount_amount_setting_value
     *
     */
    private BigDecimal couponDiscountAmountSettingValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.coupon_min_usage_amount_threshold_currency_code
     *
     */
    private String couponMinUsageAmountThresholdCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.coupon_min_usage_amount_threshold_value
     *
     */
    private BigDecimal couponMinUsageAmountThresholdValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.coupon_user_id
     *
     */
    private String couponUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.card_no
     *
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.credit_approval_code
     *
     */
    private String creditApprovalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.credit_processing_serial_number
     *
     */
    private String creditProcessingSerialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.credit_payment_type
     *
     */
    private String creditPaymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.credit_payment_count
     *
     */
    private Integer creditPaymentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.credit_affiliated_store_number
     *
     */
    private String creditAffiliatedStoreNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tender_info.update_program_id
     *
     */
    private String updateProgramId;
}
