package com.fastretailing.dcp.sales.common.entity;

import java.time.OffsetDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TransactionInquirySalesTransactionDetailInformation extends TransactionInquirySalesTransactionDetailInformationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.item_detail_sub_number
     *
     */
    private Integer itemDetailSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.key_code
     *
     */
    private String keyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.code_value_1
     *
     */
    private String codeValue1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.code_value_2
     *
     */
    private String codeValue2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.code_value_3
     *
     */
    private String codeValue3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.code_value_4
     *
     */
    private String codeValue4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.name_1
     *
     */
    private String name1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.name_2
     *
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.name_3
     *
     */
    private String name3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.name_4
     *
     */
    private String name4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.create_user_id
     *
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.create_datetime
     *
     */
    private OffsetDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.create_program_id
     *
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.update_user_id
     *
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.update_datetime
     *
     */
    private OffsetDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_detail_info.update_program_id
     *
     */
    private String updateProgramId;
}
