package com.fastretailing.dcp.sales.common.entity;

import lombok.Data;

@Data
public class TransactionInquirySalesTransactionTaxKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tax.order_sub_number
     *
     */
    private Integer orderSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tax.sales_transaction_id
     *
     */
    private String salesTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tax.detail_sub_number
     *
     */
    private Integer detailSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tax.tax_group
     *
     */
    private String taxGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_tax.tax_sub_number
     *
     */
    private Integer taxSubNumber;
}
