package com.fastretailing.dcp.sales.common.entity;

import lombok.Data;

@Data
public class TransactionInquirySalesTransactionHeaderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_header.order_sub_number
     *
     */
    private Integer orderSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction_inquiry_sales_transaction_header.sales_transaction_id
     *
     */
    private String salesTransactionId;
}
