DROP TABLE IF EXISTS public.m_business_country_state_setting CASCADE;
CREATE TABLE public.m_business_country_state_setting(
 system_brand_code varchar(4) NOT NULL,
 system_business_code varchar(10) NOT NULL,
 system_country_code varchar(3) NOT NULL,
 state_code varchar(4) NOT NULL,
 store_code varchar(10) NOT NULL,
 code_l1 varchar(50) NOT NULL,
 code_l2 varchar(50) NOT NULL,
 code_l3 varchar(50) NOT NULL,
 code_value varchar(50) NOT NULL,
 variable_type varchar(1) NOT NULL,
 display_order varchar(2) NOT NULL,
 create_user_id varchar(30),
 create_datetime timestamptz NOT NULL,
 create_program_id varchar(30),
 update_user_id varchar(30),
 update_datetime timestamptz,
 update_program_id varchar(30),
  CONSTRAINT m_business_country_state_setting_pk
   PRIMARY KEY(store_code,code_l1,code_l2,code_l3,code_value)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;

DROP TABLE IF EXISTS public.t_alteration_exclusion_control CASCADE;
CREATE TABLE public.t_alteration_exclusion_control(
 store_code varchar(10) NOT NULL,
 business_date varchar(8) NOT NULL,
 cash_register_no numeric(3) NOT NULL,
 data_alteration_type varchar(1) NOT NULL,
 exclusion_valid_time varchar(3),
 create_user_id varchar(30),
 create_datetime timestamptz NOT NULL,
 create_program_id varchar(30),
 update_user_id varchar(30),
 update_datetime timestamptz,
 update_program_id varchar(30),
  CONSTRAINT t_alteration_exclusion_control_pk
   PRIMARY KEY(store_code,business_date,cash_register_no,data_alteration_type)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;
DROP TABLE IF EXISTS public.t_sales_transaction_error_detail CASCADE;
CREATE TABLE public.t_sales_transaction_error_detail(
 sales_transaction_error_id varchar(57) NOT NULL,
 integrated_order_id varchar(27),
 sales_transaction_id varchar(30),
 store_code varchar(10),
 system_brand_code varchar(4),
 system_business_code varchar(10),
 system_country_code varchar(3),
 error_type varchar(10),
 regular_time_error_notification_flag boolean DEFAULT FALSE NOT NULL,
 daily_summary_error_notification_flag boolean DEFAULT FALSE NOT NULL,
 data_alteration_status_type varchar(1),
 error_occurred_list varchar(50),
 key_info_1 varchar(40),
 key_info_2 varchar(40),
 key_info_3 varchar(40),
 key_info_4 varchar(40),
 key_info_5 varchar(40),
 key_info_6 varchar(40),
 key_info_7 varchar(40),
 key_info_8 varchar(40),
 error_item_id_1 varchar(50),
 error_item_value_1 varchar(100),
 error_item_id_2 varchar(50),
 error_item_value_2 varchar(100),
 error_item_id_3 varchar(50),
 error_item_value_3 varchar(100),
 error_item_id_4 varchar(50),
 error_item_value_4 varchar(100),
 error_item_id_5 varchar(50),
 error_item_value_5 varchar(100),
 tax_type varchar(10),
 item_sales_amount numeric(24,4),
 non_item_sales_amount numeric(24,4),
 total_amount numeric(24,4),
 currency_code varchar(3),
 data_creation_date_time timestamptz,
 create_user_id varchar(30),
 create_datetime timestamptz NOT NULL,
 create_program_id varchar(30),
 update_user_id varchar(30),
 update_datetime timestamptz,
 update_program_id varchar(30),
  CONSTRAINT t_sales_transaction_error_detail_pk
   PRIMARY KEY(sales_transaction_error_id)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;

DROP TABLE IF EXISTS public.t_sales_error_sales_transaction_header CASCADE;
CREATE TABLE public.t_sales_error_sales_transaction_header(
 transaction_id varchar(57) NOT NULL,
 order_sub_number numeric(4) NOT NULL,
 sales_transaction_id varchar(30) NOT NULL,
 integrated_order_id varchar(27),
 sales_transaction_sub_number numeric(4),
 store_code varchar(10),
 data_creation_date_time timestamptz,
 data_creation_business_date varchar(8),
 cash_register_no numeric(3),
 receipt_no varchar(4),
 sales_linkage_type numeric(1),
 sales_transaction_type varchar(6),
 return_type numeric(1),
 system_brand_code varchar(4),
 system_business_code varchar(10),
 system_country_code varchar(3),
 channel_code varchar(10),
 order_status varchar(50),
 order_substatus varchar(50),
 order_status_update_date varchar(8),
 order_status_last_update_date_time timestamptz,
 order_cancelled_date_time timestamptz,
 booking_store_code varchar(10),
 booking_store_system_brand_code varchar(4),
 booking_store_system_business_code varchar(10),
 booking_store_system_country_code varchar(3),
 payment_status varchar(50),
 payment_store_code varchar(10),
 payment_store_system_brand_code varchar(4),
 payment_store_system_business_code varchar(10),
 payment_store_system_country_code varchar(3),
 transfer_out_status varchar(50),
 shipment_status varchar(50),
 shipment_store_code varchar(10),
 shipment_store_system_brand_code varchar(4),
 shipment_store_system_business_code varchar(10),
 shipment_store_system_country_code varchar(3),
 receiving_status varchar(50),
 receipt_store_code varchar(10),
 receipt_store_system_brand_code varchar(4),
 receipt_store_system_business_code varchar(10),
 receipt_store_system_country_code varchar(3),
 customer_id varchar(30),
 order_number_for_store_payment varchar(27),
 advance_received_store_code varchar(10),
 advance_received_store_system_brand_code varchar(4),
 advance_received_store_system_business_code varchar(10),
 advance_received_store_system_country_code varchar(3),
 operator_code varchar(18),
 original_transaction_id varchar(30),
 original_cash_register_no numeric(3),
 original_receipt_no varchar(4),
 deposit_currency_code varchar(3),
 deposit_value numeric(24,4),
 change_currency_code varchar(3),
 change_value numeric(24,4),
 receipt_no_for_credit_card_cancellation varchar(11),
 receipt_no_for_credit_card varchar(30),
 receipt_issued_flag boolean DEFAULT FALSE NOT NULL,
 e_receipt_target_flag boolean DEFAULT FALSE NOT NULL,
 processing_company_code varchar(20),
 employee_sale_flag boolean DEFAULT FALSE NOT NULL,
 consistency_sales_flag boolean DEFAULT FALSE NOT NULL,
 corporate_id varchar(20),
 sales_transaction_discount_flag boolean DEFAULT FALSE NOT NULL,
 sales_transaction_discount_amount_rate_currency_code varchar(3),
 sales_transaction_discount_amount_rate numeric(24,4),
 token_code varchar(30),
 create_user_id varchar(30),
 create_datetime timestamptz NOT NULL,
 create_program_id varchar(30),
 update_user_id varchar(30),
 update_datetime timestamptz,
 update_program_id varchar(30),
  CONSTRAINT t_sales_error_sales_transaction_header_pk
   PRIMARY KEY(transaction_id,order_sub_number,sales_transaction_id)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;

DROP TABLE IF EXISTS public.t_pay_off_data CASCADE;
CREATE TABLE public.t_pay_off_data(
 store_code varchar(10) NOT NULL,
 payoff_date varchar(8) NOT NULL,
 payoff_type_code varchar(6) NOT NULL,
 payoff_type_sub_number_code varchar(10) NOT NULL,
 cash_register_no numeric(3) NOT NULL,
 payoff_amount_currency_code varchar(3),
 payoff_amount numeric(24,4),
 payoff_quantity numeric(16,4),
 report_output_count numeric(5) DEFAULT 0 NOT NULL,
 processing_flag boolean DEFAULT FALSE NOT NULL,
 integrity_check_type varchar(2) NOT NULL,
 accounting_record_status numeric(1),
 batch_region numeric(2) NOT NULL,
 system_brand_code varchar(4),
 system_business_code varchar(10),
 system_country_code varchar(3),
 regular_time_error_notification_flag boolean DEFAULT FALSE NOT NULL,
 daily_summary_error_notification_flag boolean DEFAULT FALSE NOT NULL,
 advance_received_store_code varchar(10) NOT NULL,
 data_alteration_status varchar(20) NOT NULL,
 close_complete_flag boolean DEFAULT FALSE NOT NULL,
 create_user_id varchar(30),
 create_datetime timestamptz NOT NULL,
 create_program_id varchar(30),
 update_user_id varchar(30),
 update_datetime timestamptz,
 update_program_id varchar(30),
  CONSTRAINT t_pay_off_data_pk
   PRIMARY KEY(store_code,payoff_date,payoff_type_code,payoff_type_sub_number_code,cash_register_no,advance_received_store_code)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;
DROP TABLE IF EXISTS public.t_pile_up_pay_off_data CASCADE;
CREATE TABLE public.t_pile_up_pay_off_data(
 store_code varchar(10) NOT NULL,
 payoff_date varchar(8) NOT NULL,
 payoff_type_code varchar(6) NOT NULL,
 payoff_type_sub_number_code varchar(10) NOT NULL,
 cash_register_no numeric(3) NOT NULL,
 payoff_amount_currency_code varchar(3),
 payoff_amount numeric(24,4),
 payoff_quantity numeric(16,4),
 payoff_processing_flag boolean DEFAULT FALSE NOT NULL,
 batch_region numeric(2) NOT NULL,
 system_brand_code varchar(4),
 system_business_code varchar(10),
 system_country_code varchar(3),
 advance_received_store_code varchar(10) NOT NULL,
 create_user_id varchar(30),
 create_datetime timestamptz NOT NULL,
 create_program_id varchar(30),
 update_user_id varchar(30),
 update_datetime timestamptz,
 update_program_id varchar(30),
  CONSTRAINT t_pile_up_pay_off_data_pk
   PRIMARY KEY(store_code,payoff_date,payoff_type_code,payoff_type_sub_number_code,cash_register_no,advance_received_store_code)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;