package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDiscountOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDiscountOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDiscountOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationHistorySalesTransactionDiscountOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    long countByCondition(AlterationHistorySalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    int deleteByCondition(AlterationHistorySalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    int deleteByPrimaryKey(AlterationHistorySalesTransactionDiscountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    int insert(AlterationHistorySalesTransactionDiscountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    int insertSelective(AlterationHistorySalesTransactionDiscountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    List<AlterationHistorySalesTransactionDiscountOptional> selectByCondition(AlterationHistorySalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    AlterationHistorySalesTransactionDiscountOptional selectByPrimaryKey(AlterationHistorySalesTransactionDiscountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    int updateByConditionSelective(@Param("record") AlterationHistorySalesTransactionDiscountOptional record, @Param("example") AlterationHistorySalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    int updateByCondition(@Param("record") AlterationHistorySalesTransactionDiscountOptional record, @Param("example") AlterationHistorySalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    int updateByPrimaryKeySelective(AlterationHistorySalesTransactionDiscountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     */
    int updateByPrimaryKey(AlterationHistorySalesTransactionDiscountOptional record);
}
