package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistoryOrderInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistoryOrderInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistoryOrderInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationHistoryOrderInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    long countByCondition(AlterationHistoryOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    int deleteByCondition(AlterationHistoryOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    int deleteByPrimaryKey(AlterationHistoryOrderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    int insert(AlterationHistoryOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    int insertSelective(AlterationHistoryOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    List<AlterationHistoryOrderInformationOptional> selectByCondition(AlterationHistoryOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    AlterationHistoryOrderInformationOptional selectByPrimaryKey(AlterationHistoryOrderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    int updateByConditionSelective(@Param("record") AlterationHistoryOrderInformationOptional record, @Param("example") AlterationHistoryOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    int updateByCondition(@Param("record") AlterationHistoryOrderInformationOptional record, @Param("example") AlterationHistoryOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    int updateByPrimaryKeySelective(AlterationHistoryOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     */
    int updateByPrimaryKey(AlterationHistoryOrderInformationOptional record);
}
