package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDetailInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDetailInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDetailInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationHistorySalesTransactionDetailInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    long countByCondition(AlterationHistorySalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    int deleteByCondition(AlterationHistorySalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    int deleteByPrimaryKey(AlterationHistorySalesTransactionDetailInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    int insert(AlterationHistorySalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    int insertSelective(AlterationHistorySalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    List<AlterationHistorySalesTransactionDetailInformationOptional> selectByCondition(AlterationHistorySalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    AlterationHistorySalesTransactionDetailInformationOptional selectByPrimaryKey(AlterationHistorySalesTransactionDetailInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    int updateByConditionSelective(@Param("record") AlterationHistorySalesTransactionDetailInformationOptional record, @Param("example") AlterationHistorySalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    int updateByCondition(@Param("record") AlterationHistorySalesTransactionDetailInformationOptional record, @Param("example") AlterationHistorySalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    int updateByPrimaryKeySelective(AlterationHistorySalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail_info
     *
     */
    int updateByPrimaryKey(AlterationHistorySalesTransactionDetailInformationOptional record);
}
