package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistoryPayOffDataOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistoryPayOffDataOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistoryPayOffDataOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationHistoryPayOffDataOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    long countByCondition(AlterationHistoryPayOffDataOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    int deleteByCondition(AlterationHistoryPayOffDataOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    int deleteByPrimaryKey(AlterationHistoryPayOffDataOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    int insert(AlterationHistoryPayOffDataOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    int insertSelective(AlterationHistoryPayOffDataOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    List<AlterationHistoryPayOffDataOptional> selectByCondition(AlterationHistoryPayOffDataOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    AlterationHistoryPayOffDataOptional selectByPrimaryKey(AlterationHistoryPayOffDataOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    int updateByConditionSelective(@Param("record") AlterationHistoryPayOffDataOptional record, @Param("example") AlterationHistoryPayOffDataOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    int updateByCondition(@Param("record") AlterationHistoryPayOffDataOptional record, @Param("example") AlterationHistoryPayOffDataOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    int updateByPrimaryKeySelective(AlterationHistoryPayOffDataOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_pay_off_data
     *
     */
    int updateByPrimaryKey(AlterationHistoryPayOffDataOptional record);
}
