package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionTenderInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionTenderInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionTenderInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationHistorySalesTransactionTenderInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    long countByCondition(AlterationHistorySalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    int deleteByCondition(AlterationHistorySalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    int deleteByPrimaryKey(AlterationHistorySalesTransactionTenderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    int insert(AlterationHistorySalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    int insertSelective(AlterationHistorySalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    List<AlterationHistorySalesTransactionTenderInformationOptional> selectByCondition(AlterationHistorySalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    AlterationHistorySalesTransactionTenderInformationOptional selectByPrimaryKey(AlterationHistorySalesTransactionTenderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    int updateByConditionSelective(@Param("record") AlterationHistorySalesTransactionTenderInformationOptional record, @Param("example") AlterationHistorySalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    int updateByCondition(@Param("record") AlterationHistorySalesTransactionTenderInformationOptional record, @Param("example") AlterationHistorySalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    int updateByPrimaryKeySelective(AlterationHistorySalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_tender_info
     *
     */
    int updateByPrimaryKey(AlterationHistorySalesTransactionTenderInformationOptional record);
}
