package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationExclusionControlOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationExclusionControlOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationExclusionControlOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationExclusionControlOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    long countByCondition(AlterationExclusionControlOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int deleteByCondition(AlterationExclusionControlOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int deleteByPrimaryKey(AlterationExclusionControlOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int insert(AlterationExclusionControlOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int insertSelective(AlterationExclusionControlOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    List<AlterationExclusionControlOptional> selectByCondition(AlterationExclusionControlOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    AlterationExclusionControlOptional selectByPrimaryKey(AlterationExclusionControlOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int updateByConditionSelective(@Param("record") AlterationExclusionControlOptional record, @Param("example") AlterationExclusionControlOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int updateByCondition(@Param("record") AlterationExclusionControlOptional record, @Param("example") AlterationExclusionControlOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int updateByPrimaryKeySelective(AlterationExclusionControlOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_exclusion_control
     *
     */
    int updateByPrimaryKey(AlterationExclusionControlOptional record);
}
