package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionHeaderOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionHeaderOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionHeaderOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationHistorySalesTransactionHeaderOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    long countByCondition(AlterationHistorySalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    int deleteByCondition(AlterationHistorySalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    int deleteByPrimaryKey(AlterationHistorySalesTransactionHeaderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    int insert(AlterationHistorySalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    int insertSelective(AlterationHistorySalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    List<AlterationHistorySalesTransactionHeaderOptional> selectByCondition(AlterationHistorySalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    AlterationHistorySalesTransactionHeaderOptional selectByPrimaryKey(AlterationHistorySalesTransactionHeaderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    int updateByConditionSelective(@Param("record") AlterationHistorySalesTransactionHeaderOptional record, @Param("example") AlterationHistorySalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    int updateByCondition(@Param("record") AlterationHistorySalesTransactionHeaderOptional record, @Param("example") AlterationHistorySalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    int updateByPrimaryKeySelective(AlterationHistorySalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     */
    int updateByPrimaryKey(AlterationHistorySalesTransactionHeaderOptional record);
}
