package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionTotalAmountOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionTotalAmountOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionTotalAmountOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationHistorySalesTransactionTotalAmountOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    long countByCondition(AlterationHistorySalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    int deleteByCondition(AlterationHistorySalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    int deleteByPrimaryKey(AlterationHistorySalesTransactionTotalAmountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    int insert(AlterationHistorySalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    int insertSelective(AlterationHistorySalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    List<AlterationHistorySalesTransactionTotalAmountOptional> selectByCondition(AlterationHistorySalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    AlterationHistorySalesTransactionTotalAmountOptional selectByPrimaryKey(AlterationHistorySalesTransactionTotalAmountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    int updateByConditionSelective(@Param("record") AlterationHistorySalesTransactionTotalAmountOptional record, @Param("example") AlterationHistorySalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    int updateByCondition(@Param("record") AlterationHistorySalesTransactionTotalAmountOptional record, @Param("example") AlterationHistorySalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    int updateByPrimaryKeySelective(AlterationHistorySalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_total_amount
     *
     */
    int updateByPrimaryKey(AlterationHistorySalesTransactionTotalAmountOptional record);
}
