package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDetailOptional;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDetailOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.AlterationHistorySalesTransactionDetailOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AlterationHistorySalesTransactionDetailOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    long countByCondition(AlterationHistorySalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    int deleteByCondition(AlterationHistorySalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    int deleteByPrimaryKey(AlterationHistorySalesTransactionDetailOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    int insert(AlterationHistorySalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    int insertSelective(AlterationHistorySalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    List<AlterationHistorySalesTransactionDetailOptional> selectByCondition(AlterationHistorySalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    AlterationHistorySalesTransactionDetailOptional selectByPrimaryKey(AlterationHistorySalesTransactionDetailOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    int updateByConditionSelective(@Param("record") AlterationHistorySalesTransactionDetailOptional record, @Param("example") AlterationHistorySalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    int updateByCondition(@Param("record") AlterationHistorySalesTransactionDetailOptional record, @Param("example") AlterationHistorySalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    int updateByPrimaryKeySelective(AlterationHistorySalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     */
    int updateByPrimaryKey(AlterationHistorySalesTransactionDetailOptional record);
}
