/**
 * @(#)BusinessCountrySettingMasterOptionalMapper.java
 *
 *                                                     Copyright (c) 2018 Fast Retailing
 *                                                     Corporation.
 */

package com.fastretailing.dcp.sales.common.repository.optional;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.common.entity.optional.BusinessCountrySettingMasterOptional;
import com.fastretailing.dcp.sales.common.entity.optional.BusinessCountrySettingMasterOptionalCondition;

/**
 * Business country setting master optional mapper.
 *
 */
@Mapper
public interface BusinessCountrySettingMasterOptionalMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_business_country_state_setting.
     *
     */
    List<String> selectCodeL1List(BusinessCountrySettingMasterOptionalCondition condition);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_business_country_state_setting,m_store,m_trans_store_code.
     *
     */
    List<BusinessCountrySettingMasterOptional> selectStoreList(
            BusinessCountrySettingMasterOptionalCondition condition);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_business_country_state_setting.
     *
     */
    int countByCondition(String storeCode);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_business_country_state_setting.
     *
     */
    List<BusinessCountrySettingMasterOptional> selectStoreCodeL1(
            BusinessCountrySettingMasterOptionalCondition condition);
}
