package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDetailInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDetailInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDetailInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesTransactionDetailInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    long countByCondition(ErrorEvacuationSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesTransactionDetailInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    int insert(ErrorEvacuationSalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    int insertSelective(ErrorEvacuationSalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    List<ErrorEvacuationSalesTransactionDetailInformationOptional> selectByCondition(ErrorEvacuationSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    ErrorEvacuationSalesTransactionDetailInformationOptional selectByPrimaryKey(ErrorEvacuationSalesTransactionDetailInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesTransactionDetailInformationOptional record, @Param("example") ErrorEvacuationSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesTransactionDetailInformationOptional record, @Param("example") ErrorEvacuationSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesTransactionDetailInformationOptional record);
}
