package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionHeaderOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionHeaderOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionHeaderOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesTransactionHeaderOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    long countByCondition(ErrorEvacuationSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesTransactionHeaderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    int insert(ErrorEvacuationSalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    int insertSelective(ErrorEvacuationSalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    List<ErrorEvacuationSalesTransactionHeaderOptional> selectByCondition(ErrorEvacuationSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    ErrorEvacuationSalesTransactionHeaderOptional selectByPrimaryKey(ErrorEvacuationSalesTransactionHeaderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesTransactionHeaderOptional record, @Param("example") ErrorEvacuationSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesTransactionHeaderOptional record, @Param("example") ErrorEvacuationSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesTransactionHeaderOptional record);
}
