package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDetailOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDetailOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDetailOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesTransactionDetailOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    long countByCondition(ErrorEvacuationSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesTransactionDetailOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    int insert(ErrorEvacuationSalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    int insertSelective(ErrorEvacuationSalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    List<ErrorEvacuationSalesTransactionDetailOptional> selectByCondition(ErrorEvacuationSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    ErrorEvacuationSalesTransactionDetailOptional selectByPrimaryKey(ErrorEvacuationSalesTransactionDetailOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesTransactionDetailOptional record, @Param("example") ErrorEvacuationSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesTransactionDetailOptional record, @Param("example") ErrorEvacuationSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesTransactionDetailOptional record);
}
