package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTaxOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTaxOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTaxOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesTransactionTaxOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    long countByCondition(ErrorEvacuationSalesTransactionTaxOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionTaxOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesTransactionTaxOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    int insert(ErrorEvacuationSalesTransactionTaxOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    int insertSelective(ErrorEvacuationSalesTransactionTaxOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    List<ErrorEvacuationSalesTransactionTaxOptional> selectByCondition(ErrorEvacuationSalesTransactionTaxOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    ErrorEvacuationSalesTransactionTaxOptional selectByPrimaryKey(ErrorEvacuationSalesTransactionTaxOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesTransactionTaxOptional record, @Param("example") ErrorEvacuationSalesTransactionTaxOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesTransactionTaxOptional record, @Param("example") ErrorEvacuationSalesTransactionTaxOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesTransactionTaxOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesTransactionTaxOptional record);
}
