package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDiscountOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDiscountOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionDiscountOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesTransactionDiscountOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    long countByCondition(ErrorEvacuationSalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesTransactionDiscountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    int insert(ErrorEvacuationSalesTransactionDiscountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    int insertSelective(ErrorEvacuationSalesTransactionDiscountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    List<ErrorEvacuationSalesTransactionDiscountOptional> selectByCondition(ErrorEvacuationSalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    ErrorEvacuationSalesTransactionDiscountOptional selectByPrimaryKey(ErrorEvacuationSalesTransactionDiscountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesTransactionDiscountOptional record, @Param("example") ErrorEvacuationSalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesTransactionDiscountOptional record, @Param("example") ErrorEvacuationSalesTransactionDiscountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesTransactionDiscountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesTransactionDiscountOptional record);
}
