package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesOrderInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesOrderInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesOrderInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesOrderInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    long countByCondition(ErrorEvacuationSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    int deleteByCondition(ErrorEvacuationSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesOrderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    int insert(ErrorEvacuationSalesOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    int insertSelective(ErrorEvacuationSalesOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    List<ErrorEvacuationSalesOrderInformationOptional> selectByCondition(ErrorEvacuationSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    ErrorEvacuationSalesOrderInformationOptional selectByPrimaryKey(ErrorEvacuationSalesOrderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesOrderInformationOptional record, @Param("example") ErrorEvacuationSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesOrderInformationOptional record, @Param("example") ErrorEvacuationSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesOrderInformationOptional record);
}
