package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTenderInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTenderInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTenderInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesTransactionTenderInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    long countByCondition(ErrorEvacuationSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesTransactionTenderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    int insert(ErrorEvacuationSalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    int insertSelective(ErrorEvacuationSalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    List<ErrorEvacuationSalesTransactionTenderInformationOptional> selectByCondition(ErrorEvacuationSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    ErrorEvacuationSalesTransactionTenderInformationOptional selectByPrimaryKey(ErrorEvacuationSalesTransactionTenderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesTransactionTenderInformationOptional record, @Param("example") ErrorEvacuationSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesTransactionTenderInformationOptional record, @Param("example") ErrorEvacuationSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesTransactionTenderInformationOptional record);
}
