package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTenderOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTenderOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTenderOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesTransactionTenderOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    long countByCondition(ErrorEvacuationSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesTransactionTenderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    int insert(ErrorEvacuationSalesTransactionTenderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    int insertSelective(ErrorEvacuationSalesTransactionTenderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    List<ErrorEvacuationSalesTransactionTenderOptional> selectByCondition(ErrorEvacuationSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    ErrorEvacuationSalesTransactionTenderOptional selectByPrimaryKey(ErrorEvacuationSalesTransactionTenderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesTransactionTenderOptional record, @Param("example") ErrorEvacuationSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesTransactionTenderOptional record, @Param("example") ErrorEvacuationSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesTransactionTenderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesTransactionTenderOptional record);
}
