package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTotalAmountOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTotalAmountOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ErrorEvacuationSalesTransactionTotalAmountOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ErrorEvacuationSalesTransactionTotalAmountOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    long countByCondition(ErrorEvacuationSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    int deleteByPrimaryKey(ErrorEvacuationSalesTransactionTotalAmountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    int insert(ErrorEvacuationSalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    int insertSelective(ErrorEvacuationSalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    List<ErrorEvacuationSalesTransactionTotalAmountOptional> selectByCondition(ErrorEvacuationSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    ErrorEvacuationSalesTransactionTotalAmountOptional selectByPrimaryKey(ErrorEvacuationSalesTransactionTotalAmountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    int updateByConditionSelective(@Param("record") ErrorEvacuationSalesTransactionTotalAmountOptional record, @Param("example") ErrorEvacuationSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    int updateByCondition(@Param("record") ErrorEvacuationSalesTransactionTotalAmountOptional record, @Param("example") ErrorEvacuationSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    int updateByPrimaryKeySelective(ErrorEvacuationSalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     */
    int updateByPrimaryKey(ErrorEvacuationSalesTransactionTotalAmountOptional record);
}
