package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.ItemMasterOptional;
import com.fastretailing.dcp.sales.common.entity.optional.ItemMasterOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.ItemMasterOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemMasterOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    long countByCondition(ItemMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    int deleteByCondition(ItemMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    int deleteByPrimaryKey(ItemMasterOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    int insert(ItemMasterOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    int insertSelective(ItemMasterOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    List<ItemMasterOptional> selectByCondition(ItemMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    ItemMasterOptional selectByPrimaryKey(ItemMasterOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    int updateByConditionSelective(@Param("record") ItemMasterOptional record, @Param("example") ItemMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    int updateByCondition(@Param("record") ItemMasterOptional record, @Param("example") ItemMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    int updateByPrimaryKeySelective(ItemMasterOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     */
    int updateByPrimaryKey(ItemMasterOptional record);
}
