package com.fastretailing.dcp.sales.common.repository.optional;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.common.entity.optional.SalesReportTransactionHeaderOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesReportTransactionHeaderOptionalCondition;

@Mapper
public interface SalesReportTransactionHeaderOptionalMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_header
     *
     */
    List<SalesReportTransactionHeaderOptional> selectByCondition(
            SalesReportTransactionHeaderOptionalCondition example);
}
