package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesOrderInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesOrderInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesOrderInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SalesErrorSalesOrderInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    long countByCondition(SalesErrorSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    int deleteByCondition(SalesErrorSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    int deleteByPrimaryKey(SalesErrorSalesOrderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    int insert(SalesErrorSalesOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    int insertSelective(SalesErrorSalesOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    List<SalesErrorSalesOrderInformationOptional> selectByCondition(SalesErrorSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    SalesErrorSalesOrderInformationOptional selectByPrimaryKey(SalesErrorSalesOrderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    int updateByConditionSelective(@Param("record") SalesErrorSalesOrderInformationOptional record, @Param("example") SalesErrorSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    int updateByCondition(@Param("record") SalesErrorSalesOrderInformationOptional record, @Param("example") SalesErrorSalesOrderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    int updateByPrimaryKeySelective(SalesErrorSalesOrderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     */
    int updateByPrimaryKey(SalesErrorSalesOrderInformationOptional record);
}
