package com.fastretailing.dcp.sales.common.repository.optional;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.common.entity.optional.SalesReportTransactionTaxOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesReportTransactionTaxOptionalCondition;

@Mapper
public interface SalesReportTransactionTaxOptionalMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tax
     *
     */
    List<SalesReportTransactionTaxOptional> selectByCondition(
            SalesReportTransactionTaxOptionalCondition example);

}
