package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionDetailOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionDetailOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionDetailOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SalesErrorSalesTransactionDetailOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    long countByCondition(SalesErrorSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    int deleteByCondition(SalesErrorSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    int deleteByPrimaryKey(SalesErrorSalesTransactionDetailOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    int insert(SalesErrorSalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    int insertSelective(SalesErrorSalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    List<SalesErrorSalesTransactionDetailOptional> selectByCondition(SalesErrorSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    SalesErrorSalesTransactionDetailOptional selectByPrimaryKey(SalesErrorSalesTransactionDetailOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    int updateByConditionSelective(@Param("record") SalesErrorSalesTransactionDetailOptional record, @Param("example") SalesErrorSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    int updateByCondition(@Param("record") SalesErrorSalesTransactionDetailOptional record, @Param("example") SalesErrorSalesTransactionDetailOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    int updateByPrimaryKeySelective(SalesErrorSalesTransactionDetailOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     */
    int updateByPrimaryKey(SalesErrorSalesTransactionDetailOptional record);
}
