package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTotalAmountOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTotalAmountOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTotalAmountOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SalesErrorSalesTransactionTotalAmountOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    long countByCondition(SalesErrorSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    int deleteByCondition(SalesErrorSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    int deleteByPrimaryKey(SalesErrorSalesTransactionTotalAmountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    int insert(SalesErrorSalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    int insertSelective(SalesErrorSalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    List<SalesErrorSalesTransactionTotalAmountOptional> selectByCondition(SalesErrorSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    SalesErrorSalesTransactionTotalAmountOptional selectByPrimaryKey(SalesErrorSalesTransactionTotalAmountOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    int updateByConditionSelective(@Param("record") SalesErrorSalesTransactionTotalAmountOptional record, @Param("example") SalesErrorSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    int updateByCondition(@Param("record") SalesErrorSalesTransactionTotalAmountOptional record, @Param("example") SalesErrorSalesTransactionTotalAmountOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    int updateByPrimaryKeySelective(SalesErrorSalesTransactionTotalAmountOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     */
    int updateByPrimaryKey(SalesErrorSalesTransactionTotalAmountOptional record);
}
