package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionDetailInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionDetailInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionDetailInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SalesErrorSalesTransactionDetailInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    long countByCondition(SalesErrorSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    int deleteByCondition(SalesErrorSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    int deleteByPrimaryKey(SalesErrorSalesTransactionDetailInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    int insert(SalesErrorSalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    int insertSelective(SalesErrorSalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    List<SalesErrorSalesTransactionDetailInformationOptional> selectByCondition(SalesErrorSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    SalesErrorSalesTransactionDetailInformationOptional selectByPrimaryKey(SalesErrorSalesTransactionDetailInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    int updateByConditionSelective(@Param("record") SalesErrorSalesTransactionDetailInformationOptional record, @Param("example") SalesErrorSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    int updateByCondition(@Param("record") SalesErrorSalesTransactionDetailInformationOptional record, @Param("example") SalesErrorSalesTransactionDetailInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    int updateByPrimaryKeySelective(SalesErrorSalesTransactionDetailInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     */
    int updateByPrimaryKey(SalesErrorSalesTransactionDetailInformationOptional record);
}
