package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.SalesTransactionHistoryOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesTransactionHistoryOptionalCondition;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SalesTransactionHistoryOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    long countByCondition(SalesTransactionHistoryOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    int deleteByCondition(SalesTransactionHistoryOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    int deleteByPrimaryKey(String transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    int insert(SalesTransactionHistoryOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    int insertSelective(SalesTransactionHistoryOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    List<SalesTransactionHistoryOptional> selectByCondition(SalesTransactionHistoryOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    SalesTransactionHistoryOptional selectByPrimaryKey(String transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    int updateByConditionSelective(@Param("record") SalesTransactionHistoryOptional record, @Param("example") SalesTransactionHistoryOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    int updateByCondition(@Param("record") SalesTransactionHistoryOptional record, @Param("example") SalesTransactionHistoryOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    int updateByPrimaryKeySelective(SalesTransactionHistoryOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_history
     *
     */
    int updateByPrimaryKey(SalesTransactionHistoryOptional record);
}
