package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionHeaderOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionHeaderOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionHeaderOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SalesErrorSalesTransactionHeaderOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    long countByCondition(SalesErrorSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    int deleteByCondition(SalesErrorSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    int deleteByPrimaryKey(SalesErrorSalesTransactionHeaderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    int insert(SalesErrorSalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    int insertSelective(SalesErrorSalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    List<SalesErrorSalesTransactionHeaderOptional> selectByCondition(SalesErrorSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    SalesErrorSalesTransactionHeaderOptional selectByPrimaryKey(SalesErrorSalesTransactionHeaderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    int updateByConditionSelective(@Param("record") SalesErrorSalesTransactionHeaderOptional record, @Param("example") SalesErrorSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    int updateByCondition(@Param("record") SalesErrorSalesTransactionHeaderOptional record, @Param("example") SalesErrorSalesTransactionHeaderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    int updateByPrimaryKeySelective(SalesErrorSalesTransactionHeaderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     */
    int updateByPrimaryKey(SalesErrorSalesTransactionHeaderOptional record);
}
