package com.fastretailing.dcp.sales.common.repository.optional;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.common.entity.optional.SalesReportTransactionTenderOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesReportTransactionTenderOptionalCondition;

@Mapper
public interface SalesReportTransactionTenderOptionalMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_tender
     *
     */
    List<SalesReportTransactionTenderOptional> selectByCondition(
            SalesReportTransactionTenderOptionalCondition example);
}
