package com.fastretailing.dcp.sales.common.repository.optional;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.common.entity.optional.SalesReportTransactionDiscountDetailOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesReportTransactionDiscountDetailOptionalCondition;

@Mapper
public interface SalesReportTransactionDiscountDetailOptionalMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_sales_report_transaction_discount
     *
     */
    List<SalesReportTransactionDiscountDetailOptional> selectByCondition(
            SalesReportTransactionDiscountDetailOptionalCondition example);

}
