package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTenderOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTenderOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTenderOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SalesErrorSalesTransactionTenderOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    long countByCondition(SalesErrorSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    int deleteByCondition(SalesErrorSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    int deleteByPrimaryKey(SalesErrorSalesTransactionTenderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    int insert(SalesErrorSalesTransactionTenderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    int insertSelective(SalesErrorSalesTransactionTenderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    List<SalesErrorSalesTransactionTenderOptional> selectByCondition(SalesErrorSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    SalesErrorSalesTransactionTenderOptional selectByPrimaryKey(SalesErrorSalesTransactionTenderOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    int updateByConditionSelective(@Param("record") SalesErrorSalesTransactionTenderOptional record, @Param("example") SalesErrorSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    int updateByCondition(@Param("record") SalesErrorSalesTransactionTenderOptional record, @Param("example") SalesErrorSalesTransactionTenderOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    int updateByPrimaryKeySelective(SalesErrorSalesTransactionTenderOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     */
    int updateByPrimaryKey(SalesErrorSalesTransactionTenderOptional record);
}
