package com.fastretailing.dcp.sales.common.repository.optional;

import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTenderInformationOptional;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTenderInformationOptionalCondition;
import com.fastretailing.dcp.sales.common.entity.optional.SalesErrorSalesTransactionTenderInformationOptionalKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SalesErrorSalesTransactionTenderInformationOptionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    long countByCondition(SalesErrorSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    int deleteByCondition(SalesErrorSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    int deleteByPrimaryKey(SalesErrorSalesTransactionTenderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    int insert(SalesErrorSalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    int insertSelective(SalesErrorSalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    List<SalesErrorSalesTransactionTenderInformationOptional> selectByCondition(SalesErrorSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    SalesErrorSalesTransactionTenderInformationOptional selectByPrimaryKey(SalesErrorSalesTransactionTenderInformationOptionalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    int updateByConditionSelective(@Param("record") SalesErrorSalesTransactionTenderInformationOptional record, @Param("example") SalesErrorSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    int updateByCondition(@Param("record") SalesErrorSalesTransactionTenderInformationOptional record, @Param("example") SalesErrorSalesTransactionTenderInformationOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    int updateByPrimaryKeySelective(SalesErrorSalesTransactionTenderInformationOptional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender_info
     *
     */
    int updateByPrimaryKey(SalesErrorSalesTransactionTenderInformationOptional record);
}
