package com.fastretailing.dcp.sales.common.repository.optional;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.fastretailing.dcp.sales.common.entity.optional.TranslationStoreCodeMasterOptional;
import com.fastretailing.dcp.sales.common.entity.optional.TranslationStoreCodeMasterOptionalCondition;

@Mapper
public interface TranslationStoreCodeMasterOptionalMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    long countByCondition(TranslationStoreCodeMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    int deleteByCondition(TranslationStoreCodeMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    int deleteByPrimaryKey(String storeCode);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    int insert(TranslationStoreCodeMasterOptional record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    int insertSelective(TranslationStoreCodeMasterOptional record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    List<TranslationStoreCodeMasterOptional> selectByCondition(
            TranslationStoreCodeMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    TranslationStoreCodeMasterOptional selectByPrimaryKey(String storeCode);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    int updateByConditionSelective(@Param("record") TranslationStoreCodeMasterOptional record,
            @Param("example") TranslationStoreCodeMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    int updateByCondition(@Param("record") TranslationStoreCodeMasterOptional record,
            @Param("example") TranslationStoreCodeMasterOptionalCondition example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    int updateByPrimaryKeySelective(TranslationStoreCodeMasterOptional record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * m_trans_store_code
     *
     */
    int updateByPrimaryKey(TranslationStoreCodeMasterOptional record);
}
