package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.AlterationHistorySalesTransactionDetail;

@Mapper
public interface AlterationHistorySalesTransactionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_detail
     *
     * @mbg.generated
     */
    int insertSelective(AlterationHistorySalesTransactionDetail record);
}