package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.AlterationHistorySalesTransactionDiscount;

@Mapper
public interface AlterationHistorySalesTransactionDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_discount
     *
     * @mbg.generated
     */
    int insertSelective(AlterationHistorySalesTransactionDiscount record);
}