package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.AlterationHistoryOrderInformation;

@Mapper
public interface AlterationHistoryOrderInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_order_information
     *
     * @mbg.generated
     */
    int insertSelective(AlterationHistoryOrderInformation record);
}