package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.AlterationHistorySalesTransactionHeader;

@Mapper
public interface AlterationHistorySalesTransactionHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alteration_history_sales_transaction_header
     *
     * @mbg.generated
     */
    int insertSelective(AlterationHistorySalesTransactionHeader record);
}