package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.BusinessCountryStateSettingMaster;
import com.fastretailing.dcp.sales.importtransaction.entity.BusinessCountryStateSettingMasterCondition;

@Mapper
public interface BusinessCountryStateSettingMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_business_country_state_setting
     *
     * @mbg.generated
     */
    List<BusinessCountryStateSettingMaster> selectByCondition(BusinessCountryStateSettingMasterCondition example);
}