package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesOrderInformation;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesOrderInformationCondition;

@Mapper
public interface ErrorEvacuationSalesOrderInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesOrderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_order_information
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesOrderInformation record);
}