package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionHeader;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionHeaderCondition;

@Mapper
public interface ErrorEvacuationSalesTransactionHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionHeaderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_header
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesTransactionHeader record);
}