package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionDetailInfo;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionDetailInfoCondition;

@Mapper
public interface ErrorEvacuationSalesTransactionDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionDetailInfoCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail_info
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesTransactionDetailInfo record);
}