package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionTax;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionTaxCondition;

@Mapper
public interface ErrorEvacuationSalesTransactionTaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionTaxCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tax
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesTransactionTax record);
}