package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionTender;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionTenderCondition;

@Mapper
public interface ErrorEvacuationSalesTransactionTenderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionTenderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesTransactionTender record);
}