package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionDetail;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionDetailCondition;

@Mapper
public interface ErrorEvacuationSalesTransactionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionDetailCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_detail
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesTransactionDetail record);
}