package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionTenderInfo;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionTenderInfoCondition;

@Mapper
public interface ErrorEvacuationSalesTransactionTenderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionTenderInfoCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_tender_info
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesTransactionTenderInfo record);
}