package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionDiscount;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionDiscountCondition;

@Mapper
public interface ErrorEvacuationSalesTransactionDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionDiscountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_discount
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesTransactionDiscount record);
}