package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionTotalAmount;
import com.fastretailing.dcp.sales.importtransaction.entity.ErrorEvacuationSalesTransactionTotalAmountCondition;

@Mapper
public interface ErrorEvacuationSalesTransactionTotalAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     * @mbg.generated
     */
    int deleteByCondition(ErrorEvacuationSalesTransactionTotalAmountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_error_evacuation_sales_transaction_total_amount
     *
     * @mbg.generated
     */
    int insertSelective(ErrorEvacuationSalesTransactionTotalAmount record);
}