package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.ItemMaster;
import com.fastretailing.dcp.sales.importtransaction.entity.ItemMasterKey;

@Mapper
public interface ItemMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_item
     *
     * @mbg.generated
     */
    ItemMaster selectByPrimaryKey(ItemMasterKey key);
}