package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionHeader;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionHeaderCondition;

@Mapper
public interface SalesErrorSalesTransactionHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     * @mbg.generated
     */
    int deleteByCondition(SalesErrorSalesTransactionHeaderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     * @mbg.generated
     */
    int insertSelective(SalesErrorSalesTransactionHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_header
     *
     * @mbg.generated
     */
    List<SalesErrorSalesTransactionHeader> selectByCondition(SalesErrorSalesTransactionHeaderCondition example);
}