package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesTransactionHeader;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesTransactionHeaderCondition;

@Mapper
public interface SalesTransactionHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_header
     *
     * @mbg.generated
     */
    int insertSelective(SalesTransactionHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_header
     *
     * @mbg.generated
     */
    List<SalesTransactionHeader> selectByCondition(SalesTransactionHeaderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_header
     *
     * @mbg.generated
     */
    int updateByConditionSelective(@Param("record") SalesTransactionHeader record, @Param("example") SalesTransactionHeaderCondition example);
}