package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionDetailInfo;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionDetailInfoCondition;

@Mapper
public interface SalesErrorSalesTransactionDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     * @mbg.generated
     */
    int deleteByCondition(SalesErrorSalesTransactionDetailInfoCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     * @mbg.generated
     */
    int insertSelective(SalesErrorSalesTransactionDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail_info
     *
     * @mbg.generated
     */
    List<SalesErrorSalesTransactionDetailInfo> selectByCondition(SalesErrorSalesTransactionDetailInfoCondition example);
}