package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesTransactionDetail;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesTransactionDetailCondition;

@Mapper
public interface SalesTransactionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_detail
     *
     * @mbg.generated
     */
    int insertSelective(SalesTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_detail
     *
     * @mbg.generated
     */
    int updateByConditionSelective(@Param("record") SalesTransactionDetail record, @Param("example") SalesTransactionDetailCondition example);
}