package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesOrderInformation;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesOrderInformationCondition;

@Mapper
public interface SalesErrorSalesOrderInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     * @mbg.generated
     */
    int deleteByCondition(SalesErrorSalesOrderInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     * @mbg.generated
     */
    int insertSelective(SalesErrorSalesOrderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_order_information
     *
     * @mbg.generated
     */
    List<SalesErrorSalesOrderInformation> selectByCondition(SalesErrorSalesOrderInformationCondition example);
}