package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionDiscount;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionDiscountCondition;

@Mapper
public interface SalesErrorSalesTransactionDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_discount
     *
     * @mbg.generated
     */
    int deleteByCondition(SalesErrorSalesTransactionDiscountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_discount
     *
     * @mbg.generated
     */
    int insertSelective(SalesErrorSalesTransactionDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_discount
     *
     * @mbg.generated
     */
    List<SalesErrorSalesTransactionDiscount> selectByCondition(SalesErrorSalesTransactionDiscountCondition example);
}