package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionDetail;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionDetailCondition;

@Mapper
public interface SalesErrorSalesTransactionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     * @mbg.generated
     */
    int deleteByCondition(SalesErrorSalesTransactionDetailCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     * @mbg.generated
     */
    int insertSelective(SalesErrorSalesTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_detail
     *
     * @mbg.generated
     */
    List<SalesErrorSalesTransactionDetail> selectByCondition(SalesErrorSalesTransactionDetailCondition example);
}