package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionTender;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionTenderCondition;

@Mapper
public interface SalesErrorSalesTransactionTenderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     * @mbg.generated
     */
    int deleteByCondition(SalesErrorSalesTransactionTenderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     * @mbg.generated
     */
    int insertSelective(SalesErrorSalesTransactionTender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tender
     *
     * @mbg.generated
     */
    List<SalesErrorSalesTransactionTender> selectByCondition(SalesErrorSalesTransactionTenderCondition example);
}