package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionTax;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionTaxCondition;

@Mapper
public interface SalesErrorSalesTransactionTaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tax
     *
     * @mbg.generated
     */
    int deleteByCondition(SalesErrorSalesTransactionTaxCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tax
     *
     * @mbg.generated
     */
    int insertSelective(SalesErrorSalesTransactionTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_tax
     *
     * @mbg.generated
     */
    List<SalesErrorSalesTransactionTax> selectByCondition(SalesErrorSalesTransactionTaxCondition example);
}