package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionTotalAmount;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesErrorSalesTransactionTotalAmountCondition;

@Mapper
public interface SalesErrorSalesTransactionTotalAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     * @mbg.generated
     */
    int deleteByCondition(SalesErrorSalesTransactionTotalAmountCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     * @mbg.generated
     */
    int insertSelective(SalesErrorSalesTransactionTotalAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_error_sales_transaction_total_amount
     *
     * @mbg.generated
     */
    List<SalesErrorSalesTransactionTotalAmount> selectByCondition(SalesErrorSalesTransactionTotalAmountCondition example);
}