package com.fastretailing.dcp.sales.importtransaction.repository;

import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.SalesTransactionTenderTable;

@Mapper
public interface SalesTransactionTenderTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_transaction_tender
     *
     * @mbg.generated
     */
    int insertSelective(SalesTransactionTenderTable record);
}