package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.StoreGeneralPurposeMaster;
import com.fastretailing.dcp.sales.importtransaction.entity.StoreGeneralPurposeMasterCondition;

@Mapper
public interface StoreGeneralPurposeMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_general_purpose
     *
     * @mbg.generated
     */
    long countByCondition(StoreGeneralPurposeMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_store_general_purpose
     *
     * @mbg.generated
     */
    List<StoreGeneralPurposeMaster> selectByCondition(StoreGeneralPurposeMasterCondition example);
}