package com.fastretailing.dcp.sales.importtransaction.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.fastretailing.dcp.sales.importtransaction.entity.TranslationTenderMaster;
import com.fastretailing.dcp.sales.importtransaction.entity.TranslationTenderMasterCondition;

@Mapper
public interface TranslationTenderMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_trans_tender
     *
     * @mbg.generated
     */
    long countByCondition(TranslationTenderMasterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_trans_tender
     *
     * @mbg.generated
     */
    List<TranslationTenderMaster> selectByCondition(TranslationTenderMasterCondition example);
}