package com.fastretailing.dcp.sales.importtransaction.entity;

import lombok.Data;

@Data
public class AlterationHistoryOrderInformationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alteration_history_order_information.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alteration_history_order_information.integrated_order_id
     *
     * @mbg.generated
     */
    private String integratedOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alteration_history_order_information.history_type
     *
     * @mbg.generated
     */
    private Integer historyType;
}