package com.fastretailing.dcp.sales.importtransaction.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SalesTransactionTax extends SalesTransactionTaxKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.tax_sub_number
     *
     * @mbg.generated
     */
    private Integer taxSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.tax_amount_sign
     *
     * @mbg.generated
     */
    private String taxAmountSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.tax_amount_currency_code
     *
     * @mbg.generated
     */
    private String taxAmountCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.tax_amount_value
     *
     * @mbg.generated
     */
    private BigDecimal taxAmountValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.tax_rate
     *
     * @mbg.generated
     */
    private BigDecimal taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.tax_name
     *
     * @mbg.generated
     */
    private String taxName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.create_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.create_program_id
     *
     * @mbg.generated
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.update_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_tax.update_program_id
     *
     * @mbg.generated
     */
    private String updateProgramId;
}