package com.fastretailing.dcp.sales.importtransaction.entity;

import lombok.Data;

@Data
public class SalesErrorSalesOrderInformationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_order_information.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_order_information.integrated_order_id
     *
     * @mbg.generated
     */
    private String integratedOrderId;
}