package com.fastretailing.dcp.sales.importtransaction.entity;

import java.time.LocalDateTime;
import lombok.Data;

@Data
public class SalesTransactionHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_history.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_history.sales_transaction_data
     *
     * @mbg.generated
     */
    private String salesTransactionData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_history.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_history.create_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_history.create_program_id
     *
     * @mbg.generated
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_history.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_history.update_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_transaction_history.update_program_id
     *
     * @mbg.generated
     */
    private String updateProgramId;
}