package com.fastretailing.dcp.sales.importtransaction.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SalesErrorSalesTransactionHeader extends SalesErrorSalesTransactionHeaderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.integrated_order_id
     *
     * @mbg.generated
     */
    private String integratedOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.sales_transaction_sub_number
     *
     * @mbg.generated
     */
    private Integer salesTransactionSubNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.store_code
     *
     * @mbg.generated
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.data_creation_date_time
     *
     * @mbg.generated
     */
    private LocalDateTime dataCreationDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.data_creation_business_date
     *
     * @mbg.generated
     */
    private String dataCreationBusinessDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.cash_register_no
     *
     * @mbg.generated
     */
    private Integer cashRegisterNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receipt_no
     *
     * @mbg.generated
     */
    private String receiptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.sales_linkage_type
     *
     * @mbg.generated
     */
    private Integer salesLinkageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.sales_transaction_type
     *
     * @mbg.generated
     */
    private String salesTransactionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.return_type
     *
     * @mbg.generated
     */
    private Integer returnType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.system_brand_code
     *
     * @mbg.generated
     */
    private String systemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.system_business_code
     *
     * @mbg.generated
     */
    private String systemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.system_country_code
     *
     * @mbg.generated
     */
    private String systemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.channel_code
     *
     * @mbg.generated
     */
    private String channelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.order_substatus
     *
     * @mbg.generated
     */
    private String orderSubstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.order_status_update_date
     *
     * @mbg.generated
     */
    private String orderStatusUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.order_status_last_update_date_time
     *
     * @mbg.generated
     */
    private LocalDateTime orderStatusLastUpdateDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.order_cancelled_date_time
     *
     * @mbg.generated
     */
    private LocalDateTime orderCancelledDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.booking_store_code
     *
     * @mbg.generated
     */
    private String bookingStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.booking_store_system_brand_code
     *
     * @mbg.generated
     */
    private String bookingStoreSystemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.booking_store_system_business_code
     *
     * @mbg.generated
     */
    private String bookingStoreSystemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.booking_store_system_country_code
     *
     * @mbg.generated
     */
    private String bookingStoreSystemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.payment_status
     *
     * @mbg.generated
     */
    private String paymentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.payment_store_code
     *
     * @mbg.generated
     */
    private String paymentStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.payment_store_system_brand_code
     *
     * @mbg.generated
     */
    private String paymentStoreSystemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.payment_store_system_business_code
     *
     * @mbg.generated
     */
    private String paymentStoreSystemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.payment_store_system_country_code
     *
     * @mbg.generated
     */
    private String paymentStoreSystemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.transfer_out_status
     *
     * @mbg.generated
     */
    private String transferOutStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.shipment_status
     *
     * @mbg.generated
     */
    private String shipmentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.shipment_store_code
     *
     * @mbg.generated
     */
    private String shipmentStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.shipment_store_system_brand_code
     *
     * @mbg.generated
     */
    private String shipmentStoreSystemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.shipment_store_system_business_code
     *
     * @mbg.generated
     */
    private String shipmentStoreSystemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.shipment_store_system_country_code
     *
     * @mbg.generated
     */
    private String shipmentStoreSystemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receiving_status
     *
     * @mbg.generated
     */
    private String receivingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receipt_store_code
     *
     * @mbg.generated
     */
    private String receiptStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receipt_store_system_brand_code
     *
     * @mbg.generated
     */
    private String receiptStoreSystemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receipt_store_system_business_code
     *
     * @mbg.generated
     */
    private String receiptStoreSystemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receipt_store_system_country_code
     *
     * @mbg.generated
     */
    private String receiptStoreSystemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.customer_type
     *
     * @mbg.generated
     */
    private String customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.order_number_for_store_payment
     *
     * @mbg.generated
     */
    private String orderNumberForStorePayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.advance_received_store_code
     *
     * @mbg.generated
     */
    private String advanceReceivedStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.advance_received_store_system_brand_code
     *
     * @mbg.generated
     */
    private String advanceReceivedStoreSystemBrandCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.advance_received_store_system_business_code
     *
     * @mbg.generated
     */
    private String advanceReceivedStoreSystemBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.advance_received_store_system_country_code
     *
     * @mbg.generated
     */
    private String advanceReceivedStoreSystemCountryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.operator_code
     *
     * @mbg.generated
     */
    private String operatorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.original_transaction_id
     *
     * @mbg.generated
     */
    private String originalTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.original_cash_register_no
     *
     * @mbg.generated
     */
    private Integer originalCashRegisterNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.original_receipt_no
     *
     * @mbg.generated
     */
    private String originalReceiptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.deposit_currency_code
     *
     * @mbg.generated
     */
    private String depositCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.deposit_value
     *
     * @mbg.generated
     */
    private BigDecimal depositValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.change_currency_code
     *
     * @mbg.generated
     */
    private String changeCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.change_value
     *
     * @mbg.generated
     */
    private BigDecimal changeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receipt_no_for_credit_card_cancellation
     *
     * @mbg.generated
     */
    private String receiptNoForCreditCardCancellation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receipt_no_for_credit_card
     *
     * @mbg.generated
     */
    private String receiptNoForCreditCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.receipt_issued_flag
     *
     * @mbg.generated
     */
    private boolean receiptIssuedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.e_receipt_target_flag
     *
     * @mbg.generated
     */
    private boolean eReceiptTargetFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.processing_company_code
     *
     * @mbg.generated
     */
    private String processingCompanyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.employee_sale_flag
     *
     * @mbg.generated
     */
    private boolean employeeSaleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.consistency_sales_flag
     *
     * @mbg.generated
     */
    private boolean consistencySalesFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.corporate_id
     *
     * @mbg.generated
     */
    private String corporateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.sales_transaction_discount_flag
     *
     * @mbg.generated
     */
    private boolean salesTransactionDiscountFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.sales_transaction_discount_type
     *
     * @mbg.generated
     */
    private String salesTransactionDiscountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.sales_transaction_discount_amount_rate_currency_code
     *
     * @mbg.generated
     */
    private String salesTransactionDiscountAmountRateCurrencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.sales_transaction_discount_amount_rate
     *
     * @mbg.generated
     */
    private BigDecimal salesTransactionDiscountAmountRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.token_code
     *
     * @mbg.generated
     */
    private String tokenCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.create_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.create_program_id
     *
     * @mbg.generated
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.update_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sales_error_sales_transaction_header.update_program_id
     *
     * @mbg.generated
     */
    private String updateProgramId;
}