package com.fastretailing.dcp.sales.importtransaction.entity;

import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TranslationTenderMaster extends TranslationTenderMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.tender_group
     *
     * @mbg.generated
     */
    private String tenderGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.valid_date
     *
     * @mbg.generated
     */
    private LocalDateTime validDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.ims_tender_id
     *
     * @mbg.generated
     */
    private Integer imsTenderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.ims_tender_group
     *
     * @mbg.generated
     */
    private String imsTenderGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.create_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.create_program_id
     *
     * @mbg.generated
     */
    private String createProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.update_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_trans_tender.update_program_id
     *
     * @mbg.generated
     */
    private String updateProgramId;
}