package com.fastretailing.dcp.sales.common.repository.work;

import com.fastretailing.dcp.sales.common.entity.work.ItemWork;
import com.fastretailing.dcp.sales.common.entity.work.ItemWorkCondition;
import com.fastretailing.dcp.sales.common.entity.work.ItemWorkKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    long countByCondition(ItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    int deleteByCondition(ItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    int deleteByPrimaryKey(ItemWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    int insert(ItemWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    int insertSelective(ItemWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    List<ItemWork> selectByCondition(ItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    ItemWork selectByPrimaryKey(ItemWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    int updateByConditionSelective(@Param("record") ItemWork record, @Param("example") ItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    int updateByCondition(@Param("record") ItemWork record, @Param("example") ItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    int updateByPrimaryKeySelective(ItemWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item
     *
     */
    int updateByPrimaryKey(ItemWork record);
}
