package com.fastretailing.dcp.sales.common.repository.work;

import com.fastretailing.dcp.sales.common.entity.work.ItemHierarchyMajorWork;
import com.fastretailing.dcp.sales.common.entity.work.ItemHierarchyMajorWorkCondition;
import com.fastretailing.dcp.sales.common.entity.work.ItemHierarchyMajorWorkKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemHierarchyMajorWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    long countByCondition(ItemHierarchyMajorWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    int deleteByCondition(ItemHierarchyMajorWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    int deleteByPrimaryKey(ItemHierarchyMajorWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    int insert(ItemHierarchyMajorWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    int insertSelective(ItemHierarchyMajorWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    List<ItemHierarchyMajorWork> selectByCondition(ItemHierarchyMajorWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    ItemHierarchyMajorWork selectByPrimaryKey(ItemHierarchyMajorWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    int updateByConditionSelective(@Param("record") ItemHierarchyMajorWork record, @Param("example") ItemHierarchyMajorWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    int updateByCondition(@Param("record") ItemHierarchyMajorWork record, @Param("example") ItemHierarchyMajorWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    int updateByPrimaryKeySelective(ItemHierarchyMajorWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_item_hierarchy_major_category
     *
     */
    int updateByPrimaryKey(ItemHierarchyMajorWork record);
}
