package com.fastretailing.dcp.sales.common.repository.work;

import com.fastretailing.dcp.sales.common.entity.work.NonItemWork;
import com.fastretailing.dcp.sales.common.entity.work.NonItemWorkCondition;
import com.fastretailing.dcp.sales.common.entity.work.NonItemWorkKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface NonItemWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    long countByCondition(NonItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    int deleteByCondition(NonItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    int deleteByPrimaryKey(NonItemWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    int insert(NonItemWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    int insertSelective(NonItemWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    List<NonItemWork> selectByCondition(NonItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    NonItemWork selectByPrimaryKey(NonItemWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    int updateByConditionSelective(@Param("record") NonItemWork record, @Param("example") NonItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    int updateByCondition(@Param("record") NonItemWork record, @Param("example") NonItemWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    int updateByPrimaryKeySelective(NonItemWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_non_item
     *
     */
    int updateByPrimaryKey(NonItemWork record);
}
