package com.fastretailing.dcp.sales.common.repository.work;

import com.fastretailing.dcp.sales.common.entity.work.SkulistParentWork;
import com.fastretailing.dcp.sales.common.entity.work.SkulistParentWorkCondition;
import com.fastretailing.dcp.sales.common.entity.work.SkulistParentWorkKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SkulistParentWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    long countByCondition(SkulistParentWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    int deleteByCondition(SkulistParentWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    int deleteByPrimaryKey(SkulistParentWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    int insert(SkulistParentWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    int insertSelective(SkulistParentWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    List<SkulistParentWork> selectByCondition(SkulistParentWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    SkulistParentWork selectByPrimaryKey(SkulistParentWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    int updateByConditionSelective(@Param("record") SkulistParentWork record, @Param("example") SkulistParentWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    int updateByCondition(@Param("record") SkulistParentWork record, @Param("example") SkulistParentWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    int updateByPrimaryKeySelective(SkulistParentWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_parent
     *
     */
    int updateByPrimaryKey(SkulistParentWork record);
}
