package com.fastretailing.dcp.sales.common.repository.work;

import com.fastretailing.dcp.sales.common.entity.work.SkulistChildWork;
import com.fastretailing.dcp.sales.common.entity.work.SkulistChildWorkCondition;
import com.fastretailing.dcp.sales.common.entity.work.SkulistChildWorkKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SkulistChildWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    long countByCondition(SkulistChildWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    int deleteByCondition(SkulistChildWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    int deleteByPrimaryKey(SkulistChildWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    int insert(SkulistChildWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    int insertSelective(SkulistChildWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    List<SkulistChildWork> selectByCondition(SkulistChildWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    SkulistChildWork selectByPrimaryKey(SkulistChildWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    int updateByConditionSelective(@Param("record") SkulistChildWork record, @Param("example") SkulistChildWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    int updateByCondition(@Param("record") SkulistChildWork record, @Param("example") SkulistChildWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    int updateByPrimaryKeySelective(SkulistChildWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_skulist_child
     *
     */
    int updateByPrimaryKey(SkulistChildWork record);
}
