package com.fastretailing.dcp.sales.common.repository.work;

import com.fastretailing.dcp.sales.common.entity.work.StoreWork;
import com.fastretailing.dcp.sales.common.entity.work.StoreWorkCondition;
import com.fastretailing.dcp.sales.common.entity.work.StoreWorkKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StoreWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    long countByCondition(StoreWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    int deleteByCondition(StoreWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    int deleteByPrimaryKey(StoreWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    int insert(StoreWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    int insertSelective(StoreWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    List<StoreWork> selectByCondition(StoreWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    StoreWork selectByPrimaryKey(StoreWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    int updateByConditionSelective(@Param("record") StoreWork record, @Param("example") StoreWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    int updateByCondition(@Param("record") StoreWork record, @Param("example") StoreWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    int updateByPrimaryKeySelective(StoreWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_store
     *
     */
    int updateByPrimaryKey(StoreWork record);
}
