package com.fastretailing.dcp.sales.common.repository.work;

import com.fastretailing.dcp.sales.common.entity.work.TenderWork;
import com.fastretailing.dcp.sales.common.entity.work.TenderWorkCondition;
import com.fastretailing.dcp.sales.common.entity.work.TenderWorkKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TenderWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    long countByCondition(TenderWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    int deleteByCondition(TenderWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    int deleteByPrimaryKey(TenderWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    int insert(TenderWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    int insertSelective(TenderWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    List<TenderWork> selectByCondition(TenderWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    TenderWork selectByPrimaryKey(TenderWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    int updateByConditionSelective(@Param("record") TenderWork record, @Param("example") TenderWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    int updateByCondition(@Param("record") TenderWork record, @Param("example") TenderWorkCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    int updateByPrimaryKeySelective(TenderWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tender
     *
     */
    int updateByPrimaryKey(TenderWork record);
}
